/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.tsp.sct.dao.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the call_center_foliado table.
 */
public class CallCenterFoliadoPk implements Serializable
{
	protected int idCallCenterFoliado;

	/** 
	 * This attribute represents whether the primitive attribute idCallCenterFoliado is null.
	 */
	protected boolean idCallCenterFoliadoNull;

	/** 
	 * Sets the value of idCallCenterFoliado
	 */
	public void setIdCallCenterFoliado(int idCallCenterFoliado)
	{
		this.idCallCenterFoliado = idCallCenterFoliado;
	}

	/** 
	 * Gets the value of idCallCenterFoliado
	 */
	public int getIdCallCenterFoliado()
	{
		return idCallCenterFoliado;
	}

	/**
	 * Method 'CallCenterFoliadoPk'
	 * 
	 */
	public CallCenterFoliadoPk()
	{
	}

	/**
	 * Method 'CallCenterFoliadoPk'
	 * 
	 * @param idCallCenterFoliado
	 */
	public CallCenterFoliadoPk(final int idCallCenterFoliado)
	{
		this.idCallCenterFoliado = idCallCenterFoliado;
	}

	/** 
	 * Sets the value of idCallCenterFoliadoNull
	 */
	public void setIdCallCenterFoliadoNull(boolean idCallCenterFoliadoNull)
	{
		this.idCallCenterFoliadoNull = idCallCenterFoliadoNull;
	}

	/** 
	 * Gets the value of idCallCenterFoliadoNull
	 */
	public boolean isIdCallCenterFoliadoNull()
	{
		return idCallCenterFoliadoNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof CallCenterFoliadoPk)) {
			return false;
		}
		
		final CallCenterFoliadoPk _cast = (CallCenterFoliadoPk) _other;
		if (idCallCenterFoliado != _cast.idCallCenterFoliado) {
			return false;
		}
		
		if (idCallCenterFoliadoNull != _cast.idCallCenterFoliadoNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idCallCenterFoliado;
		_hashCode = 29 * _hashCode + (idCallCenterFoliadoNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.tsp.sct.dao.dto.CallCenterFoliadoPk: " );
		ret.append( "idCallCenterFoliado=" + idCallCenterFoliado );
		return ret.toString();
	}

}
