/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.tsp.sct.dao.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the comprobante_descripcion_perflores table.
 */
public class ComprobanteDescripcionPerfloresPk implements Serializable
{
	protected int idComprobanteDescripcion;

	/** 
	 * This attribute represents whether the primitive attribute idComprobanteDescripcion is null.
	 */
	protected boolean idComprobanteDescripcionNull;

	/** 
	 * Sets the value of idComprobanteDescripcion
	 */
	public void setIdComprobanteDescripcion(int idComprobanteDescripcion)
	{
		this.idComprobanteDescripcion = idComprobanteDescripcion;
	}

	/** 
	 * Gets the value of idComprobanteDescripcion
	 */
	public int getIdComprobanteDescripcion()
	{
		return idComprobanteDescripcion;
	}

	/**
	 * Method 'ComprobanteDescripcionPerfloresPk'
	 * 
	 */
	public ComprobanteDescripcionPerfloresPk()
	{
	}

	/**
	 * Method 'ComprobanteDescripcionPerfloresPk'
	 * 
	 * @param idComprobanteDescripcion
	 */
	public ComprobanteDescripcionPerfloresPk(final int idComprobanteDescripcion)
	{
		this.idComprobanteDescripcion = idComprobanteDescripcion;
	}

	/** 
	 * Sets the value of idComprobanteDescripcionNull
	 */
	public void setIdComprobanteDescripcionNull(boolean idComprobanteDescripcionNull)
	{
		this.idComprobanteDescripcionNull = idComprobanteDescripcionNull;
	}

	/** 
	 * Gets the value of idComprobanteDescripcionNull
	 */
	public boolean isIdComprobanteDescripcionNull()
	{
		return idComprobanteDescripcionNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof ComprobanteDescripcionPerfloresPk)) {
			return false;
		}
		
		final ComprobanteDescripcionPerfloresPk _cast = (ComprobanteDescripcionPerfloresPk) _other;
		if (idComprobanteDescripcion != _cast.idComprobanteDescripcion) {
			return false;
		}
		
		if (idComprobanteDescripcionNull != _cast.idComprobanteDescripcionNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idComprobanteDescripcion;
		_hashCode = 29 * _hashCode + (idComprobanteDescripcionNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.tsp.sct.dao.dto.ComprobanteDescripcionPerfloresPk: " );
		ret.append( "idComprobanteDescripcion=" + idComprobanteDescripcion );
		return ret.toString();
	}

}
