/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.tsp.sct.dao.dto;

import com.tsp.sct.dao.dao.*;
import com.tsp.sct.dao.factory.*;
import com.tsp.sct.dao.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class CrProductoSeguro implements Serializable
{
	/** 
	 * This attribute maps to the column id_producto_seguro in the cr_producto_seguro table.
	 */
	protected int idProductoSeguro;

	/** 
	 * This attribute represents whether the attribute idProductoSeguro has been modified since being read from the database.
	 */
	protected boolean idProductoSeguroModified = false;

	/** 
	 * This attribute maps to the column id_producto_credito in the cr_producto_seguro table.
	 */
	protected int idProductoCredito;

	/** 
	 * This attribute represents whether the attribute idProductoCredito has been modified since being read from the database.
	 */
	protected boolean idProductoCreditoModified = false;

	/** 
	 * This attribute maps to the column is_obligatorio in the cr_producto_seguro table.
	 */
	protected int isObligatorio;

	/** 
	 * This attribute represents whether the attribute isObligatorio has been modified since being read from the database.
	 */
	protected boolean isObligatorioModified = false;

	/** 
	 * This attribute maps to the column tipo_seguro in the cr_producto_seguro table.
	 */
	protected String tipoSeguro;

	/** 
	 * This attribute represents whether the attribute tipoSeguro has been modified since being read from the database.
	 */
	protected boolean tipoSeguroModified = false;

	/** 
	 * This attribute maps to the column aseguradora_nombre in the cr_producto_seguro table.
	 */
	protected String aseguradoraNombre;

	/** 
	 * This attribute represents whether the attribute aseguradoraNombre has been modified since being read from the database.
	 */
	protected boolean aseguradoraNombreModified = false;

	/** 
	 * This attribute maps to the column id_estatus in the cr_producto_seguro table.
	 */
	protected int idEstatus;

	/** 
	 * This attribute represents whether the attribute idEstatus has been modified since being read from the database.
	 */
	protected boolean idEstatusModified = false;

	/** 
	 * This attribute maps to the column id_empresa in the cr_producto_seguro table.
	 */
	protected int idEmpresa;

	/** 
	 * This attribute represents whether the attribute idEmpresa has been modified since being read from the database.
	 */
	protected boolean idEmpresaModified = false;

	/**
	 * Method 'CrProductoSeguro'
	 * 
	 */
	public CrProductoSeguro()
	{
	}

	/**
	 * Method 'getIdProductoSeguro'
	 * 
	 * @return int
	 */
	public int getIdProductoSeguro()
	{
		return idProductoSeguro;
	}

	/**
	 * Method 'setIdProductoSeguro'
	 * 
	 * @param idProductoSeguro
	 */
	public void setIdProductoSeguro(int idProductoSeguro)
	{
		this.idProductoSeguro = idProductoSeguro;
		this.idProductoSeguroModified = true;
	}

	/** 
	 * Sets the value of idProductoSeguroModified
	 */
	public void setIdProductoSeguroModified(boolean idProductoSeguroModified)
	{
		this.idProductoSeguroModified = idProductoSeguroModified;
	}

	/** 
	 * Gets the value of idProductoSeguroModified
	 */
	public boolean isIdProductoSeguroModified()
	{
		return idProductoSeguroModified;
	}

	/**
	 * Method 'getIdProductoCredito'
	 * 
	 * @return int
	 */
	public int getIdProductoCredito()
	{
		return idProductoCredito;
	}

	/**
	 * Method 'setIdProductoCredito'
	 * 
	 * @param idProductoCredito
	 */
	public void setIdProductoCredito(int idProductoCredito)
	{
		this.idProductoCredito = idProductoCredito;
		this.idProductoCreditoModified = true;
	}

	/** 
	 * Sets the value of idProductoCreditoModified
	 */
	public void setIdProductoCreditoModified(boolean idProductoCreditoModified)
	{
		this.idProductoCreditoModified = idProductoCreditoModified;
	}

	/** 
	 * Gets the value of idProductoCreditoModified
	 */
	public boolean isIdProductoCreditoModified()
	{
		return idProductoCreditoModified;
	}

	/**
	 * Method 'getIsObligatorio'
	 * 
	 * @return int
	 */
	public int getIsObligatorio()
	{
		return isObligatorio;
	}

	/**
	 * Method 'setIsObligatorio'
	 * 
	 * @param isObligatorio
	 */
	public void setIsObligatorio(int isObligatorio)
	{
		this.isObligatorio = isObligatorio;
		this.isObligatorioModified = true;
	}

	/** 
	 * Sets the value of isObligatorioModified
	 */
	public void setIsObligatorioModified(boolean isObligatorioModified)
	{
		this.isObligatorioModified = isObligatorioModified;
	}

	/** 
	 * Gets the value of isObligatorioModified
	 */
	public boolean isIsObligatorioModified()
	{
		return isObligatorioModified;
	}

	/**
	 * Method 'getTipoSeguro'
	 * 
	 * @return String
	 */
	public String getTipoSeguro()
	{
		return tipoSeguro;
	}

	/**
	 * Method 'setTipoSeguro'
	 * 
	 * @param tipoSeguro
	 */
	public void setTipoSeguro(String tipoSeguro)
	{
		this.tipoSeguro = tipoSeguro;
		this.tipoSeguroModified = true;
	}

	/** 
	 * Sets the value of tipoSeguroModified
	 */
	public void setTipoSeguroModified(boolean tipoSeguroModified)
	{
		this.tipoSeguroModified = tipoSeguroModified;
	}

	/** 
	 * Gets the value of tipoSeguroModified
	 */
	public boolean isTipoSeguroModified()
	{
		return tipoSeguroModified;
	}

	/**
	 * Method 'getAseguradoraNombre'
	 * 
	 * @return String
	 */
	public String getAseguradoraNombre()
	{
		return aseguradoraNombre;
	}

	/**
	 * Method 'setAseguradoraNombre'
	 * 
	 * @param aseguradoraNombre
	 */
	public void setAseguradoraNombre(String aseguradoraNombre)
	{
		this.aseguradoraNombre = aseguradoraNombre;
		this.aseguradoraNombreModified = true;
	}

	/** 
	 * Sets the value of aseguradoraNombreModified
	 */
	public void setAseguradoraNombreModified(boolean aseguradoraNombreModified)
	{
		this.aseguradoraNombreModified = aseguradoraNombreModified;
	}

	/** 
	 * Gets the value of aseguradoraNombreModified
	 */
	public boolean isAseguradoraNombreModified()
	{
		return aseguradoraNombreModified;
	}

	/**
	 * Method 'getIdEstatus'
	 * 
	 * @return int
	 */
	public int getIdEstatus()
	{
		return idEstatus;
	}

	/**
	 * Method 'setIdEstatus'
	 * 
	 * @param idEstatus
	 */
	public void setIdEstatus(int idEstatus)
	{
		this.idEstatus = idEstatus;
		this.idEstatusModified = true;
	}

	/** 
	 * Sets the value of idEstatusModified
	 */
	public void setIdEstatusModified(boolean idEstatusModified)
	{
		this.idEstatusModified = idEstatusModified;
	}

	/** 
	 * Gets the value of idEstatusModified
	 */
	public boolean isIdEstatusModified()
	{
		return idEstatusModified;
	}

	/**
	 * Method 'getIdEmpresa'
	 * 
	 * @return int
	 */
	public int getIdEmpresa()
	{
		return idEmpresa;
	}

	/**
	 * Method 'setIdEmpresa'
	 * 
	 * @param idEmpresa
	 */
	public void setIdEmpresa(int idEmpresa)
	{
		this.idEmpresa = idEmpresa;
		this.idEmpresaModified = true;
	}

	/** 
	 * Sets the value of idEmpresaModified
	 */
	public void setIdEmpresaModified(boolean idEmpresaModified)
	{
		this.idEmpresaModified = idEmpresaModified;
	}

	/** 
	 * Gets the value of idEmpresaModified
	 */
	public boolean isIdEmpresaModified()
	{
		return idEmpresaModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof CrProductoSeguro)) {
			return false;
		}
		
		final CrProductoSeguro _cast = (CrProductoSeguro) _other;
		if (idProductoSeguro != _cast.idProductoSeguro) {
			return false;
		}
		
		if (idProductoSeguroModified != _cast.idProductoSeguroModified) {
			return false;
		}
		
		if (idProductoCredito != _cast.idProductoCredito) {
			return false;
		}
		
		if (idProductoCreditoModified != _cast.idProductoCreditoModified) {
			return false;
		}
		
		if (isObligatorio != _cast.isObligatorio) {
			return false;
		}
		
		if (isObligatorioModified != _cast.isObligatorioModified) {
			return false;
		}
		
		if (tipoSeguro == null ? _cast.tipoSeguro != tipoSeguro : !tipoSeguro.equals( _cast.tipoSeguro )) {
			return false;
		}
		
		if (tipoSeguroModified != _cast.tipoSeguroModified) {
			return false;
		}
		
		if (aseguradoraNombre == null ? _cast.aseguradoraNombre != aseguradoraNombre : !aseguradoraNombre.equals( _cast.aseguradoraNombre )) {
			return false;
		}
		
		if (aseguradoraNombreModified != _cast.aseguradoraNombreModified) {
			return false;
		}
		
		if (idEstatus != _cast.idEstatus) {
			return false;
		}
		
		if (idEstatusModified != _cast.idEstatusModified) {
			return false;
		}
		
		if (idEmpresa != _cast.idEmpresa) {
			return false;
		}
		
		if (idEmpresaModified != _cast.idEmpresaModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idProductoSeguro;
		_hashCode = 29 * _hashCode + (idProductoSeguroModified ? 1 : 0);
		_hashCode = 29 * _hashCode + idProductoCredito;
		_hashCode = 29 * _hashCode + (idProductoCreditoModified ? 1 : 0);
		_hashCode = 29 * _hashCode + isObligatorio;
		_hashCode = 29 * _hashCode + (isObligatorioModified ? 1 : 0);
		if (tipoSeguro != null) {
			_hashCode = 29 * _hashCode + tipoSeguro.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (tipoSeguroModified ? 1 : 0);
		if (aseguradoraNombre != null) {
			_hashCode = 29 * _hashCode + aseguradoraNombre.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (aseguradoraNombreModified ? 1 : 0);
		_hashCode = 29 * _hashCode + idEstatus;
		_hashCode = 29 * _hashCode + (idEstatusModified ? 1 : 0);
		_hashCode = 29 * _hashCode + idEmpresa;
		_hashCode = 29 * _hashCode + (idEmpresaModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return CrProductoSeguroPk
	 */
	public CrProductoSeguroPk createPk()
	{
		return new CrProductoSeguroPk(idProductoSeguro);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.tsp.sct.dao.dto.CrProductoSeguro: " );
		ret.append( "idProductoSeguro=" + idProductoSeguro );
		ret.append( ", idProductoCredito=" + idProductoCredito );
		ret.append( ", isObligatorio=" + isObligatorio );
		ret.append( ", tipoSeguro=" + tipoSeguro );
		ret.append( ", aseguradoraNombre=" + aseguradoraNombre );
		ret.append( ", idEstatus=" + idEstatus );
		ret.append( ", idEmpresa=" + idEmpresa );
		return ret.toString();
	}

}
