/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.tsp.sct.dao.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the cr_producto_seguro table.
 */
public class CrProductoSeguroPk implements Serializable
{
	protected int idProductoSeguro;

	/** 
	 * This attribute represents whether the primitive attribute idProductoSeguro is null.
	 */
	protected boolean idProductoSeguroNull;

	/** 
	 * Sets the value of idProductoSeguro
	 */
	public void setIdProductoSeguro(int idProductoSeguro)
	{
		this.idProductoSeguro = idProductoSeguro;
	}

	/** 
	 * Gets the value of idProductoSeguro
	 */
	public int getIdProductoSeguro()
	{
		return idProductoSeguro;
	}

	/**
	 * Method 'CrProductoSeguroPk'
	 * 
	 */
	public CrProductoSeguroPk()
	{
	}

	/**
	 * Method 'CrProductoSeguroPk'
	 * 
	 * @param idProductoSeguro
	 */
	public CrProductoSeguroPk(final int idProductoSeguro)
	{
		this.idProductoSeguro = idProductoSeguro;
	}

	/** 
	 * Sets the value of idProductoSeguroNull
	 */
	public void setIdProductoSeguroNull(boolean idProductoSeguroNull)
	{
		this.idProductoSeguroNull = idProductoSeguroNull;
	}

	/** 
	 * Gets the value of idProductoSeguroNull
	 */
	public boolean isIdProductoSeguroNull()
	{
		return idProductoSeguroNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof CrProductoSeguroPk)) {
			return false;
		}
		
		final CrProductoSeguroPk _cast = (CrProductoSeguroPk) _other;
		if (idProductoSeguro != _cast.idProductoSeguro) {
			return false;
		}
		
		if (idProductoSeguroNull != _cast.idProductoSeguroNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idProductoSeguro;
		_hashCode = 29 * _hashCode + (idProductoSeguroNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.tsp.sct.dao.dto.CrProductoSeguroPk: " );
		ret.append( "idProductoSeguro=" + idProductoSeguro );
		return ret.toString();
	}

}
