/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.tsp.sct.dao.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the detalle_edc table.
 */
public class DetalleEdcPk implements Serializable
{
	protected int idDetalleEdc;

	/** 
	 * This attribute represents whether the primitive attribute idDetalleEdc is null.
	 */
	protected boolean idDetalleEdcNull;

	/** 
	 * Sets the value of idDetalleEdc
	 */
	public void setIdDetalleEdc(int idDetalleEdc)
	{
		this.idDetalleEdc = idDetalleEdc;
	}

	/** 
	 * Gets the value of idDetalleEdc
	 */
	public int getIdDetalleEdc()
	{
		return idDetalleEdc;
	}

	/**
	 * Method 'DetalleEdcPk'
	 * 
	 */
	public DetalleEdcPk()
	{
	}

	/**
	 * Method 'DetalleEdcPk'
	 * 
	 * @param idDetalleEdc
	 */
	public DetalleEdcPk(final int idDetalleEdc)
	{
		this.idDetalleEdc = idDetalleEdc;
	}

	/** 
	 * Sets the value of idDetalleEdcNull
	 */
	public void setIdDetalleEdcNull(boolean idDetalleEdcNull)
	{
		this.idDetalleEdcNull = idDetalleEdcNull;
	}

	/** 
	 * Gets the value of idDetalleEdcNull
	 */
	public boolean isIdDetalleEdcNull()
	{
		return idDetalleEdcNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof DetalleEdcPk)) {
			return false;
		}
		
		final DetalleEdcPk _cast = (DetalleEdcPk) _other;
		if (idDetalleEdc != _cast.idDetalleEdc) {
			return false;
		}
		
		if (idDetalleEdcNull != _cast.idDetalleEdcNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idDetalleEdc;
		_hashCode = 29 * _hashCode + (idDetalleEdcNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.tsp.sct.dao.dto.DetalleEdcPk: " );
		ret.append( "idDetalleEdc=" + idDetalleEdc );
		return ret.toString();
	}

}
