/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.tsp.sct.dao.dto;

import com.tsp.sct.dao.dao.*;
import com.tsp.sct.dao.factory.*;
import com.tsp.sct.dao.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class Empresa implements Serializable
{
	/** 
	 * This attribute maps to the column ID_EMPRESA in the empresa table.
	 */
	protected int idEmpresa;

	/** 
	 * This attribute represents whether the attribute idEmpresa has been modified since being read from the database.
	 */
	protected boolean idEmpresaModified = false;

	/** 
	 * This attribute maps to the column ID_EMPRESA_PADRE in the empresa table.
	 */
	protected int idEmpresaPadre;

	/** 
	 * This attribute represents whether the primitive attribute idEmpresaPadre is null.
	 */
	protected boolean idEmpresaPadreNull = true;

	/** 
	 * This attribute represents whether the attribute idEmpresaPadre has been modified since being read from the database.
	 */
	protected boolean idEmpresaPadreModified = false;

	/** 
	 * This attribute maps to the column ID_UBICACION_FISCAL in the empresa table.
	 */
	protected int idUbicacionFiscal;

	/** 
	 * This attribute represents whether the attribute idUbicacionFiscal has been modified since being read from the database.
	 */
	protected boolean idUbicacionFiscalModified = false;

	/** 
	 * This attribute maps to the column ID_TIPO_EMPRESA in the empresa table.
	 */
	protected int idTipoEmpresa;

	/** 
	 * This attribute represents whether the attribute idTipoEmpresa has been modified since being read from the database.
	 */
	protected boolean idTipoEmpresaModified = false;

	/** 
	 * This attribute maps to the column RFC in the empresa table.
	 */
	protected String rfc;

	/** 
	 * This attribute represents whether the attribute rfc has been modified since being read from the database.
	 */
	protected boolean rfcModified = false;

	/** 
	 * This attribute maps to the column RAZON_SOCIAL in the empresa table.
	 */
	protected String razonSocial;

	/** 
	 * This attribute represents whether the attribute razonSocial has been modified since being read from the database.
	 */
	protected boolean razonSocialModified = false;

	/** 
	 * This attribute maps to the column NOMBRE_COMERCIAL in the empresa table.
	 */
	protected String nombreComercial;

	/** 
	 * This attribute represents whether the attribute nombreComercial has been modified since being read from the database.
	 */
	protected boolean nombreComercialModified = false;

	/** 
	 * This attribute maps to the column FOLIOS_DISPONIBLES in the empresa table.
	 */
	protected int foliosDisponibles;

	/** 
	 * This attribute represents whether the primitive attribute foliosDisponibles is null.
	 */
	protected boolean foliosDisponiblesNull = true;

	/** 
	 * This attribute represents whether the attribute foliosDisponibles has been modified since being read from the database.
	 */
	protected boolean foliosDisponiblesModified = false;

	/** 
	 * This attribute maps to the column REGIMEN_FISCAL in the empresa table.
	 */
	protected String regimenFiscal;

	/** 
	 * This attribute represents whether the attribute regimenFiscal has been modified since being read from the database.
	 */
	protected boolean regimenFiscalModified = false;

	/** 
	 * This attribute maps to the column ID_ESTATUS in the empresa table.
	 */
	protected int idEstatus;

	/** 
	 * This attribute represents whether the attribute idEstatus has been modified since being read from the database.
	 */
	protected boolean idEstatusModified = false;

	/** 
	 * This attribute maps to the column TIPO_PDF in the empresa table.
	 */
	protected int tipoPdf;

	/** 
	 * This attribute represents whether the primitive attribute tipoPdf is null.
	 */
	protected boolean tipoPdfNull = true;

	/** 
	 * This attribute represents whether the attribute tipoPdf has been modified since being read from the database.
	 */
	protected boolean tipoPdfModified = false;

	/** 
	 * This attribute maps to the column TIPO_PDF_HONORARIOS in the empresa table.
	 */
	protected int tipoPdfHonorarios;

	/** 
	 * This attribute represents whether the primitive attribute tipoPdfHonorarios is null.
	 */
	protected boolean tipoPdfHonorariosNull = true;

	/** 
	 * This attribute represents whether the attribute tipoPdfHonorarios has been modified since being read from the database.
	 */
	protected boolean tipoPdfHonorariosModified = false;

	/** 
	 * This attribute maps to the column TIPO_PDF_ARRENDAMIENTO in the empresa table.
	 */
	protected int tipoPdfArrendamiento;

	/** 
	 * This attribute represents whether the primitive attribute tipoPdfArrendamiento is null.
	 */
	protected boolean tipoPdfArrendamientoNull = true;

	/** 
	 * This attribute represents whether the attribute tipoPdfArrendamiento has been modified since being read from the database.
	 */
	protected boolean tipoPdfArrendamientoModified = false;

	/** 
	 * This attribute maps to the column ID_VENDEDOR in the empresa table.
	 */
	protected int idVendedor;

	/** 
	 * This attribute represents whether the primitive attribute idVendedor is null.
	 */
	protected boolean idVendedorNull = true;

	/** 
	 * This attribute represents whether the attribute idVendedor has been modified since being read from the database.
	 */
	protected boolean idVendedorModified = false;

	/** 
	 * This attribute maps to the column TIPO_PAGO in the empresa table.
	 */
	protected int tipoPago;

	/** 
	 * This attribute represents whether the primitive attribute tipoPago is null.
	 */
	protected boolean tipoPagoNull = true;

	/** 
	 * This attribute represents whether the attribute tipoPago has been modified since being read from the database.
	 */
	protected boolean tipoPagoModified = false;

	/** 
	 * This attribute maps to the column ID_PAGO in the empresa table.
	 */
	protected int idPago;

	/** 
	 * This attribute represents whether the primitive attribute idPago is null.
	 */
	protected boolean idPagoNull = true;

	/** 
	 * This attribute represents whether the attribute idPago has been modified since being read from the database.
	 */
	protected boolean idPagoModified = false;

	/** 
	 * This attribute maps to the column ID_PAQUETE in the empresa table.
	 */
	protected int idPaquete;

	/** 
	 * This attribute represents whether the primitive attribute idPaquete is null.
	 */
	protected boolean idPaqueteNull = true;

	/** 
	 * This attribute represents whether the attribute idPaquete has been modified since being read from the database.
	 */
	protected boolean idPaqueteModified = false;

	/** 
	 * This attribute maps to the column REFERENCIA_PAGO in the empresa table.
	 */
	protected String referenciaPago;

	/** 
	 * This attribute represents whether the attribute referenciaPago has been modified since being read from the database.
	 */
	protected boolean referenciaPagoModified = false;

	/** 
	 * This attribute maps to the column FECHA_REGISTRO in the empresa table.
	 */
	protected Date fechaRegistro;

	/** 
	 * This attribute represents whether the attribute fechaRegistro has been modified since being read from the database.
	 */
	protected boolean fechaRegistroModified = false;

	/** 
	 * This attribute maps to the column COMPARTIR_CONCEPTOS_MATRIZ in the empresa table.
	 */
	protected int compartirConceptosMatriz;

	/** 
	 * This attribute represents whether the primitive attribute compartirConceptosMatriz is null.
	 */
	protected boolean compartirConceptosMatrizNull = true;

	/** 
	 * This attribute represents whether the attribute compartirConceptosMatriz has been modified since being read from the database.
	 */
	protected boolean compartirConceptosMatrizModified = false;

	/** 
	 * This attribute maps to the column LATITUD in the empresa table.
	 */
	protected double latitud;

	/** 
	 * This attribute represents whether the primitive attribute latitud is null.
	 */
	protected boolean latitudNull = true;

	/** 
	 * This attribute represents whether the attribute latitud has been modified since being read from the database.
	 */
	protected boolean latitudModified = false;

	/** 
	 * This attribute maps to the column LONGITUD in the empresa table.
	 */
	protected double longitud;

	/** 
	 * This attribute represents whether the primitive attribute longitud is null.
	 */
	protected boolean longitudNull = true;

	/** 
	 * This attribute represents whether the attribute longitud has been modified since being read from the database.
	 */
	protected boolean longitudModified = false;

	/** 
	 * This attribute maps to the column REGISTRO_PATRONAL in the empresa table.
	 */
	protected String registroPatronal;

	/** 
	 * This attribute represents whether the attribute registroPatronal has been modified since being read from the database.
	 */
	protected boolean registroPatronalModified = false;

	/** 
	 * This attribute maps to the column CREDITO_VALIDA_XML in the empresa table.
	 */
	protected int creditoValidaXml;

	/** 
	 * This attribute represents whether the primitive attribute creditoValidaXml is null.
	 */
	protected boolean creditoValidaXmlNull = true;

	/** 
	 * This attribute represents whether the attribute creditoValidaXml has been modified since being read from the database.
	 */
	protected boolean creditoValidaXmlModified = false;

	/** 
	 * This attribute maps to the column CREDITOS_DISPONIBLES_SECTOR_PRIMARIO in the empresa table.
	 */
	protected int creditosDisponiblesSectorPrimario;

	/** 
	 * This attribute represents whether the primitive attribute creditosDisponiblesSectorPrimario is null.
	 */
	protected boolean creditosDisponiblesSectorPrimarioNull = true;

	/** 
	 * This attribute represents whether the attribute creditosDisponiblesSectorPrimario has been modified since being read from the database.
	 */
	protected boolean creditosDisponiblesSectorPrimarioModified = false;

	/** 
	 * This attribute maps to the column ADDEDAS_PERMITIDAS in the empresa table.
	 */
	protected String addedasPermitidas;

	/** 
	 * This attribute represents whether the attribute addedasPermitidas has been modified since being read from the database.
	 */
	protected boolean addedasPermitidasModified = false;

	/** 
	 * This attribute maps to the column ID_FRANQUICIATARIO in the empresa table.
	 */
	protected int idFranquiciatario;

	/** 
	 * This attribute represents whether the primitive attribute idFranquiciatario is null.
	 */
	protected boolean idFranquiciatarioNull = true;

	/** 
	 * This attribute represents whether the attribute idFranquiciatario has been modified since being read from the database.
	 */
	protected boolean idFranquiciatarioModified = false;

	/** 
	 * This attribute maps to the column MENSAJE_PERSONALIZADO_VISITA in the empresa table.
	 */
	protected String mensajePersonalizadoVisita;

	/** 
	 * This attribute represents whether the attribute mensajePersonalizadoVisita has been modified since being read from the database.
	 */
	protected boolean mensajePersonalizadoVisitaModified = false;

	/** 
	 * This attribute maps to the column PRINT_RAZON_SOCIAL in the empresa table.
	 */
	protected int printRazonSocial;

	/** 
	 * This attribute represents whether the primitive attribute printRazonSocial is null.
	 */
	protected boolean printRazonSocialNull = true;

	/** 
	 * This attribute represents whether the attribute printRazonSocial has been modified since being read from the database.
	 */
	protected boolean printRazonSocialModified = false;

	/** 
	 * This attribute maps to the column PRINT_NOMBRE_COMERCIAL in the empresa table.
	 */
	protected int printNombreComercial;

	/** 
	 * This attribute represents whether the primitive attribute printNombreComercial is null.
	 */
	protected boolean printNombreComercialNull = true;

	/** 
	 * This attribute represents whether the attribute printNombreComercial has been modified since being read from the database.
	 */
	protected boolean printNombreComercialModified = false;

	/** 
	 * This attribute maps to the column GIRO in the empresa table.
	 */
	protected String giro;

	/** 
	 * This attribute represents whether the attribute giro has been modified since being read from the database.
	 */
	protected boolean giroModified = false;

	/** 
	 * This attribute maps to the column CREDITOS_OPERACION in the empresa table.
	 */
	protected int creditosOperacion;

	/** 
	 * This attribute represents whether the primitive attribute creditosOperacion is null.
	 */
	protected boolean creditosOperacionNull = true;

	/** 
	 * This attribute represents whether the attribute creditosOperacion has been modified since being read from the database.
	 */
	protected boolean creditosOperacionModified = false;

	/** 
	 * This attribute maps to the column INTENTOS_LOGIN_NO_CREDITOS in the empresa table.
	 */
	protected int intentosLoginNoCreditos;

	/** 
	 * This attribute represents whether the primitive attribute intentosLoginNoCreditos is null.
	 */
	protected boolean intentosLoginNoCreditosNull = true;

	/** 
	 * This attribute represents whether the attribute intentosLoginNoCreditos has been modified since being read from the database.
	 */
	protected boolean intentosLoginNoCreditosModified = false;

	/** 
	 * This attribute maps to the column PRINT_TK_PRODS in the empresa table.
	 */
	protected int printTkProds;

	/** 
	 * This attribute represents whether the primitive attribute printTkProds is null.
	 */
	protected boolean printTkProdsNull = true;

	/** 
	 * This attribute represents whether the attribute printTkProds has been modified since being read from the database.
	 */
	protected boolean printTkProdsModified = false;

	/** 
	 * This attribute maps to the column TK_MOVIL_TIPO in the empresa table.
	 */
	protected int tkMovilTipo;

	/** 
	 * This attribute represents whether the primitive attribute tkMovilTipo is null.
	 */
	protected boolean tkMovilTipoNull = true;

	/** 
	 * This attribute represents whether the attribute tkMovilTipo has been modified since being read from the database.
	 */
	protected boolean tkMovilTipoModified = false;

	/** 
	 * This attribute maps to the column TK_MOVIL_POR_MARCA in the empresa table.
	 */
	protected int tkMovilPorMarca;

	/** 
	 * This attribute represents whether the primitive attribute tkMovilPorMarca is null.
	 */
	protected boolean tkMovilPorMarcaNull = true;

	/** 
	 * This attribute represents whether the attribute tkMovilPorMarca has been modified since being read from the database.
	 */
	protected boolean tkMovilPorMarcaModified = false;

	/** 
	 * This attribute maps to the column TK_MOVIL_MOSTRAR_ZONA in the empresa table.
	 */
	protected int tkMovilMostrarZona;

	/** 
	 * This attribute represents whether the primitive attribute tkMovilMostrarZona is null.
	 */
	protected boolean tkMovilMostrarZonaNull = true;

	/** 
	 * This attribute represents whether the attribute tkMovilMostrarZona has been modified since being read from the database.
	 */
	protected boolean tkMovilMostrarZonaModified = false;

	/** 
	 * This attribute maps to the column TK_MOVIL_MOSTRAR_FOLIO in the empresa table.
	 */
	protected int tkMovilMostrarFolio;

	/** 
	 * This attribute represents whether the primitive attribute tkMovilMostrarFolio is null.
	 */
	protected boolean tkMovilMostrarFolioNull = true;

	/** 
	 * This attribute represents whether the attribute tkMovilMostrarFolio has been modified since being read from the database.
	 */
	protected boolean tkMovilMostrarFolioModified = false;

	/** 
	 * This attribute maps to the column CREDITOS_SMS in the empresa table.
	 */
	protected int creditosSms;

	/** 
	 * This attribute represents whether the primitive attribute creditosSms is null.
	 */
	protected boolean creditosSmsNull = true;

	/** 
	 * This attribute represents whether the attribute creditosSms has been modified since being read from the database.
	 */
	protected boolean creditosSmsModified = false;

	/** 
	 * This attribute maps to the column ID_SMS_DISPOSITIVO_MOVIL in the empresa table.
	 */
	protected int idSmsDispositivoMovil;

	/** 
	 * This attribute represents whether the primitive attribute idSmsDispositivoMovil is null.
	 */
	protected boolean idSmsDispositivoMovilNull = true;

	/** 
	 * This attribute represents whether the attribute idSmsDispositivoMovil has been modified since being read from the database.
	 */
	protected boolean idSmsDispositivoMovilModified = false;

	/** 
	 * This attribute maps to the column CONTACTO_CELULAR in the empresa table.
	 */
	protected String contactoCelular;

	/** 
	 * This attribute represents whether the attribute contactoCelular has been modified since being read from the database.
	 */
	protected boolean contactoCelularModified = false;

	/**
	 * Method 'Empresa'
	 * 
	 */
	public Empresa()
	{
	}

	/**
	 * Method 'getIdEmpresa'
	 * 
	 * @return int
	 */
	public int getIdEmpresa()
	{
		return idEmpresa;
	}

	/**
	 * Method 'setIdEmpresa'
	 * 
	 * @param idEmpresa
	 */
	public void setIdEmpresa(int idEmpresa)
	{
		this.idEmpresa = idEmpresa;
		this.idEmpresaModified = true;
	}

	/** 
	 * Sets the value of idEmpresaModified
	 */
	public void setIdEmpresaModified(boolean idEmpresaModified)
	{
		this.idEmpresaModified = idEmpresaModified;
	}

	/** 
	 * Gets the value of idEmpresaModified
	 */
	public boolean isIdEmpresaModified()
	{
		return idEmpresaModified;
	}

	/**
	 * Method 'getIdEmpresaPadre'
	 * 
	 * @return int
	 */
	public int getIdEmpresaPadre()
	{
		return idEmpresaPadre;
	}

	/**
	 * Method 'setIdEmpresaPadre'
	 * 
	 * @param idEmpresaPadre
	 */
	public void setIdEmpresaPadre(int idEmpresaPadre)
	{
		this.idEmpresaPadre = idEmpresaPadre;
		this.idEmpresaPadreNull = false;
		this.idEmpresaPadreModified = true;
	}

	/**
	 * Method 'setIdEmpresaPadreNull'
	 * 
	 * @param value
	 */
	public void setIdEmpresaPadreNull(boolean value)
	{
		this.idEmpresaPadreNull = value;
		this.idEmpresaPadreModified = true;
	}

	/**
	 * Method 'isIdEmpresaPadreNull'
	 * 
	 * @return boolean
	 */
	public boolean isIdEmpresaPadreNull()
	{
		return idEmpresaPadreNull;
	}

	/** 
	 * Sets the value of idEmpresaPadreModified
	 */
	public void setIdEmpresaPadreModified(boolean idEmpresaPadreModified)
	{
		this.idEmpresaPadreModified = idEmpresaPadreModified;
	}

	/** 
	 * Gets the value of idEmpresaPadreModified
	 */
	public boolean isIdEmpresaPadreModified()
	{
		return idEmpresaPadreModified;
	}

	/**
	 * Method 'getIdUbicacionFiscal'
	 * 
	 * @return int
	 */
	public int getIdUbicacionFiscal()
	{
		return idUbicacionFiscal;
	}

	/**
	 * Method 'setIdUbicacionFiscal'
	 * 
	 * @param idUbicacionFiscal
	 */
	public void setIdUbicacionFiscal(int idUbicacionFiscal)
	{
		this.idUbicacionFiscal = idUbicacionFiscal;
		this.idUbicacionFiscalModified = true;
	}

	/** 
	 * Sets the value of idUbicacionFiscalModified
	 */
	public void setIdUbicacionFiscalModified(boolean idUbicacionFiscalModified)
	{
		this.idUbicacionFiscalModified = idUbicacionFiscalModified;
	}

	/** 
	 * Gets the value of idUbicacionFiscalModified
	 */
	public boolean isIdUbicacionFiscalModified()
	{
		return idUbicacionFiscalModified;
	}

	/**
	 * Method 'getIdTipoEmpresa'
	 * 
	 * @return int
	 */
	public int getIdTipoEmpresa()
	{
		return idTipoEmpresa;
	}

	/**
	 * Method 'setIdTipoEmpresa'
	 * 
	 * @param idTipoEmpresa
	 */
	public void setIdTipoEmpresa(int idTipoEmpresa)
	{
		this.idTipoEmpresa = idTipoEmpresa;
		this.idTipoEmpresaModified = true;
	}

	/** 
	 * Sets the value of idTipoEmpresaModified
	 */
	public void setIdTipoEmpresaModified(boolean idTipoEmpresaModified)
	{
		this.idTipoEmpresaModified = idTipoEmpresaModified;
	}

	/** 
	 * Gets the value of idTipoEmpresaModified
	 */
	public boolean isIdTipoEmpresaModified()
	{
		return idTipoEmpresaModified;
	}

	/**
	 * Method 'getRfc'
	 * 
	 * @return String
	 */
	public String getRfc()
	{
		return rfc;
	}

	/**
	 * Method 'setRfc'
	 * 
	 * @param rfc
	 */
	public void setRfc(String rfc)
	{
		this.rfc = rfc;
		this.rfcModified = true;
	}

	/** 
	 * Sets the value of rfcModified
	 */
	public void setRfcModified(boolean rfcModified)
	{
		this.rfcModified = rfcModified;
	}

	/** 
	 * Gets the value of rfcModified
	 */
	public boolean isRfcModified()
	{
		return rfcModified;
	}

	/**
	 * Method 'getRazonSocial'
	 * 
	 * @return String
	 */
	public String getRazonSocial()
	{
		return razonSocial;
	}

	/**
	 * Method 'setRazonSocial'
	 * 
	 * @param razonSocial
	 */
	public void setRazonSocial(String razonSocial)
	{
		this.razonSocial = razonSocial;
		this.razonSocialModified = true;
	}

	/** 
	 * Sets the value of razonSocialModified
	 */
	public void setRazonSocialModified(boolean razonSocialModified)
	{
		this.razonSocialModified = razonSocialModified;
	}

	/** 
	 * Gets the value of razonSocialModified
	 */
	public boolean isRazonSocialModified()
	{
		return razonSocialModified;
	}

	/**
	 * Method 'getNombreComercial'
	 * 
	 * @return String
	 */
	public String getNombreComercial()
	{
		return nombreComercial;
	}

	/**
	 * Method 'setNombreComercial'
	 * 
	 * @param nombreComercial
	 */
	public void setNombreComercial(String nombreComercial)
	{
		this.nombreComercial = nombreComercial;
		this.nombreComercialModified = true;
	}

	/** 
	 * Sets the value of nombreComercialModified
	 */
	public void setNombreComercialModified(boolean nombreComercialModified)
	{
		this.nombreComercialModified = nombreComercialModified;
	}

	/** 
	 * Gets the value of nombreComercialModified
	 */
	public boolean isNombreComercialModified()
	{
		return nombreComercialModified;
	}

	/**
	 * Method 'getFoliosDisponibles'
	 * 
	 * @return int
	 */
	public int getFoliosDisponibles()
	{
		return foliosDisponibles;
	}

	/**
	 * Method 'setFoliosDisponibles'
	 * 
	 * @param foliosDisponibles
	 */
	public void setFoliosDisponibles(int foliosDisponibles)
	{
		this.foliosDisponibles = foliosDisponibles;
		this.foliosDisponiblesNull = false;
		this.foliosDisponiblesModified = true;
	}

	/**
	 * Method 'setFoliosDisponiblesNull'
	 * 
	 * @param value
	 */
	public void setFoliosDisponiblesNull(boolean value)
	{
		this.foliosDisponiblesNull = value;
		this.foliosDisponiblesModified = true;
	}

	/**
	 * Method 'isFoliosDisponiblesNull'
	 * 
	 * @return boolean
	 */
	public boolean isFoliosDisponiblesNull()
	{
		return foliosDisponiblesNull;
	}

	/** 
	 * Sets the value of foliosDisponiblesModified
	 */
	public void setFoliosDisponiblesModified(boolean foliosDisponiblesModified)
	{
		this.foliosDisponiblesModified = foliosDisponiblesModified;
	}

	/** 
	 * Gets the value of foliosDisponiblesModified
	 */
	public boolean isFoliosDisponiblesModified()
	{
		return foliosDisponiblesModified;
	}

	/**
	 * Method 'getRegimenFiscal'
	 * 
	 * @return String
	 */
	public String getRegimenFiscal()
	{
		return regimenFiscal;
	}

	/**
	 * Method 'setRegimenFiscal'
	 * 
	 * @param regimenFiscal
	 */
	public void setRegimenFiscal(String regimenFiscal)
	{
		this.regimenFiscal = regimenFiscal;
		this.regimenFiscalModified = true;
	}

	/** 
	 * Sets the value of regimenFiscalModified
	 */
	public void setRegimenFiscalModified(boolean regimenFiscalModified)
	{
		this.regimenFiscalModified = regimenFiscalModified;
	}

	/** 
	 * Gets the value of regimenFiscalModified
	 */
	public boolean isRegimenFiscalModified()
	{
		return regimenFiscalModified;
	}

	/**
	 * Method 'getIdEstatus'
	 * 
	 * @return int
	 */
	public int getIdEstatus()
	{
		return idEstatus;
	}

	/**
	 * Method 'setIdEstatus'
	 * 
	 * @param idEstatus
	 */
	public void setIdEstatus(int idEstatus)
	{
		this.idEstatus = idEstatus;
		this.idEstatusModified = true;
	}

	/** 
	 * Sets the value of idEstatusModified
	 */
	public void setIdEstatusModified(boolean idEstatusModified)
	{
		this.idEstatusModified = idEstatusModified;
	}

	/** 
	 * Gets the value of idEstatusModified
	 */
	public boolean isIdEstatusModified()
	{
		return idEstatusModified;
	}

	/**
	 * Method 'getTipoPdf'
	 * 
	 * @return int
	 */
	public int getTipoPdf()
	{
		return tipoPdf;
	}

	/**
	 * Method 'setTipoPdf'
	 * 
	 * @param tipoPdf
	 */
	public void setTipoPdf(int tipoPdf)
	{
		this.tipoPdf = tipoPdf;
		this.tipoPdfNull = false;
		this.tipoPdfModified = true;
	}

	/**
	 * Method 'setTipoPdfNull'
	 * 
	 * @param value
	 */
	public void setTipoPdfNull(boolean value)
	{
		this.tipoPdfNull = value;
		this.tipoPdfModified = true;
	}

	/**
	 * Method 'isTipoPdfNull'
	 * 
	 * @return boolean
	 */
	public boolean isTipoPdfNull()
	{
		return tipoPdfNull;
	}

	/** 
	 * Sets the value of tipoPdfModified
	 */
	public void setTipoPdfModified(boolean tipoPdfModified)
	{
		this.tipoPdfModified = tipoPdfModified;
	}

	/** 
	 * Gets the value of tipoPdfModified
	 */
	public boolean isTipoPdfModified()
	{
		return tipoPdfModified;
	}

	/**
	 * Method 'getTipoPdfHonorarios'
	 * 
	 * @return int
	 */
	public int getTipoPdfHonorarios()
	{
		return tipoPdfHonorarios;
	}

	/**
	 * Method 'setTipoPdfHonorarios'
	 * 
	 * @param tipoPdfHonorarios
	 */
	public void setTipoPdfHonorarios(int tipoPdfHonorarios)
	{
		this.tipoPdfHonorarios = tipoPdfHonorarios;
		this.tipoPdfHonorariosNull = false;
		this.tipoPdfHonorariosModified = true;
	}

	/**
	 * Method 'setTipoPdfHonorariosNull'
	 * 
	 * @param value
	 */
	public void setTipoPdfHonorariosNull(boolean value)
	{
		this.tipoPdfHonorariosNull = value;
		this.tipoPdfHonorariosModified = true;
	}

	/**
	 * Method 'isTipoPdfHonorariosNull'
	 * 
	 * @return boolean
	 */
	public boolean isTipoPdfHonorariosNull()
	{
		return tipoPdfHonorariosNull;
	}

	/** 
	 * Sets the value of tipoPdfHonorariosModified
	 */
	public void setTipoPdfHonorariosModified(boolean tipoPdfHonorariosModified)
	{
		this.tipoPdfHonorariosModified = tipoPdfHonorariosModified;
	}

	/** 
	 * Gets the value of tipoPdfHonorariosModified
	 */
	public boolean isTipoPdfHonorariosModified()
	{
		return tipoPdfHonorariosModified;
	}

	/**
	 * Method 'getTipoPdfArrendamiento'
	 * 
	 * @return int
	 */
	public int getTipoPdfArrendamiento()
	{
		return tipoPdfArrendamiento;
	}

	/**
	 * Method 'setTipoPdfArrendamiento'
	 * 
	 * @param tipoPdfArrendamiento
	 */
	public void setTipoPdfArrendamiento(int tipoPdfArrendamiento)
	{
		this.tipoPdfArrendamiento = tipoPdfArrendamiento;
		this.tipoPdfArrendamientoNull = false;
		this.tipoPdfArrendamientoModified = true;
	}

	/**
	 * Method 'setTipoPdfArrendamientoNull'
	 * 
	 * @param value
	 */
	public void setTipoPdfArrendamientoNull(boolean value)
	{
		this.tipoPdfArrendamientoNull = value;
		this.tipoPdfArrendamientoModified = true;
	}

	/**
	 * Method 'isTipoPdfArrendamientoNull'
	 * 
	 * @return boolean
	 */
	public boolean isTipoPdfArrendamientoNull()
	{
		return tipoPdfArrendamientoNull;
	}

	/** 
	 * Sets the value of tipoPdfArrendamientoModified
	 */
	public void setTipoPdfArrendamientoModified(boolean tipoPdfArrendamientoModified)
	{
		this.tipoPdfArrendamientoModified = tipoPdfArrendamientoModified;
	}

	/** 
	 * Gets the value of tipoPdfArrendamientoModified
	 */
	public boolean isTipoPdfArrendamientoModified()
	{
		return tipoPdfArrendamientoModified;
	}

	/**
	 * Method 'getIdVendedor'
	 * 
	 * @return int
	 */
	public int getIdVendedor()
	{
		return idVendedor;
	}

	/**
	 * Method 'setIdVendedor'
	 * 
	 * @param idVendedor
	 */
	public void setIdVendedor(int idVendedor)
	{
		this.idVendedor = idVendedor;
		this.idVendedorNull = false;
		this.idVendedorModified = true;
	}

	/**
	 * Method 'setIdVendedorNull'
	 * 
	 * @param value
	 */
	public void setIdVendedorNull(boolean value)
	{
		this.idVendedorNull = value;
		this.idVendedorModified = true;
	}

	/**
	 * Method 'isIdVendedorNull'
	 * 
	 * @return boolean
	 */
	public boolean isIdVendedorNull()
	{
		return idVendedorNull;
	}

	/** 
	 * Sets the value of idVendedorModified
	 */
	public void setIdVendedorModified(boolean idVendedorModified)
	{
		this.idVendedorModified = idVendedorModified;
	}

	/** 
	 * Gets the value of idVendedorModified
	 */
	public boolean isIdVendedorModified()
	{
		return idVendedorModified;
	}

	/**
	 * Method 'getTipoPago'
	 * 
	 * @return int
	 */
	public int getTipoPago()
	{
		return tipoPago;
	}

	/**
	 * Method 'setTipoPago'
	 * 
	 * @param tipoPago
	 */
	public void setTipoPago(int tipoPago)
	{
		this.tipoPago = tipoPago;
		this.tipoPagoNull = false;
		this.tipoPagoModified = true;
	}

	/**
	 * Method 'setTipoPagoNull'
	 * 
	 * @param value
	 */
	public void setTipoPagoNull(boolean value)
	{
		this.tipoPagoNull = value;
		this.tipoPagoModified = true;
	}

	/**
	 * Method 'isTipoPagoNull'
	 * 
	 * @return boolean
	 */
	public boolean isTipoPagoNull()
	{
		return tipoPagoNull;
	}

	/** 
	 * Sets the value of tipoPagoModified
	 */
	public void setTipoPagoModified(boolean tipoPagoModified)
	{
		this.tipoPagoModified = tipoPagoModified;
	}

	/** 
	 * Gets the value of tipoPagoModified
	 */
	public boolean isTipoPagoModified()
	{
		return tipoPagoModified;
	}

	/**
	 * Method 'getIdPago'
	 * 
	 * @return int
	 */
	public int getIdPago()
	{
		return idPago;
	}

	/**
	 * Method 'setIdPago'
	 * 
	 * @param idPago
	 */
	public void setIdPago(int idPago)
	{
		this.idPago = idPago;
		this.idPagoNull = false;
		this.idPagoModified = true;
	}

	/**
	 * Method 'setIdPagoNull'
	 * 
	 * @param value
	 */
	public void setIdPagoNull(boolean value)
	{
		this.idPagoNull = value;
		this.idPagoModified = true;
	}

	/**
	 * Method 'isIdPagoNull'
	 * 
	 * @return boolean
	 */
	public boolean isIdPagoNull()
	{
		return idPagoNull;
	}

	/** 
	 * Sets the value of idPagoModified
	 */
	public void setIdPagoModified(boolean idPagoModified)
	{
		this.idPagoModified = idPagoModified;
	}

	/** 
	 * Gets the value of idPagoModified
	 */
	public boolean isIdPagoModified()
	{
		return idPagoModified;
	}

	/**
	 * Method 'getIdPaquete'
	 * 
	 * @return int
	 */
	public int getIdPaquete()
	{
		return idPaquete;
	}

	/**
	 * Method 'setIdPaquete'
	 * 
	 * @param idPaquete
	 */
	public void setIdPaquete(int idPaquete)
	{
		this.idPaquete = idPaquete;
		this.idPaqueteNull = false;
		this.idPaqueteModified = true;
	}

	/**
	 * Method 'setIdPaqueteNull'
	 * 
	 * @param value
	 */
	public void setIdPaqueteNull(boolean value)
	{
		this.idPaqueteNull = value;
		this.idPaqueteModified = true;
	}

	/**
	 * Method 'isIdPaqueteNull'
	 * 
	 * @return boolean
	 */
	public boolean isIdPaqueteNull()
	{
		return idPaqueteNull;
	}

	/** 
	 * Sets the value of idPaqueteModified
	 */
	public void setIdPaqueteModified(boolean idPaqueteModified)
	{
		this.idPaqueteModified = idPaqueteModified;
	}

	/** 
	 * Gets the value of idPaqueteModified
	 */
	public boolean isIdPaqueteModified()
	{
		return idPaqueteModified;
	}

	/**
	 * Method 'getReferenciaPago'
	 * 
	 * @return String
	 */
	public String getReferenciaPago()
	{
		return referenciaPago;
	}

	/**
	 * Method 'setReferenciaPago'
	 * 
	 * @param referenciaPago
	 */
	public void setReferenciaPago(String referenciaPago)
	{
		this.referenciaPago = referenciaPago;
		this.referenciaPagoModified = true;
	}

	/** 
	 * Sets the value of referenciaPagoModified
	 */
	public void setReferenciaPagoModified(boolean referenciaPagoModified)
	{
		this.referenciaPagoModified = referenciaPagoModified;
	}

	/** 
	 * Gets the value of referenciaPagoModified
	 */
	public boolean isReferenciaPagoModified()
	{
		return referenciaPagoModified;
	}

	/**
	 * Method 'getFechaRegistro'
	 * 
	 * @return Date
	 */
	public Date getFechaRegistro()
	{
		return fechaRegistro;
	}

	/**
	 * Method 'setFechaRegistro'
	 * 
	 * @param fechaRegistro
	 */
	public void setFechaRegistro(Date fechaRegistro)
	{
		this.fechaRegistro = fechaRegistro;
		this.fechaRegistroModified = true;
	}

	/** 
	 * Sets the value of fechaRegistroModified
	 */
	public void setFechaRegistroModified(boolean fechaRegistroModified)
	{
		this.fechaRegistroModified = fechaRegistroModified;
	}

	/** 
	 * Gets the value of fechaRegistroModified
	 */
	public boolean isFechaRegistroModified()
	{
		return fechaRegistroModified;
	}

	/**
	 * Method 'getCompartirConceptosMatriz'
	 * 
	 * @return int
	 */
	public int getCompartirConceptosMatriz()
	{
		return compartirConceptosMatriz;
	}

	/**
	 * Method 'setCompartirConceptosMatriz'
	 * 
	 * @param compartirConceptosMatriz
	 */
	public void setCompartirConceptosMatriz(int compartirConceptosMatriz)
	{
		this.compartirConceptosMatriz = compartirConceptosMatriz;
		this.compartirConceptosMatrizNull = false;
		this.compartirConceptosMatrizModified = true;
	}

	/**
	 * Method 'setCompartirConceptosMatrizNull'
	 * 
	 * @param value
	 */
	public void setCompartirConceptosMatrizNull(boolean value)
	{
		this.compartirConceptosMatrizNull = value;
		this.compartirConceptosMatrizModified = true;
	}

	/**
	 * Method 'isCompartirConceptosMatrizNull'
	 * 
	 * @return boolean
	 */
	public boolean isCompartirConceptosMatrizNull()
	{
		return compartirConceptosMatrizNull;
	}

	/** 
	 * Sets the value of compartirConceptosMatrizModified
	 */
	public void setCompartirConceptosMatrizModified(boolean compartirConceptosMatrizModified)
	{
		this.compartirConceptosMatrizModified = compartirConceptosMatrizModified;
	}

	/** 
	 * Gets the value of compartirConceptosMatrizModified
	 */
	public boolean isCompartirConceptosMatrizModified()
	{
		return compartirConceptosMatrizModified;
	}

	/**
	 * Method 'getLatitud'
	 * 
	 * @return double
	 */
	public double getLatitud()
	{
		return latitud;
	}

	/**
	 * Method 'setLatitud'
	 * 
	 * @param latitud
	 */
	public void setLatitud(double latitud)
	{
		this.latitud = latitud;
		this.latitudNull = false;
		this.latitudModified = true;
	}

	/**
	 * Method 'setLatitudNull'
	 * 
	 * @param value
	 */
	public void setLatitudNull(boolean value)
	{
		this.latitudNull = value;
		this.latitudModified = true;
	}

	/**
	 * Method 'isLatitudNull'
	 * 
	 * @return boolean
	 */
	public boolean isLatitudNull()
	{
		return latitudNull;
	}

	/** 
	 * Sets the value of latitudModified
	 */
	public void setLatitudModified(boolean latitudModified)
	{
		this.latitudModified = latitudModified;
	}

	/** 
	 * Gets the value of latitudModified
	 */
	public boolean isLatitudModified()
	{
		return latitudModified;
	}

	/**
	 * Method 'getLongitud'
	 * 
	 * @return double
	 */
	public double getLongitud()
	{
		return longitud;
	}

	/**
	 * Method 'setLongitud'
	 * 
	 * @param longitud
	 */
	public void setLongitud(double longitud)
	{
		this.longitud = longitud;
		this.longitudNull = false;
		this.longitudModified = true;
	}

	/**
	 * Method 'setLongitudNull'
	 * 
	 * @param value
	 */
	public void setLongitudNull(boolean value)
	{
		this.longitudNull = value;
		this.longitudModified = true;
	}

	/**
	 * Method 'isLongitudNull'
	 * 
	 * @return boolean
	 */
	public boolean isLongitudNull()
	{
		return longitudNull;
	}

	/** 
	 * Sets the value of longitudModified
	 */
	public void setLongitudModified(boolean longitudModified)
	{
		this.longitudModified = longitudModified;
	}

	/** 
	 * Gets the value of longitudModified
	 */
	public boolean isLongitudModified()
	{
		return longitudModified;
	}

	/**
	 * Method 'getRegistroPatronal'
	 * 
	 * @return String
	 */
	public String getRegistroPatronal()
	{
		return registroPatronal;
	}

	/**
	 * Method 'setRegistroPatronal'
	 * 
	 * @param registroPatronal
	 */
	public void setRegistroPatronal(String registroPatronal)
	{
		this.registroPatronal = registroPatronal;
		this.registroPatronalModified = true;
	}

	/** 
	 * Sets the value of registroPatronalModified
	 */
	public void setRegistroPatronalModified(boolean registroPatronalModified)
	{
		this.registroPatronalModified = registroPatronalModified;
	}

	/** 
	 * Gets the value of registroPatronalModified
	 */
	public boolean isRegistroPatronalModified()
	{
		return registroPatronalModified;
	}

	/**
	 * Method 'getCreditoValidaXml'
	 * 
	 * @return int
	 */
	public int getCreditoValidaXml()
	{
		return creditoValidaXml;
	}

	/**
	 * Method 'setCreditoValidaXml'
	 * 
	 * @param creditoValidaXml
	 */
	public void setCreditoValidaXml(int creditoValidaXml)
	{
		this.creditoValidaXml = creditoValidaXml;
		this.creditoValidaXmlNull = false;
		this.creditoValidaXmlModified = true;
	}

	/**
	 * Method 'setCreditoValidaXmlNull'
	 * 
	 * @param value
	 */
	public void setCreditoValidaXmlNull(boolean value)
	{
		this.creditoValidaXmlNull = value;
		this.creditoValidaXmlModified = true;
	}

	/**
	 * Method 'isCreditoValidaXmlNull'
	 * 
	 * @return boolean
	 */
	public boolean isCreditoValidaXmlNull()
	{
		return creditoValidaXmlNull;
	}

	/** 
	 * Sets the value of creditoValidaXmlModified
	 */
	public void setCreditoValidaXmlModified(boolean creditoValidaXmlModified)
	{
		this.creditoValidaXmlModified = creditoValidaXmlModified;
	}

	/** 
	 * Gets the value of creditoValidaXmlModified
	 */
	public boolean isCreditoValidaXmlModified()
	{
		return creditoValidaXmlModified;
	}

	/**
	 * Method 'getCreditosDisponiblesSectorPrimario'
	 * 
	 * @return int
	 */
	public int getCreditosDisponiblesSectorPrimario()
	{
		return creditosDisponiblesSectorPrimario;
	}

	/**
	 * Method 'setCreditosDisponiblesSectorPrimario'
	 * 
	 * @param creditosDisponiblesSectorPrimario
	 */
	public void setCreditosDisponiblesSectorPrimario(int creditosDisponiblesSectorPrimario)
	{
		this.creditosDisponiblesSectorPrimario = creditosDisponiblesSectorPrimario;
		this.creditosDisponiblesSectorPrimarioNull = false;
		this.creditosDisponiblesSectorPrimarioModified = true;
	}

	/**
	 * Method 'setCreditosDisponiblesSectorPrimarioNull'
	 * 
	 * @param value
	 */
	public void setCreditosDisponiblesSectorPrimarioNull(boolean value)
	{
		this.creditosDisponiblesSectorPrimarioNull = value;
		this.creditosDisponiblesSectorPrimarioModified = true;
	}

	/**
	 * Method 'isCreditosDisponiblesSectorPrimarioNull'
	 * 
	 * @return boolean
	 */
	public boolean isCreditosDisponiblesSectorPrimarioNull()
	{
		return creditosDisponiblesSectorPrimarioNull;
	}

	/** 
	 * Sets the value of creditosDisponiblesSectorPrimarioModified
	 */
	public void setCreditosDisponiblesSectorPrimarioModified(boolean creditosDisponiblesSectorPrimarioModified)
	{
		this.creditosDisponiblesSectorPrimarioModified = creditosDisponiblesSectorPrimarioModified;
	}

	/** 
	 * Gets the value of creditosDisponiblesSectorPrimarioModified
	 */
	public boolean isCreditosDisponiblesSectorPrimarioModified()
	{
		return creditosDisponiblesSectorPrimarioModified;
	}

	/**
	 * Method 'getAddedasPermitidas'
	 * 
	 * @return String
	 */
	public String getAddedasPermitidas()
	{
		return addedasPermitidas;
	}

	/**
	 * Method 'setAddedasPermitidas'
	 * 
	 * @param addedasPermitidas
	 */
	public void setAddedasPermitidas(String addedasPermitidas)
	{
		this.addedasPermitidas = addedasPermitidas;
		this.addedasPermitidasModified = true;
	}

	/** 
	 * Sets the value of addedasPermitidasModified
	 */
	public void setAddedasPermitidasModified(boolean addedasPermitidasModified)
	{
		this.addedasPermitidasModified = addedasPermitidasModified;
	}

	/** 
	 * Gets the value of addedasPermitidasModified
	 */
	public boolean isAddedasPermitidasModified()
	{
		return addedasPermitidasModified;
	}

	/**
	 * Method 'getIdFranquiciatario'
	 * 
	 * @return int
	 */
	public int getIdFranquiciatario()
	{
		return idFranquiciatario;
	}

	/**
	 * Method 'setIdFranquiciatario'
	 * 
	 * @param idFranquiciatario
	 */
	public void setIdFranquiciatario(int idFranquiciatario)
	{
		this.idFranquiciatario = idFranquiciatario;
		this.idFranquiciatarioNull = false;
		this.idFranquiciatarioModified = true;
	}

	/**
	 * Method 'setIdFranquiciatarioNull'
	 * 
	 * @param value
	 */
	public void setIdFranquiciatarioNull(boolean value)
	{
		this.idFranquiciatarioNull = value;
		this.idFranquiciatarioModified = true;
	}

	/**
	 * Method 'isIdFranquiciatarioNull'
	 * 
	 * @return boolean
	 */
	public boolean isIdFranquiciatarioNull()
	{
		return idFranquiciatarioNull;
	}

	/** 
	 * Sets the value of idFranquiciatarioModified
	 */
	public void setIdFranquiciatarioModified(boolean idFranquiciatarioModified)
	{
		this.idFranquiciatarioModified = idFranquiciatarioModified;
	}

	/** 
	 * Gets the value of idFranquiciatarioModified
	 */
	public boolean isIdFranquiciatarioModified()
	{
		return idFranquiciatarioModified;
	}

	/**
	 * Method 'getMensajePersonalizadoVisita'
	 * 
	 * @return String
	 */
	public String getMensajePersonalizadoVisita()
	{
		return mensajePersonalizadoVisita;
	}

	/**
	 * Method 'setMensajePersonalizadoVisita'
	 * 
	 * @param mensajePersonalizadoVisita
	 */
	public void setMensajePersonalizadoVisita(String mensajePersonalizadoVisita)
	{
		this.mensajePersonalizadoVisita = mensajePersonalizadoVisita;
		this.mensajePersonalizadoVisitaModified = true;
	}

	/** 
	 * Sets the value of mensajePersonalizadoVisitaModified
	 */
	public void setMensajePersonalizadoVisitaModified(boolean mensajePersonalizadoVisitaModified)
	{
		this.mensajePersonalizadoVisitaModified = mensajePersonalizadoVisitaModified;
	}

	/** 
	 * Gets the value of mensajePersonalizadoVisitaModified
	 */
	public boolean isMensajePersonalizadoVisitaModified()
	{
		return mensajePersonalizadoVisitaModified;
	}

	/**
	 * Method 'getPrintRazonSocial'
	 * 
	 * @return int
	 */
	public int getPrintRazonSocial()
	{
		return printRazonSocial;
	}

	/**
	 * Method 'setPrintRazonSocial'
	 * 
	 * @param printRazonSocial
	 */
	public void setPrintRazonSocial(int printRazonSocial)
	{
		this.printRazonSocial = printRazonSocial;
		this.printRazonSocialNull = false;
		this.printRazonSocialModified = true;
	}

	/**
	 * Method 'setPrintRazonSocialNull'
	 * 
	 * @param value
	 */
	public void setPrintRazonSocialNull(boolean value)
	{
		this.printRazonSocialNull = value;
		this.printRazonSocialModified = true;
	}

	/**
	 * Method 'isPrintRazonSocialNull'
	 * 
	 * @return boolean
	 */
	public boolean isPrintRazonSocialNull()
	{
		return printRazonSocialNull;
	}

	/** 
	 * Sets the value of printRazonSocialModified
	 */
	public void setPrintRazonSocialModified(boolean printRazonSocialModified)
	{
		this.printRazonSocialModified = printRazonSocialModified;
	}

	/** 
	 * Gets the value of printRazonSocialModified
	 */
	public boolean isPrintRazonSocialModified()
	{
		return printRazonSocialModified;
	}

	/**
	 * Method 'getPrintNombreComercial'
	 * 
	 * @return int
	 */
	public int getPrintNombreComercial()
	{
		return printNombreComercial;
	}

	/**
	 * Method 'setPrintNombreComercial'
	 * 
	 * @param printNombreComercial
	 */
	public void setPrintNombreComercial(int printNombreComercial)
	{
		this.printNombreComercial = printNombreComercial;
		this.printNombreComercialNull = false;
		this.printNombreComercialModified = true;
	}

	/**
	 * Method 'setPrintNombreComercialNull'
	 * 
	 * @param value
	 */
	public void setPrintNombreComercialNull(boolean value)
	{
		this.printNombreComercialNull = value;
		this.printNombreComercialModified = true;
	}

	/**
	 * Method 'isPrintNombreComercialNull'
	 * 
	 * @return boolean
	 */
	public boolean isPrintNombreComercialNull()
	{
		return printNombreComercialNull;
	}

	/** 
	 * Sets the value of printNombreComercialModified
	 */
	public void setPrintNombreComercialModified(boolean printNombreComercialModified)
	{
		this.printNombreComercialModified = printNombreComercialModified;
	}

	/** 
	 * Gets the value of printNombreComercialModified
	 */
	public boolean isPrintNombreComercialModified()
	{
		return printNombreComercialModified;
	}

	/**
	 * Method 'getGiro'
	 * 
	 * @return String
	 */
	public String getGiro()
	{
		return giro;
	}

	/**
	 * Method 'setGiro'
	 * 
	 * @param giro
	 */
	public void setGiro(String giro)
	{
		this.giro = giro;
		this.giroModified = true;
	}

	/** 
	 * Sets the value of giroModified
	 */
	public void setGiroModified(boolean giroModified)
	{
		this.giroModified = giroModified;
	}

	/** 
	 * Gets the value of giroModified
	 */
	public boolean isGiroModified()
	{
		return giroModified;
	}

	/**
	 * Method 'getCreditosOperacion'
	 * 
	 * @return int
	 */
	public int getCreditosOperacion()
	{
		return creditosOperacion;
	}

	/**
	 * Method 'setCreditosOperacion'
	 * 
	 * @param creditosOperacion
	 */
	public void setCreditosOperacion(int creditosOperacion)
	{
		this.creditosOperacion = creditosOperacion;
		this.creditosOperacionNull = false;
		this.creditosOperacionModified = true;
	}

	/**
	 * Method 'setCreditosOperacionNull'
	 * 
	 * @param value
	 */
	public void setCreditosOperacionNull(boolean value)
	{
		this.creditosOperacionNull = value;
		this.creditosOperacionModified = true;
	}

	/**
	 * Method 'isCreditosOperacionNull'
	 * 
	 * @return boolean
	 */
	public boolean isCreditosOperacionNull()
	{
		return creditosOperacionNull;
	}

	/** 
	 * Sets the value of creditosOperacionModified
	 */
	public void setCreditosOperacionModified(boolean creditosOperacionModified)
	{
		this.creditosOperacionModified = creditosOperacionModified;
	}

	/** 
	 * Gets the value of creditosOperacionModified
	 */
	public boolean isCreditosOperacionModified()
	{
		return creditosOperacionModified;
	}

	/**
	 * Method 'getIntentosLoginNoCreditos'
	 * 
	 * @return int
	 */
	public int getIntentosLoginNoCreditos()
	{
		return intentosLoginNoCreditos;
	}

	/**
	 * Method 'setIntentosLoginNoCreditos'
	 * 
	 * @param intentosLoginNoCreditos
	 */
	public void setIntentosLoginNoCreditos(int intentosLoginNoCreditos)
	{
		this.intentosLoginNoCreditos = intentosLoginNoCreditos;
		this.intentosLoginNoCreditosNull = false;
		this.intentosLoginNoCreditosModified = true;
	}

	/**
	 * Method 'setIntentosLoginNoCreditosNull'
	 * 
	 * @param value
	 */
	public void setIntentosLoginNoCreditosNull(boolean value)
	{
		this.intentosLoginNoCreditosNull = value;
		this.intentosLoginNoCreditosModified = true;
	}

	/**
	 * Method 'isIntentosLoginNoCreditosNull'
	 * 
	 * @return boolean
	 */
	public boolean isIntentosLoginNoCreditosNull()
	{
		return intentosLoginNoCreditosNull;
	}

	/** 
	 * Sets the value of intentosLoginNoCreditosModified
	 */
	public void setIntentosLoginNoCreditosModified(boolean intentosLoginNoCreditosModified)
	{
		this.intentosLoginNoCreditosModified = intentosLoginNoCreditosModified;
	}

	/** 
	 * Gets the value of intentosLoginNoCreditosModified
	 */
	public boolean isIntentosLoginNoCreditosModified()
	{
		return intentosLoginNoCreditosModified;
	}

	/**
	 * Method 'getPrintTkProds'
	 * 
	 * @return int
	 */
	public int getPrintTkProds()
	{
		return printTkProds;
	}

	/**
	 * Method 'setPrintTkProds'
	 * 
	 * @param printTkProds
	 */
	public void setPrintTkProds(int printTkProds)
	{
		this.printTkProds = printTkProds;
		this.printTkProdsNull = false;
		this.printTkProdsModified = true;
	}

	/**
	 * Method 'setPrintTkProdsNull'
	 * 
	 * @param value
	 */
	public void setPrintTkProdsNull(boolean value)
	{
		this.printTkProdsNull = value;
		this.printTkProdsModified = true;
	}

	/**
	 * Method 'isPrintTkProdsNull'
	 * 
	 * @return boolean
	 */
	public boolean isPrintTkProdsNull()
	{
		return printTkProdsNull;
	}

	/** 
	 * Sets the value of printTkProdsModified
	 */
	public void setPrintTkProdsModified(boolean printTkProdsModified)
	{
		this.printTkProdsModified = printTkProdsModified;
	}

	/** 
	 * Gets the value of printTkProdsModified
	 */
	public boolean isPrintTkProdsModified()
	{
		return printTkProdsModified;
	}

	/**
	 * Method 'getTkMovilTipo'
	 * 
	 * @return int
	 */
	public int getTkMovilTipo()
	{
		return tkMovilTipo;
	}

	/**
	 * Method 'setTkMovilTipo'
	 * 
	 * @param tkMovilTipo
	 */
	public void setTkMovilTipo(int tkMovilTipo)
	{
		this.tkMovilTipo = tkMovilTipo;
		this.tkMovilTipoNull = false;
		this.tkMovilTipoModified = true;
	}

	/**
	 * Method 'setTkMovilTipoNull'
	 * 
	 * @param value
	 */
	public void setTkMovilTipoNull(boolean value)
	{
		this.tkMovilTipoNull = value;
		this.tkMovilTipoModified = true;
	}

	/**
	 * Method 'isTkMovilTipoNull'
	 * 
	 * @return boolean
	 */
	public boolean isTkMovilTipoNull()
	{
		return tkMovilTipoNull;
	}

	/** 
	 * Sets the value of tkMovilTipoModified
	 */
	public void setTkMovilTipoModified(boolean tkMovilTipoModified)
	{
		this.tkMovilTipoModified = tkMovilTipoModified;
	}

	/** 
	 * Gets the value of tkMovilTipoModified
	 */
	public boolean isTkMovilTipoModified()
	{
		return tkMovilTipoModified;
	}

	/**
	 * Method 'getTkMovilPorMarca'
	 * 
	 * @return int
	 */
	public int getTkMovilPorMarca()
	{
		return tkMovilPorMarca;
	}

	/**
	 * Method 'setTkMovilPorMarca'
	 * 
	 * @param tkMovilPorMarca
	 */
	public void setTkMovilPorMarca(int tkMovilPorMarca)
	{
		this.tkMovilPorMarca = tkMovilPorMarca;
		this.tkMovilPorMarcaNull = false;
		this.tkMovilPorMarcaModified = true;
	}

	/**
	 * Method 'setTkMovilPorMarcaNull'
	 * 
	 * @param value
	 */
	public void setTkMovilPorMarcaNull(boolean value)
	{
		this.tkMovilPorMarcaNull = value;
		this.tkMovilPorMarcaModified = true;
	}

	/**
	 * Method 'isTkMovilPorMarcaNull'
	 * 
	 * @return boolean
	 */
	public boolean isTkMovilPorMarcaNull()
	{
		return tkMovilPorMarcaNull;
	}

	/** 
	 * Sets the value of tkMovilPorMarcaModified
	 */
	public void setTkMovilPorMarcaModified(boolean tkMovilPorMarcaModified)
	{
		this.tkMovilPorMarcaModified = tkMovilPorMarcaModified;
	}

	/** 
	 * Gets the value of tkMovilPorMarcaModified
	 */
	public boolean isTkMovilPorMarcaModified()
	{
		return tkMovilPorMarcaModified;
	}

	/**
	 * Method 'getTkMovilMostrarZona'
	 * 
	 * @return int
	 */
	public int getTkMovilMostrarZona()
	{
		return tkMovilMostrarZona;
	}

	/**
	 * Method 'setTkMovilMostrarZona'
	 * 
	 * @param tkMovilMostrarZona
	 */
	public void setTkMovilMostrarZona(int tkMovilMostrarZona)
	{
		this.tkMovilMostrarZona = tkMovilMostrarZona;
		this.tkMovilMostrarZonaNull = false;
		this.tkMovilMostrarZonaModified = true;
	}

	/**
	 * Method 'setTkMovilMostrarZonaNull'
	 * 
	 * @param value
	 */
	public void setTkMovilMostrarZonaNull(boolean value)
	{
		this.tkMovilMostrarZonaNull = value;
		this.tkMovilMostrarZonaModified = true;
	}

	/**
	 * Method 'isTkMovilMostrarZonaNull'
	 * 
	 * @return boolean
	 */
	public boolean isTkMovilMostrarZonaNull()
	{
		return tkMovilMostrarZonaNull;
	}

	/** 
	 * Sets the value of tkMovilMostrarZonaModified
	 */
	public void setTkMovilMostrarZonaModified(boolean tkMovilMostrarZonaModified)
	{
		this.tkMovilMostrarZonaModified = tkMovilMostrarZonaModified;
	}

	/** 
	 * Gets the value of tkMovilMostrarZonaModified
	 */
	public boolean isTkMovilMostrarZonaModified()
	{
		return tkMovilMostrarZonaModified;
	}

	/**
	 * Method 'getTkMovilMostrarFolio'
	 * 
	 * @return int
	 */
	public int getTkMovilMostrarFolio()
	{
		return tkMovilMostrarFolio;
	}

	/**
	 * Method 'setTkMovilMostrarFolio'
	 * 
	 * @param tkMovilMostrarFolio
	 */
	public void setTkMovilMostrarFolio(int tkMovilMostrarFolio)
	{
		this.tkMovilMostrarFolio = tkMovilMostrarFolio;
		this.tkMovilMostrarFolioNull = false;
		this.tkMovilMostrarFolioModified = true;
	}

	/**
	 * Method 'setTkMovilMostrarFolioNull'
	 * 
	 * @param value
	 */
	public void setTkMovilMostrarFolioNull(boolean value)
	{
		this.tkMovilMostrarFolioNull = value;
		this.tkMovilMostrarFolioModified = true;
	}

	/**
	 * Method 'isTkMovilMostrarFolioNull'
	 * 
	 * @return boolean
	 */
	public boolean isTkMovilMostrarFolioNull()
	{
		return tkMovilMostrarFolioNull;
	}

	/** 
	 * Sets the value of tkMovilMostrarFolioModified
	 */
	public void setTkMovilMostrarFolioModified(boolean tkMovilMostrarFolioModified)
	{
		this.tkMovilMostrarFolioModified = tkMovilMostrarFolioModified;
	}

	/** 
	 * Gets the value of tkMovilMostrarFolioModified
	 */
	public boolean isTkMovilMostrarFolioModified()
	{
		return tkMovilMostrarFolioModified;
	}

	/**
	 * Method 'getCreditosSms'
	 * 
	 * @return int
	 */
	public int getCreditosSms()
	{
		return creditosSms;
	}

	/**
	 * Method 'setCreditosSms'
	 * 
	 * @param creditosSms
	 */
	public void setCreditosSms(int creditosSms)
	{
		this.creditosSms = creditosSms;
		this.creditosSmsNull = false;
		this.creditosSmsModified = true;
	}

	/**
	 * Method 'setCreditosSmsNull'
	 * 
	 * @param value
	 */
	public void setCreditosSmsNull(boolean value)
	{
		this.creditosSmsNull = value;
		this.creditosSmsModified = true;
	}

	/**
	 * Method 'isCreditosSmsNull'
	 * 
	 * @return boolean
	 */
	public boolean isCreditosSmsNull()
	{
		return creditosSmsNull;
	}

	/** 
	 * Sets the value of creditosSmsModified
	 */
	public void setCreditosSmsModified(boolean creditosSmsModified)
	{
		this.creditosSmsModified = creditosSmsModified;
	}

	/** 
	 * Gets the value of creditosSmsModified
	 */
	public boolean isCreditosSmsModified()
	{
		return creditosSmsModified;
	}

	/**
	 * Method 'getIdSmsDispositivoMovil'
	 * 
	 * @return int
	 */
	public int getIdSmsDispositivoMovil()
	{
		return idSmsDispositivoMovil;
	}

	/**
	 * Method 'setIdSmsDispositivoMovil'
	 * 
	 * @param idSmsDispositivoMovil
	 */
	public void setIdSmsDispositivoMovil(int idSmsDispositivoMovil)
	{
		this.idSmsDispositivoMovil = idSmsDispositivoMovil;
		this.idSmsDispositivoMovilNull = false;
		this.idSmsDispositivoMovilModified = true;
	}

	/**
	 * Method 'setIdSmsDispositivoMovilNull'
	 * 
	 * @param value
	 */
	public void setIdSmsDispositivoMovilNull(boolean value)
	{
		this.idSmsDispositivoMovilNull = value;
		this.idSmsDispositivoMovilModified = true;
	}

	/**
	 * Method 'isIdSmsDispositivoMovilNull'
	 * 
	 * @return boolean
	 */
	public boolean isIdSmsDispositivoMovilNull()
	{
		return idSmsDispositivoMovilNull;
	}

	/** 
	 * Sets the value of idSmsDispositivoMovilModified
	 */
	public void setIdSmsDispositivoMovilModified(boolean idSmsDispositivoMovilModified)
	{
		this.idSmsDispositivoMovilModified = idSmsDispositivoMovilModified;
	}

	/** 
	 * Gets the value of idSmsDispositivoMovilModified
	 */
	public boolean isIdSmsDispositivoMovilModified()
	{
		return idSmsDispositivoMovilModified;
	}

	/**
	 * Method 'getContactoCelular'
	 * 
	 * @return String
	 */
	public String getContactoCelular()
	{
		return contactoCelular;
	}

	/**
	 * Method 'setContactoCelular'
	 * 
	 * @param contactoCelular
	 */
	public void setContactoCelular(String contactoCelular)
	{
		this.contactoCelular = contactoCelular;
		this.contactoCelularModified = true;
	}

	/** 
	 * Sets the value of contactoCelularModified
	 */
	public void setContactoCelularModified(boolean contactoCelularModified)
	{
		this.contactoCelularModified = contactoCelularModified;
	}

	/** 
	 * Gets the value of contactoCelularModified
	 */
	public boolean isContactoCelularModified()
	{
		return contactoCelularModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Empresa)) {
			return false;
		}
		
		final Empresa _cast = (Empresa) _other;
		if (idEmpresa != _cast.idEmpresa) {
			return false;
		}
		
		if (idEmpresaModified != _cast.idEmpresaModified) {
			return false;
		}
		
		if (idEmpresaPadre != _cast.idEmpresaPadre) {
			return false;
		}
		
		if (idEmpresaPadreNull != _cast.idEmpresaPadreNull) {
			return false;
		}
		
		if (idEmpresaPadreModified != _cast.idEmpresaPadreModified) {
			return false;
		}
		
		if (idUbicacionFiscal != _cast.idUbicacionFiscal) {
			return false;
		}
		
		if (idUbicacionFiscalModified != _cast.idUbicacionFiscalModified) {
			return false;
		}
		
		if (idTipoEmpresa != _cast.idTipoEmpresa) {
			return false;
		}
		
		if (idTipoEmpresaModified != _cast.idTipoEmpresaModified) {
			return false;
		}
		
		if (rfc == null ? _cast.rfc != rfc : !rfc.equals( _cast.rfc )) {
			return false;
		}
		
		if (rfcModified != _cast.rfcModified) {
			return false;
		}
		
		if (razonSocial == null ? _cast.razonSocial != razonSocial : !razonSocial.equals( _cast.razonSocial )) {
			return false;
		}
		
		if (razonSocialModified != _cast.razonSocialModified) {
			return false;
		}
		
		if (nombreComercial == null ? _cast.nombreComercial != nombreComercial : !nombreComercial.equals( _cast.nombreComercial )) {
			return false;
		}
		
		if (nombreComercialModified != _cast.nombreComercialModified) {
			return false;
		}
		
		if (foliosDisponibles != _cast.foliosDisponibles) {
			return false;
		}
		
		if (foliosDisponiblesNull != _cast.foliosDisponiblesNull) {
			return false;
		}
		
		if (foliosDisponiblesModified != _cast.foliosDisponiblesModified) {
			return false;
		}
		
		if (regimenFiscal == null ? _cast.regimenFiscal != regimenFiscal : !regimenFiscal.equals( _cast.regimenFiscal )) {
			return false;
		}
		
		if (regimenFiscalModified != _cast.regimenFiscalModified) {
			return false;
		}
		
		if (idEstatus != _cast.idEstatus) {
			return false;
		}
		
		if (idEstatusModified != _cast.idEstatusModified) {
			return false;
		}
		
		if (tipoPdf != _cast.tipoPdf) {
			return false;
		}
		
		if (tipoPdfNull != _cast.tipoPdfNull) {
			return false;
		}
		
		if (tipoPdfModified != _cast.tipoPdfModified) {
			return false;
		}
		
		if (tipoPdfHonorarios != _cast.tipoPdfHonorarios) {
			return false;
		}
		
		if (tipoPdfHonorariosNull != _cast.tipoPdfHonorariosNull) {
			return false;
		}
		
		if (tipoPdfHonorariosModified != _cast.tipoPdfHonorariosModified) {
			return false;
		}
		
		if (tipoPdfArrendamiento != _cast.tipoPdfArrendamiento) {
			return false;
		}
		
		if (tipoPdfArrendamientoNull != _cast.tipoPdfArrendamientoNull) {
			return false;
		}
		
		if (tipoPdfArrendamientoModified != _cast.tipoPdfArrendamientoModified) {
			return false;
		}
		
		if (idVendedor != _cast.idVendedor) {
			return false;
		}
		
		if (idVendedorNull != _cast.idVendedorNull) {
			return false;
		}
		
		if (idVendedorModified != _cast.idVendedorModified) {
			return false;
		}
		
		if (tipoPago != _cast.tipoPago) {
			return false;
		}
		
		if (tipoPagoNull != _cast.tipoPagoNull) {
			return false;
		}
		
		if (tipoPagoModified != _cast.tipoPagoModified) {
			return false;
		}
		
		if (idPago != _cast.idPago) {
			return false;
		}
		
		if (idPagoNull != _cast.idPagoNull) {
			return false;
		}
		
		if (idPagoModified != _cast.idPagoModified) {
			return false;
		}
		
		if (idPaquete != _cast.idPaquete) {
			return false;
		}
		
		if (idPaqueteNull != _cast.idPaqueteNull) {
			return false;
		}
		
		if (idPaqueteModified != _cast.idPaqueteModified) {
			return false;
		}
		
		if (referenciaPago == null ? _cast.referenciaPago != referenciaPago : !referenciaPago.equals( _cast.referenciaPago )) {
			return false;
		}
		
		if (referenciaPagoModified != _cast.referenciaPagoModified) {
			return false;
		}
		
		if (fechaRegistro == null ? _cast.fechaRegistro != fechaRegistro : !fechaRegistro.equals( _cast.fechaRegistro )) {
			return false;
		}
		
		if (fechaRegistroModified != _cast.fechaRegistroModified) {
			return false;
		}
		
		if (compartirConceptosMatriz != _cast.compartirConceptosMatriz) {
			return false;
		}
		
		if (compartirConceptosMatrizNull != _cast.compartirConceptosMatrizNull) {
			return false;
		}
		
		if (compartirConceptosMatrizModified != _cast.compartirConceptosMatrizModified) {
			return false;
		}
		
		if (latitud != _cast.latitud) {
			return false;
		}
		
		if (latitudNull != _cast.latitudNull) {
			return false;
		}
		
		if (latitudModified != _cast.latitudModified) {
			return false;
		}
		
		if (longitud != _cast.longitud) {
			return false;
		}
		
		if (longitudNull != _cast.longitudNull) {
			return false;
		}
		
		if (longitudModified != _cast.longitudModified) {
			return false;
		}
		
		if (registroPatronal == null ? _cast.registroPatronal != registroPatronal : !registroPatronal.equals( _cast.registroPatronal )) {
			return false;
		}
		
		if (registroPatronalModified != _cast.registroPatronalModified) {
			return false;
		}
		
		if (creditoValidaXml != _cast.creditoValidaXml) {
			return false;
		}
		
		if (creditoValidaXmlNull != _cast.creditoValidaXmlNull) {
			return false;
		}
		
		if (creditoValidaXmlModified != _cast.creditoValidaXmlModified) {
			return false;
		}
		
		if (creditosDisponiblesSectorPrimario != _cast.creditosDisponiblesSectorPrimario) {
			return false;
		}
		
		if (creditosDisponiblesSectorPrimarioNull != _cast.creditosDisponiblesSectorPrimarioNull) {
			return false;
		}
		
		if (creditosDisponiblesSectorPrimarioModified != _cast.creditosDisponiblesSectorPrimarioModified) {
			return false;
		}
		
		if (addedasPermitidas == null ? _cast.addedasPermitidas != addedasPermitidas : !addedasPermitidas.equals( _cast.addedasPermitidas )) {
			return false;
		}
		
		if (addedasPermitidasModified != _cast.addedasPermitidasModified) {
			return false;
		}
		
		if (idFranquiciatario != _cast.idFranquiciatario) {
			return false;
		}
		
		if (idFranquiciatarioNull != _cast.idFranquiciatarioNull) {
			return false;
		}
		
		if (idFranquiciatarioModified != _cast.idFranquiciatarioModified) {
			return false;
		}
		
		if (mensajePersonalizadoVisita == null ? _cast.mensajePersonalizadoVisita != mensajePersonalizadoVisita : !mensajePersonalizadoVisita.equals( _cast.mensajePersonalizadoVisita )) {
			return false;
		}
		
		if (mensajePersonalizadoVisitaModified != _cast.mensajePersonalizadoVisitaModified) {
			return false;
		}
		
		if (printRazonSocial != _cast.printRazonSocial) {
			return false;
		}
		
		if (printRazonSocialNull != _cast.printRazonSocialNull) {
			return false;
		}
		
		if (printRazonSocialModified != _cast.printRazonSocialModified) {
			return false;
		}
		
		if (printNombreComercial != _cast.printNombreComercial) {
			return false;
		}
		
		if (printNombreComercialNull != _cast.printNombreComercialNull) {
			return false;
		}
		
		if (printNombreComercialModified != _cast.printNombreComercialModified) {
			return false;
		}
		
		if (giro == null ? _cast.giro != giro : !giro.equals( _cast.giro )) {
			return false;
		}
		
		if (giroModified != _cast.giroModified) {
			return false;
		}
		
		if (creditosOperacion != _cast.creditosOperacion) {
			return false;
		}
		
		if (creditosOperacionNull != _cast.creditosOperacionNull) {
			return false;
		}
		
		if (creditosOperacionModified != _cast.creditosOperacionModified) {
			return false;
		}
		
		if (intentosLoginNoCreditos != _cast.intentosLoginNoCreditos) {
			return false;
		}
		
		if (intentosLoginNoCreditosNull != _cast.intentosLoginNoCreditosNull) {
			return false;
		}
		
		if (intentosLoginNoCreditosModified != _cast.intentosLoginNoCreditosModified) {
			return false;
		}
		
		if (printTkProds != _cast.printTkProds) {
			return false;
		}
		
		if (printTkProdsNull != _cast.printTkProdsNull) {
			return false;
		}
		
		if (printTkProdsModified != _cast.printTkProdsModified) {
			return false;
		}
		
		if (tkMovilTipo != _cast.tkMovilTipo) {
			return false;
		}
		
		if (tkMovilTipoNull != _cast.tkMovilTipoNull) {
			return false;
		}
		
		if (tkMovilTipoModified != _cast.tkMovilTipoModified) {
			return false;
		}
		
		if (tkMovilPorMarca != _cast.tkMovilPorMarca) {
			return false;
		}
		
		if (tkMovilPorMarcaNull != _cast.tkMovilPorMarcaNull) {
			return false;
		}
		
		if (tkMovilPorMarcaModified != _cast.tkMovilPorMarcaModified) {
			return false;
		}
		
		if (tkMovilMostrarZona != _cast.tkMovilMostrarZona) {
			return false;
		}
		
		if (tkMovilMostrarZonaNull != _cast.tkMovilMostrarZonaNull) {
			return false;
		}
		
		if (tkMovilMostrarZonaModified != _cast.tkMovilMostrarZonaModified) {
			return false;
		}
		
		if (tkMovilMostrarFolio != _cast.tkMovilMostrarFolio) {
			return false;
		}
		
		if (tkMovilMostrarFolioNull != _cast.tkMovilMostrarFolioNull) {
			return false;
		}
		
		if (tkMovilMostrarFolioModified != _cast.tkMovilMostrarFolioModified) {
			return false;
		}
		
		if (creditosSms != _cast.creditosSms) {
			return false;
		}
		
		if (creditosSmsNull != _cast.creditosSmsNull) {
			return false;
		}
		
		if (creditosSmsModified != _cast.creditosSmsModified) {
			return false;
		}
		
		if (idSmsDispositivoMovil != _cast.idSmsDispositivoMovil) {
			return false;
		}
		
		if (idSmsDispositivoMovilNull != _cast.idSmsDispositivoMovilNull) {
			return false;
		}
		
		if (idSmsDispositivoMovilModified != _cast.idSmsDispositivoMovilModified) {
			return false;
		}
		
		if (contactoCelular == null ? _cast.contactoCelular != contactoCelular : !contactoCelular.equals( _cast.contactoCelular )) {
			return false;
		}
		
		if (contactoCelularModified != _cast.contactoCelularModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idEmpresa;
		_hashCode = 29 * _hashCode + (idEmpresaModified ? 1 : 0);
		_hashCode = 29 * _hashCode + idEmpresaPadre;
		_hashCode = 29 * _hashCode + (idEmpresaPadreNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (idEmpresaPadreModified ? 1 : 0);
		_hashCode = 29 * _hashCode + idUbicacionFiscal;
		_hashCode = 29 * _hashCode + (idUbicacionFiscalModified ? 1 : 0);
		_hashCode = 29 * _hashCode + idTipoEmpresa;
		_hashCode = 29 * _hashCode + (idTipoEmpresaModified ? 1 : 0);
		if (rfc != null) {
			_hashCode = 29 * _hashCode + rfc.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (rfcModified ? 1 : 0);
		if (razonSocial != null) {
			_hashCode = 29 * _hashCode + razonSocial.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (razonSocialModified ? 1 : 0);
		if (nombreComercial != null) {
			_hashCode = 29 * _hashCode + nombreComercial.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (nombreComercialModified ? 1 : 0);
		_hashCode = 29 * _hashCode + foliosDisponibles;
		_hashCode = 29 * _hashCode + (foliosDisponiblesNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (foliosDisponiblesModified ? 1 : 0);
		if (regimenFiscal != null) {
			_hashCode = 29 * _hashCode + regimenFiscal.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (regimenFiscalModified ? 1 : 0);
		_hashCode = 29 * _hashCode + idEstatus;
		_hashCode = 29 * _hashCode + (idEstatusModified ? 1 : 0);
		_hashCode = 29 * _hashCode + tipoPdf;
		_hashCode = 29 * _hashCode + (tipoPdfNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (tipoPdfModified ? 1 : 0);
		_hashCode = 29 * _hashCode + tipoPdfHonorarios;
		_hashCode = 29 * _hashCode + (tipoPdfHonorariosNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (tipoPdfHonorariosModified ? 1 : 0);
		_hashCode = 29 * _hashCode + tipoPdfArrendamiento;
		_hashCode = 29 * _hashCode + (tipoPdfArrendamientoNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (tipoPdfArrendamientoModified ? 1 : 0);
		_hashCode = 29 * _hashCode + idVendedor;
		_hashCode = 29 * _hashCode + (idVendedorNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (idVendedorModified ? 1 : 0);
		_hashCode = 29 * _hashCode + tipoPago;
		_hashCode = 29 * _hashCode + (tipoPagoNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (tipoPagoModified ? 1 : 0);
		_hashCode = 29 * _hashCode + idPago;
		_hashCode = 29 * _hashCode + (idPagoNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (idPagoModified ? 1 : 0);
		_hashCode = 29 * _hashCode + idPaquete;
		_hashCode = 29 * _hashCode + (idPaqueteNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (idPaqueteModified ? 1 : 0);
		if (referenciaPago != null) {
			_hashCode = 29 * _hashCode + referenciaPago.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (referenciaPagoModified ? 1 : 0);
		if (fechaRegistro != null) {
			_hashCode = 29 * _hashCode + fechaRegistro.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (fechaRegistroModified ? 1 : 0);
		_hashCode = 29 * _hashCode + compartirConceptosMatriz;
		_hashCode = 29 * _hashCode + (compartirConceptosMatrizNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (compartirConceptosMatrizModified ? 1 : 0);
		long temp_latitud = Double.doubleToLongBits(latitud);
		_hashCode = 29 * _hashCode + (int) (temp_latitud ^ (temp_latitud >>> 32));
		_hashCode = 29 * _hashCode + (latitudNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (latitudModified ? 1 : 0);
		long temp_longitud = Double.doubleToLongBits(longitud);
		_hashCode = 29 * _hashCode + (int) (temp_longitud ^ (temp_longitud >>> 32));
		_hashCode = 29 * _hashCode + (longitudNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (longitudModified ? 1 : 0);
		if (registroPatronal != null) {
			_hashCode = 29 * _hashCode + registroPatronal.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (registroPatronalModified ? 1 : 0);
		_hashCode = 29 * _hashCode + creditoValidaXml;
		_hashCode = 29 * _hashCode + (creditoValidaXmlNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (creditoValidaXmlModified ? 1 : 0);
		_hashCode = 29 * _hashCode + creditosDisponiblesSectorPrimario;
		_hashCode = 29 * _hashCode + (creditosDisponiblesSectorPrimarioNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (creditosDisponiblesSectorPrimarioModified ? 1 : 0);
		if (addedasPermitidas != null) {
			_hashCode = 29 * _hashCode + addedasPermitidas.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (addedasPermitidasModified ? 1 : 0);
		_hashCode = 29 * _hashCode + idFranquiciatario;
		_hashCode = 29 * _hashCode + (idFranquiciatarioNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (idFranquiciatarioModified ? 1 : 0);
		if (mensajePersonalizadoVisita != null) {
			_hashCode = 29 * _hashCode + mensajePersonalizadoVisita.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (mensajePersonalizadoVisitaModified ? 1 : 0);
		_hashCode = 29 * _hashCode + printRazonSocial;
		_hashCode = 29 * _hashCode + (printRazonSocialNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (printRazonSocialModified ? 1 : 0);
		_hashCode = 29 * _hashCode + printNombreComercial;
		_hashCode = 29 * _hashCode + (printNombreComercialNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (printNombreComercialModified ? 1 : 0);
		if (giro != null) {
			_hashCode = 29 * _hashCode + giro.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (giroModified ? 1 : 0);
		_hashCode = 29 * _hashCode + creditosOperacion;
		_hashCode = 29 * _hashCode + (creditosOperacionNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (creditosOperacionModified ? 1 : 0);
		_hashCode = 29 * _hashCode + intentosLoginNoCreditos;
		_hashCode = 29 * _hashCode + (intentosLoginNoCreditosNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (intentosLoginNoCreditosModified ? 1 : 0);
		_hashCode = 29 * _hashCode + printTkProds;
		_hashCode = 29 * _hashCode + (printTkProdsNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (printTkProdsModified ? 1 : 0);
		_hashCode = 29 * _hashCode + tkMovilTipo;
		_hashCode = 29 * _hashCode + (tkMovilTipoNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (tkMovilTipoModified ? 1 : 0);
		_hashCode = 29 * _hashCode + tkMovilPorMarca;
		_hashCode = 29 * _hashCode + (tkMovilPorMarcaNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (tkMovilPorMarcaModified ? 1 : 0);
		_hashCode = 29 * _hashCode + tkMovilMostrarZona;
		_hashCode = 29 * _hashCode + (tkMovilMostrarZonaNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (tkMovilMostrarZonaModified ? 1 : 0);
		_hashCode = 29 * _hashCode + tkMovilMostrarFolio;
		_hashCode = 29 * _hashCode + (tkMovilMostrarFolioNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (tkMovilMostrarFolioModified ? 1 : 0);
		_hashCode = 29 * _hashCode + creditosSms;
		_hashCode = 29 * _hashCode + (creditosSmsNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (creditosSmsModified ? 1 : 0);
		_hashCode = 29 * _hashCode + idSmsDispositivoMovil;
		_hashCode = 29 * _hashCode + (idSmsDispositivoMovilNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (idSmsDispositivoMovilModified ? 1 : 0);
		if (contactoCelular != null) {
			_hashCode = 29 * _hashCode + contactoCelular.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (contactoCelularModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return EmpresaPk
	 */
	public EmpresaPk createPk()
	{
		return new EmpresaPk(idEmpresa);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.tsp.sct.dao.dto.Empresa: " );
		ret.append( "idEmpresa=" + idEmpresa );
		ret.append( ", idEmpresaPadre=" + idEmpresaPadre );
		ret.append( ", idUbicacionFiscal=" + idUbicacionFiscal );
		ret.append( ", idTipoEmpresa=" + idTipoEmpresa );
		ret.append( ", rfc=" + rfc );
		ret.append( ", razonSocial=" + razonSocial );
		ret.append( ", nombreComercial=" + nombreComercial );
		ret.append( ", foliosDisponibles=" + foliosDisponibles );
		ret.append( ", regimenFiscal=" + regimenFiscal );
		ret.append( ", idEstatus=" + idEstatus );
		ret.append( ", tipoPdf=" + tipoPdf );
		ret.append( ", tipoPdfHonorarios=" + tipoPdfHonorarios );
		ret.append( ", tipoPdfArrendamiento=" + tipoPdfArrendamiento );
		ret.append( ", idVendedor=" + idVendedor );
		ret.append( ", tipoPago=" + tipoPago );
		ret.append( ", idPago=" + idPago );
		ret.append( ", idPaquete=" + idPaquete );
		ret.append( ", referenciaPago=" + referenciaPago );
		ret.append( ", fechaRegistro=" + fechaRegistro );
		ret.append( ", compartirConceptosMatriz=" + compartirConceptosMatriz );
		ret.append( ", latitud=" + latitud );
		ret.append( ", longitud=" + longitud );
		ret.append( ", registroPatronal=" + registroPatronal );
		ret.append( ", creditoValidaXml=" + creditoValidaXml );
		ret.append( ", creditosDisponiblesSectorPrimario=" + creditosDisponiblesSectorPrimario );
		ret.append( ", addedasPermitidas=" + addedasPermitidas );
		ret.append( ", idFranquiciatario=" + idFranquiciatario );
		ret.append( ", mensajePersonalizadoVisita=" + mensajePersonalizadoVisita );
		ret.append( ", printRazonSocial=" + printRazonSocial );
		ret.append( ", printNombreComercial=" + printNombreComercial );
		ret.append( ", giro=" + giro );
		ret.append( ", creditosOperacion=" + creditosOperacion );
		ret.append( ", intentosLoginNoCreditos=" + intentosLoginNoCreditos );
		ret.append( ", printTkProds=" + printTkProds );
		ret.append( ", tkMovilTipo=" + tkMovilTipo );
		ret.append( ", tkMovilPorMarca=" + tkMovilPorMarca );
		ret.append( ", tkMovilMostrarZona=" + tkMovilMostrarZona );
		ret.append( ", tkMovilMostrarFolio=" + tkMovilMostrarFolio );
		ret.append( ", creditosSms=" + creditosSms );
		ret.append( ", idSmsDispositivoMovil=" + idSmsDispositivoMovil );
		ret.append( ", contactoCelular=" + contactoCelular );
		return ret.toString();
	}

}
