/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.tsp.sct.dao.dto;

import com.tsp.sct.dao.dao.*;
import com.tsp.sct.dao.factory.*;
import com.tsp.sct.dao.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class MtzSeguridad implements Serializable
{
	/** 
	 * This attribute maps to the column ID_MTZ_SEGURIDAD in the mtz_seguridad table.
	 */
	protected int idMtzSeguridad;

	/** 
	 * This attribute maps to the column ID_ROLES in the mtz_seguridad table.
	 */
	protected int idRoles;

	/** 
	 * This attribute represents whether the primitive attribute idRoles is null.
	 */
	protected boolean idRolesNull = true;

	/** 
	 * This attribute maps to the column ID_PERMISOS in the mtz_seguridad table.
	 */
	protected int idPermisos;

	/** 
	 * This attribute represents whether the primitive attribute idPermisos is null.
	 */
	protected boolean idPermisosNull = true;

	/** 
	 * This attribute maps to the column ID_APLICATIVO in the mtz_seguridad table.
	 */
	protected int idAplicativo;

	/** 
	 * This attribute represents whether the primitive attribute idAplicativo is null.
	 */
	protected boolean idAplicativoNull = true;

	/**
	 * Method 'MtzSeguridad'
	 * 
	 */
	public MtzSeguridad()
	{
	}

	/**
	 * Method 'getIdMtzSeguridad'
	 * 
	 * @return int
	 */
	public int getIdMtzSeguridad()
	{
		return idMtzSeguridad;
	}

	/**
	 * Method 'setIdMtzSeguridad'
	 * 
	 * @param idMtzSeguridad
	 */
	public void setIdMtzSeguridad(int idMtzSeguridad)
	{
		this.idMtzSeguridad = idMtzSeguridad;
	}

	/**
	 * Method 'getIdRoles'
	 * 
	 * @return int
	 */
	public int getIdRoles()
	{
		return idRoles;
	}

	/**
	 * Method 'setIdRoles'
	 * 
	 * @param idRoles
	 */
	public void setIdRoles(int idRoles)
	{
		this.idRoles = idRoles;
		this.idRolesNull = false;
	}

	/**
	 * Method 'setIdRolesNull'
	 * 
	 * @param value
	 */
	public void setIdRolesNull(boolean value)
	{
		this.idRolesNull = value;
	}

	/**
	 * Method 'isIdRolesNull'
	 * 
	 * @return boolean
	 */
	public boolean isIdRolesNull()
	{
		return idRolesNull;
	}

	/**
	 * Method 'getIdPermisos'
	 * 
	 * @return int
	 */
	public int getIdPermisos()
	{
		return idPermisos;
	}

	/**
	 * Method 'setIdPermisos'
	 * 
	 * @param idPermisos
	 */
	public void setIdPermisos(int idPermisos)
	{
		this.idPermisos = idPermisos;
		this.idPermisosNull = false;
	}

	/**
	 * Method 'setIdPermisosNull'
	 * 
	 * @param value
	 */
	public void setIdPermisosNull(boolean value)
	{
		this.idPermisosNull = value;
	}

	/**
	 * Method 'isIdPermisosNull'
	 * 
	 * @return boolean
	 */
	public boolean isIdPermisosNull()
	{
		return idPermisosNull;
	}

	/**
	 * Method 'getIdAplicativo'
	 * 
	 * @return int
	 */
	public int getIdAplicativo()
	{
		return idAplicativo;
	}

	/**
	 * Method 'setIdAplicativo'
	 * 
	 * @param idAplicativo
	 */
	public void setIdAplicativo(int idAplicativo)
	{
		this.idAplicativo = idAplicativo;
		this.idAplicativoNull = false;
	}

	/**
	 * Method 'setIdAplicativoNull'
	 * 
	 * @param value
	 */
	public void setIdAplicativoNull(boolean value)
	{
		this.idAplicativoNull = value;
	}

	/**
	 * Method 'isIdAplicativoNull'
	 * 
	 * @return boolean
	 */
	public boolean isIdAplicativoNull()
	{
		return idAplicativoNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof MtzSeguridad)) {
			return false;
		}
		
		final MtzSeguridad _cast = (MtzSeguridad) _other;
		if (idMtzSeguridad != _cast.idMtzSeguridad) {
			return false;
		}
		
		if (idRoles != _cast.idRoles) {
			return false;
		}
		
		if (idRolesNull != _cast.idRolesNull) {
			return false;
		}
		
		if (idPermisos != _cast.idPermisos) {
			return false;
		}
		
		if (idPermisosNull != _cast.idPermisosNull) {
			return false;
		}
		
		if (idAplicativo != _cast.idAplicativo) {
			return false;
		}
		
		if (idAplicativoNull != _cast.idAplicativoNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idMtzSeguridad;
		_hashCode = 29 * _hashCode + idRoles;
		_hashCode = 29 * _hashCode + (idRolesNull ? 1 : 0);
		_hashCode = 29 * _hashCode + idPermisos;
		_hashCode = 29 * _hashCode + (idPermisosNull ? 1 : 0);
		_hashCode = 29 * _hashCode + idAplicativo;
		_hashCode = 29 * _hashCode + (idAplicativoNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return MtzSeguridadPk
	 */
	public MtzSeguridadPk createPk()
	{
		return new MtzSeguridadPk(idMtzSeguridad);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.tsp.sct.dao.dto.MtzSeguridad: " );
		ret.append( "idMtzSeguridad=" + idMtzSeguridad );
		ret.append( ", idRoles=" + idRoles );
		ret.append( ", idPermisos=" + idPermisos );
		ret.append( ", idAplicativo=" + idAplicativo );
		return ret.toString();
	}

}
