/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.tsp.sct.dao.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the nomina_regimen_fiscal table.
 */
public class NominaRegimenFiscalPk implements Serializable
{
	protected int idRegimen;

	/** 
	 * This attribute represents whether the primitive attribute idRegimen is null.
	 */
	protected boolean idRegimenNull;

	/** 
	 * Sets the value of idRegimen
	 */
	public void setIdRegimen(int idRegimen)
	{
		this.idRegimen = idRegimen;
	}

	/** 
	 * Gets the value of idRegimen
	 */
	public int getIdRegimen()
	{
		return idRegimen;
	}

	/**
	 * Method 'NominaRegimenFiscalPk'
	 * 
	 */
	public NominaRegimenFiscalPk()
	{
	}

	/**
	 * Method 'NominaRegimenFiscalPk'
	 * 
	 * @param idRegimen
	 */
	public NominaRegimenFiscalPk(final int idRegimen)
	{
		this.idRegimen = idRegimen;
	}

	/** 
	 * Sets the value of idRegimenNull
	 */
	public void setIdRegimenNull(boolean idRegimenNull)
	{
		this.idRegimenNull = idRegimenNull;
	}

	/** 
	 * Gets the value of idRegimenNull
	 */
	public boolean isIdRegimenNull()
	{
		return idRegimenNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof NominaRegimenFiscalPk)) {
			return false;
		}
		
		final NominaRegimenFiscalPk _cast = (NominaRegimenFiscalPk) _other;
		if (idRegimen != _cast.idRegimen) {
			return false;
		}
		
		if (idRegimenNull != _cast.idRegimenNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idRegimen;
		_hashCode = 29 * _hashCode + (idRegimenNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.tsp.sct.dao.dto.NominaRegimenFiscalPk: " );
		ret.append( "idRegimen=" + idRegimen );
		return ret.toString();
	}

}
