/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.tsp.sct.dao.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the via_embarque table.
 */
public class ViaEmbarquePk implements Serializable
{
	protected int idViaEmbarque;

	/** 
	 * This attribute represents whether the primitive attribute idViaEmbarque is null.
	 */
	protected boolean idViaEmbarqueNull;

	/** 
	 * Sets the value of idViaEmbarque
	 */
	public void setIdViaEmbarque(int idViaEmbarque)
	{
		this.idViaEmbarque = idViaEmbarque;
	}

	/** 
	 * Gets the value of idViaEmbarque
	 */
	public int getIdViaEmbarque()
	{
		return idViaEmbarque;
	}

	/**
	 * Method 'ViaEmbarquePk'
	 * 
	 */
	public ViaEmbarquePk()
	{
	}

	/**
	 * Method 'ViaEmbarquePk'
	 * 
	 * @param idViaEmbarque
	 */
	public ViaEmbarquePk(final int idViaEmbarque)
	{
		this.idViaEmbarque = idViaEmbarque;
	}

	/** 
	 * Sets the value of idViaEmbarqueNull
	 */
	public void setIdViaEmbarqueNull(boolean idViaEmbarqueNull)
	{
		this.idViaEmbarqueNull = idViaEmbarqueNull;
	}

	/** 
	 * Gets the value of idViaEmbarqueNull
	 */
	public boolean isIdViaEmbarqueNull()
	{
		return idViaEmbarqueNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof ViaEmbarquePk)) {
			return false;
		}
		
		final ViaEmbarquePk _cast = (ViaEmbarquePk) _other;
		if (idViaEmbarque != _cast.idViaEmbarque) {
			return false;
		}
		
		if (idViaEmbarqueNull != _cast.idViaEmbarqueNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idViaEmbarque;
		_hashCode = 29 * _hashCode + (idViaEmbarqueNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.tsp.sct.dao.dto.ViaEmbarquePk: " );
		ret.append( "idViaEmbarque=" + idViaEmbarque );
		return ret.toString();
	}

}
