ALTER TABLE EMPRESA ADD REGISTRO_PATRONAL VARCHAR(100) DEFAULT '' COMMENT 'NUMERO DE REGISTRO PATRONAL ANTE EL IMSS';

--MODULO DE DEPARTAMENTOS:
CREATE TABLE NOMINA_DEPARTAMENTO(
    ID_DEPARTAMENTO INT(10) NOT NULL AUTO_INCREMENT,
    ID_EMPRESA INT(10) NOT NULL,
    ID_ESTATUS INT(2),
    NOMBRE VARCHAR(30),
    DESCRIPCION VARCHAR(500),
    PRIMARY KEY (ID_DEPARTAMENTO)
);

--MODULO DE PRESTACIONES
--CREATE TABLE NOMINA_PRESTACIONES(
--    ID_PRESTACIONES INT(10) NOT NULL AUTO_INCREMENT,
--    ID_EMPRESA INT(10) NOT NULL,
--    ID_ESTATUS INT(2),
--    NOMBRE VARCHAR(30),
--    DESCRIPCION VARCHAR(500),
--    PRIMARY KEY (ID_PRESTACIONES)
--);

--
CREATE TABLE NOMINA_REGIMEN_FISCAL
(
   ID_REGIMEN INT(10) NOT NULL AUTO_INCREMENT,
   REGIMEN_FISCAL VARCHAR(80) COMMENT 'NOMBRE DEL REGIMEN QUE LO IDENTIFICA',
   CLAVE INT(10) COMMENT 'EXPRESION DE LA CLAVE DEL REGIMEN, EN BASE AL CATALOGO DEL SAT',
   PRIMARY KEY (ID_REGIMEN)
);

INSERT INTO NOMINA_REGIMEN_FISCAL (ID_REGIMEN,REGIMEN_FISCAL,CLAVE) VALUES (1,'Asimilados a salarios',1);
INSERT INTO NOMINA_REGIMEN_FISCAL (ID_REGIMEN,REGIMEN_FISCAL,CLAVE) VALUES (2,'Sueldos y salarios',2);
INSERT INTO NOMINA_REGIMEN_FISCAL (ID_REGIMEN,REGIMEN_FISCAL,CLAVE) VALUES (3,'Jubilados',3);
INSERT INTO NOMINA_REGIMEN_FISCAL (ID_REGIMEN,REGIMEN_FISCAL,CLAVE) VALUES (4,'Pensionados',4);


--MODULO DE PUESTO
CREATE TABLE NOMINA_PUESTO(
    ID_PUESTO INT(10) NOT NULL AUTO_INCREMENT,
    ID_EMPRESA INT(10) NOT NULL,
    ID_ESTATUS INT(2),
    NOMBRE VARCHAR(30) COMMENT 'NOMBRE DEL PUESTO O ACTIVIDAD QUE REALIZA',
    DESCRIPCION VARCHAR(500) COMMENT 'DESCRIPCION DEL PUESTO O ACTIVIDAD QUE REALIZA',
    SUELDO_DIARIO_INTEGRADO DOUBLE NOT NULL,
    PRIMARY KEY (ID_PUESTO)
);

CREATE TABLE NOMINA_PERIODICIDAD_PAGO
(
   ID_PERIODICIDAD_PAGO INT(10) NOT NULL AUTO_INCREMENT,
   ID_EMPRESA INT(10) NOT NULL COMMENT 'SI ES 0 ES REGISTRO GENERICO, SE VE PARA TODAS LAS EMPRESAS',
   NOMBRE VARCHAR(30),
   DESCRIPCION VARCHAR(50) COMMENT 'FORMA EN QUE SE ESTRABLECE EL PAGO DEL SALARIO: DIARIO, SEMANAL, QUINCENAL, CATORCENAL, MENSUAL, BIMESTRAL, UNIDA DE OBRA, COMISION, PRECIO ALZADO, ETC.',
   ID_ESTATUS INT(2),
   PRIMARY KEY (ID_PERIODICIDAD_PAGO)
);

INSERT INTO NOMINA_PERIODICIDAD_PAGO (ID_PERIODICIDAD_PAGO,ID_EMPRESA,NOMBRE,DESCRIPCION,ID_ESTATUS) VALUES (1,0,'DIARIO','DIARIO',1);
INSERT INTO NOMINA_PERIODICIDAD_PAGO (ID_PERIODICIDAD_PAGO,ID_EMPRESA,NOMBRE,DESCRIPCION,ID_ESTATUS) VALUES (2,0,'SEMANAL','SEMANAL',1);
INSERT INTO NOMINA_PERIODICIDAD_PAGO (ID_PERIODICIDAD_PAGO,ID_EMPRESA,NOMBRE,DESCRIPCION,ID_ESTATUS) VALUES (3,0,'QUINCENAL','QUINCENAL',1);
INSERT INTO NOMINA_PERIODICIDAD_PAGO (ID_PERIODICIDAD_PAGO,ID_EMPRESA,NOMBRE,DESCRIPCION,ID_ESTATUS) VALUES (4,0,'CATORCENAL','CATORCENAL',1);
INSERT INTO NOMINA_PERIODICIDAD_PAGO (ID_PERIODICIDAD_PAGO,ID_EMPRESA,NOMBRE,DESCRIPCION,ID_ESTATUS) VALUES (5,0,'MENSUAL','MENSUAL',1);
INSERT INTO NOMINA_PERIODICIDAD_PAGO (ID_PERIODICIDAD_PAGO,ID_EMPRESA,NOMBRE,DESCRIPCION,ID_ESTATUS) VALUES (6,0,'BIMESTRAL','BIMESTRAL',1);
INSERT INTO NOMINA_PERIODICIDAD_PAGO (ID_PERIODICIDAD_PAGO,ID_EMPRESA,NOMBRE,DESCRIPCION,ID_ESTATUS) VALUES (7,0,'UNIDA DE OBRA','UNIDA DE OBRA',1);
INSERT INTO NOMINA_PERIODICIDAD_PAGO (ID_PERIODICIDAD_PAGO,ID_EMPRESA,NOMBRE,DESCRIPCION,ID_ESTATUS) VALUES (8,0,'COMISION','COMISION',1);
INSERT INTO NOMINA_PERIODICIDAD_PAGO (ID_PERIODICIDAD_PAGO,ID_EMPRESA,NOMBRE,DESCRIPCION,ID_ESTATUS) VALUES (9,0,'PRECIO ALZADO','PRECIO ALZADO',1);

--
CREATE TABLE NOMINA_RIESGO_PUESTO
(
   ID_RIESGO_PUESTO INT(10) NOT NULL AUTO_INCREMENT,
   NOMBRE VARCHAR(30),
   DESCRIPCION VARCHAR(50) COMMENT 'CLAVE CONFORME A LA CLASE N Q DEBEN INSCRIBIRSE LOS PATRONES, D ACUERDO A LAS ACTIVIDADES Q DESEMPEÑAN SUS TRABAJADORES, SEGUN LO PREVISTO N L ARTICULO 196 DL REGLAMENTO N MATERIA D AFILIACION CLASIFICACION D EMPRESAS, RECAUDACION Y FISCALIZACION',
   PRIMARY KEY (ID_RIESGO_PUESTO)
);

INSERT INTO NOMINA_RIESGO_PUESTO (ID_RIESGO_PUESTO,NOMBRE,DESCRIPCION) VALUES (1,'Clase I','1');
INSERT INTO NOMINA_RIESGO_PUESTO (ID_RIESGO_PUESTO,NOMBRE,DESCRIPCION) VALUES (2,'Clase II','2');
INSERT INTO NOMINA_RIESGO_PUESTO (ID_RIESGO_PUESTO,NOMBRE,DESCRIPCION) VALUES (3,'Clase III','3');
INSERT INTO NOMINA_RIESGO_PUESTO (ID_RIESGO_PUESTO,NOMBRE,DESCRIPCION) VALUES (4,'Clase IV','4');
INSERT INTO NOMINA_RIESGO_PUESTO (ID_RIESGO_PUESTO,NOMBRE,DESCRIPCION) VALUES (5,'Clase V','5');

--
CREATE TABLE NOMINA_TIPO_CONTRATO
(
   ID_TIPO_CONTRATO INT(10) NOT NULL AUTO_INCREMENT,
   ID_EMPRESA INT(10) NOT NULL COMMENT 'SI ES 0 ES REGISTRO GENERICO, SE VE PARA TODAS LAS EMPRESAS',
   NOMBRE VARCHAR(30),
   DESCRIPCION VARCHAR(50) COMMENT 'TIPO DE CONTRATO QUE TIENE EL TRABAJADOR:  BASE, EVENTUAL, CONFIANZA, SINDICALIZADO, A PRUEBA, ETC.',
   ID_ESTATUS INT(2),
   PRIMARY KEY (ID_TIPO_CONTRATO)
);

INSERT INTO NOMINA_TIPO_CONTRATO (ID_TIPO_CONTRATO,ID_EMPRESA,NOMBRE,DESCRIPCION,ID_ESTATUS) VALUES (1,0,'BASE','BASE',1);
INSERT INTO NOMINA_TIPO_CONTRATO (ID_TIPO_CONTRATO,ID_EMPRESA,NOMBRE,DESCRIPCION,ID_ESTATUS) VALUES (2,0,'EVENTUAL','EVENTUAL',1);
INSERT INTO NOMINA_TIPO_CONTRATO (ID_TIPO_CONTRATO,ID_EMPRESA,NOMBRE,DESCRIPCION,ID_ESTATUS) VALUES (3,0,'CONFIANZA','CONFIANZA',1);
INSERT INTO NOMINA_TIPO_CONTRATO (ID_TIPO_CONTRATO,ID_EMPRESA,NOMBRE,DESCRIPCION,ID_ESTATUS) VALUES (4,0,'SINDICALIZADO','SINDICALIZADO',1);
INSERT INTO NOMINA_TIPO_CONTRATO (ID_TIPO_CONTRATO,ID_EMPRESA,NOMBRE,DESCRIPCION,ID_ESTATUS) VALUES (5,0,'A PRUEBA','A PRUEBA',1);

CREATE TABLE NOMINA_TIPO_DEDUCCION
(
   ID_TIPO_DEDUCCION INT(10) NOT NULL AUTO_INCREMENT,
   DESCRIPCION VARCHAR(100),
   CLAVE VARCHAR(4) COMMENT 'CLAVE AGRUPADORA. CLASIFICA LA DEDUCCION CONFORME AL CATALOGO PUBLICADO EN EL PORTAL DEL SAT',
   COMENTARIO VARCHAR(100),
   PRIMARY KEY (ID_TIPO_DEDUCCION)
);

INSERT INTO NOMINA_TIPO_DEDUCCION (ID_TIPO_DEDUCCION,DESCRIPCION,CLAVE,COMENTARIO) VALUES (1,'Seguridad social','001','');
INSERT INTO NOMINA_TIPO_DEDUCCION (ID_TIPO_DEDUCCION,DESCRIPCION,CLAVE,COMENTARIO) VALUES (2,'ISR','002','');
INSERT INTO NOMINA_TIPO_DEDUCCION (ID_TIPO_DEDUCCION,DESCRIPCION,CLAVE,COMENTARIO) VALUES (3,'Aportaciones a retiro, cesantía en edad avanzada y vejez.','003','');
INSERT INTO NOMINA_TIPO_DEDUCCION (ID_TIPO_DEDUCCION,DESCRIPCION,CLAVE,COMENTARIO) VALUES (4,'Otros','004','');
INSERT INTO NOMINA_TIPO_DEDUCCION (ID_TIPO_DEDUCCION,DESCRIPCION,CLAVE,COMENTARIO) VALUES (5,'Aportaciones a Fondo de vivienda','005','');
INSERT INTO NOMINA_TIPO_DEDUCCION (ID_TIPO_DEDUCCION,DESCRIPCION,CLAVE,COMENTARIO) VALUES (6,'Descuento por incapacidad','006','Sumatoria de los valores de los atributos Descuento del nodo Incapacidad');
INSERT INTO NOMINA_TIPO_DEDUCCION (ID_TIPO_DEDUCCION,DESCRIPCION,CLAVE,COMENTARIO) VALUES (7,'Pensión alimenticia','007','');
INSERT INTO NOMINA_TIPO_DEDUCCION (ID_TIPO_DEDUCCION,DESCRIPCION,CLAVE,COMENTARIO) VALUES (8,'Renta','008','');
INSERT INTO NOMINA_TIPO_DEDUCCION (ID_TIPO_DEDUCCION,DESCRIPCION,CLAVE,COMENTARIO) VALUES (9,'Préstamos provenientes del Fondo Nacional de la Vivienda para los Trabajadores','009','');
INSERT INTO NOMINA_TIPO_DEDUCCION (ID_TIPO_DEDUCCION,DESCRIPCION,CLAVE,COMENTARIO) VALUES (10,'Pago por crédito de vivienda','010','');
INSERT INTO NOMINA_TIPO_DEDUCCION (ID_TIPO_DEDUCCION,DESCRIPCION,CLAVE,COMENTARIO) VALUES (11,'Pago de abonos INFONACOT','011','');
INSERT INTO NOMINA_TIPO_DEDUCCION (ID_TIPO_DEDUCCION,DESCRIPCION,CLAVE,COMENTARIO) VALUES (12,'Anticipo de salarios','012','');
INSERT INTO NOMINA_TIPO_DEDUCCION (ID_TIPO_DEDUCCION,DESCRIPCION,CLAVE,COMENTARIO) VALUES (13,'Pagos hechos con exceso al trabajador','013','');
INSERT INTO NOMINA_TIPO_DEDUCCION (ID_TIPO_DEDUCCION,DESCRIPCION,CLAVE,COMENTARIO) VALUES (14,'Errores','014','');
INSERT INTO NOMINA_TIPO_DEDUCCION (ID_TIPO_DEDUCCION,DESCRIPCION,CLAVE,COMENTARIO) VALUES (15,'Pérdidas','015','');
INSERT INTO NOMINA_TIPO_DEDUCCION (ID_TIPO_DEDUCCION,DESCRIPCION,CLAVE,COMENTARIO) VALUES (16,'Averías','016','');
INSERT INTO NOMINA_TIPO_DEDUCCION (ID_TIPO_DEDUCCION,DESCRIPCION,CLAVE,COMENTARIO) VALUES (17,'Adquisición de artículos producidos por la empresa o establecimiento','017','');
INSERT INTO NOMINA_TIPO_DEDUCCION (ID_TIPO_DEDUCCION,DESCRIPCION,CLAVE,COMENTARIO) VALUES (18,'Cuotas para la constitución y fomento de sociedades cooperativas y de cajas de ahorro','018','');
INSERT INTO NOMINA_TIPO_DEDUCCION (ID_TIPO_DEDUCCION,DESCRIPCION,CLAVE,COMENTARIO) VALUES (19,'Cuotas sindicales','019','');
INSERT INTO NOMINA_TIPO_DEDUCCION (ID_TIPO_DEDUCCION,DESCRIPCION,CLAVE,COMENTARIO) VALUES (20,'Ausencia (Ausentismo)','020','');
INSERT INTO NOMINA_TIPO_DEDUCCION (ID_TIPO_DEDUCCION,DESCRIPCION,CLAVE,COMENTARIO) VALUES (21,'Cuotas obrero patronales','021','');


CREATE TABLE NOMINA_TIPO_INCAPACIDAD
(
   ID_TIPO_INCAPACIDAD INT(10) NOT NULL AUTO_INCREMENT,
   DESCRIPCION VARCHAR(50),
   CLAVE INT(4),
   PRIMARY KEY (ID_TIPO_INCAPACIDAD)
);

INSERT INTO NOMINA_TIPO_INCAPACIDAD (ID_TIPO_INCAPACIDAD,DESCRIPCION,CLAVE) VALUES (1,'Riesgo de trabajo',1);
INSERT INTO NOMINA_TIPO_INCAPACIDAD (ID_TIPO_INCAPACIDAD,DESCRIPCION,CLAVE) VALUES (2,'Enfermedad en general',2);
INSERT INTO NOMINA_TIPO_INCAPACIDAD (ID_TIPO_INCAPACIDAD,DESCRIPCION,CLAVE) VALUES (3,'Maternidad',3);

CREATE TABLE NOMINA_TIPO_JORNADA
(
   ID_TIPO_JORNADA INT(10) NOT NULL AUTO_INCREMENT,
   ID_EMPRESA INT(10) NOT NULL COMMENT 'SI ES 0 ES REGISTRO GENERICO, SE VE PARA TODAS LAS EMPRESAS',
   NOMBRE VARCHAR(30),
   DESCRIPCION VARCHAR(50) COMMENT 'TIPO DE JORNADA QUE CUBRE EL TRABAJADOR:  DIURNA, NOCTURNA, MIXTA, POR HORA, REDUCIDA, CONTINUADA, PARTIDA, POR TURNOS, ETC.',
   ID_ESTATUS INT(2),
   PRIMARY KEY (ID_TIPO_JORNADA)
);

INSERT INTO NOMINA_TIPO_JORNADA (ID_TIPO_JORNADA,ID_EMPRESA,NOMBRE,DESCRIPCION,ID_ESTATUS) VALUES (1,0,'DIURNA','DIURNA',1);
INSERT INTO NOMINA_TIPO_JORNADA (ID_TIPO_JORNADA,ID_EMPRESA,NOMBRE,DESCRIPCION,ID_ESTATUS) VALUES (2,0,'NOCTURNA','NOCTURNA',1);
INSERT INTO NOMINA_TIPO_JORNADA (ID_TIPO_JORNADA,ID_EMPRESA,NOMBRE,DESCRIPCION,ID_ESTATUS) VALUES (3,0,'MIXTA','MIXTA',1);
INSERT INTO NOMINA_TIPO_JORNADA (ID_TIPO_JORNADA,ID_EMPRESA,NOMBRE,DESCRIPCION,ID_ESTATUS) VALUES (4,0,'POR HORA','POR HORA',1);
INSERT INTO NOMINA_TIPO_JORNADA (ID_TIPO_JORNADA,ID_EMPRESA,NOMBRE,DESCRIPCION,ID_ESTATUS) VALUES (5,0,'REDUCIDA','REDUCIDA',1);
INSERT INTO NOMINA_TIPO_JORNADA (ID_TIPO_JORNADA,ID_EMPRESA,NOMBRE,DESCRIPCION,ID_ESTATUS) VALUES (6,0,'CONTINUADA','CONTINUADA',1);
INSERT INTO NOMINA_TIPO_JORNADA (ID_TIPO_JORNADA,ID_EMPRESA,NOMBRE,DESCRIPCION,ID_ESTATUS) VALUES (7,0,'PARTIDA','PARTIDA',1);
INSERT INTO NOMINA_TIPO_JORNADA (ID_TIPO_JORNADA,ID_EMPRESA,NOMBRE,DESCRIPCION,ID_ESTATUS) VALUES (8,0,'POR TURNOS','POR TURNOS',1);

CREATE TABLE NOMINA_TIPO_PERCEPCION
(
   ID_TIPO_PRECEPCION INT(10) NOT NULL AUTO_INCREMENT,
   DESCRIPCION VARCHAR(70) COMMENT 'DESCRIPCION O NOMBRE DEL TIPO DE PERCEPCION',
   CLAVE VARCHAR(4) COMMENT 'CLAVE IDENTIFICADORA EN CATALOGO SAT',
   PRIMARY KEY (ID_TIPO_PRECEPCION)
);

INSERT INTO NOMINA_TIPO_PERCEPCION (ID_TIPO_PRECEPCION,DESCRIPCION,CLAVE) VALUES (1,'Sueldos, Salarios Rayas y Jornales','001');
INSERT INTO NOMINA_TIPO_PERCEPCION (ID_TIPO_PRECEPCION,DESCRIPCION,CLAVE) VALUES (2,'Gratificación Anual (Aguinaldo)','002');
INSERT INTO NOMINA_TIPO_PERCEPCION (ID_TIPO_PRECEPCION,DESCRIPCION,CLAVE) VALUES (3,'Participación de los Trabajadores en las Utilidades PTU','003');
INSERT INTO NOMINA_TIPO_PERCEPCION (ID_TIPO_PRECEPCION,DESCRIPCION,CLAVE) VALUES (4,'Reembolso de Gastos Médicos Dentales y Hospitalarios','004');
INSERT INTO NOMINA_TIPO_PERCEPCION (ID_TIPO_PRECEPCION,DESCRIPCION,CLAVE) VALUES (5,'Fondo de Ahorro','005');
INSERT INTO NOMINA_TIPO_PERCEPCION (ID_TIPO_PRECEPCION,DESCRIPCION,CLAVE) VALUES (6,'Caja de ahorro','006');
INSERT INTO NOMINA_TIPO_PERCEPCION (ID_TIPO_PRECEPCION,DESCRIPCION,CLAVE) VALUES (7,'Vales','007');
INSERT INTO NOMINA_TIPO_PERCEPCION (ID_TIPO_PRECEPCION,DESCRIPCION,CLAVE) VALUES (8,'Ayudas','008');
INSERT INTO NOMINA_TIPO_PERCEPCION (ID_TIPO_PRECEPCION,DESCRIPCION,CLAVE) VALUES (9,'Contribuciones a Cargo del Trabajador Pagadas por el Patrón','009');
INSERT INTO NOMINA_TIPO_PERCEPCION (ID_TIPO_PRECEPCION,DESCRIPCION,CLAVE) VALUES (10,'Premios por puntualidad','010');
INSERT INTO NOMINA_TIPO_PERCEPCION (ID_TIPO_PRECEPCION,DESCRIPCION,CLAVE) VALUES (11,'Prima de Seguro de vida','011');
INSERT INTO NOMINA_TIPO_PERCEPCION (ID_TIPO_PRECEPCION,DESCRIPCION,CLAVE) VALUES (12,'Seguro de Gastos Medicos Mayores','012');
INSERT INTO NOMINA_TIPO_PERCEPCION (ID_TIPO_PRECEPCION,DESCRIPCION,CLAVE) VALUES (13,'Cuotas Sindicales Pagadas por el Patrón','013');
INSERT INTO NOMINA_TIPO_PERCEPCION (ID_TIPO_PRECEPCION,DESCRIPCION,CLAVE) VALUES (14,'Subsidios por incapacidad','014');
INSERT INTO NOMINA_TIPO_PERCEPCION (ID_TIPO_PRECEPCION,DESCRIPCION,CLAVE) VALUES (15,'Becas para trabajadores y/o hijos','015');
INSERT INTO NOMINA_TIPO_PERCEPCION (ID_TIPO_PRECEPCION,DESCRIPCION,CLAVE) VALUES (16,'Otros','016');
INSERT INTO NOMINA_TIPO_PERCEPCION (ID_TIPO_PRECEPCION,DESCRIPCION,CLAVE) VALUES (17,'Subsidio para el empleo','017');
INSERT INTO NOMINA_TIPO_PERCEPCION (ID_TIPO_PRECEPCION,DESCRIPCION,CLAVE) VALUES (18,'Fomento al primer empleo','018');
INSERT INTO NOMINA_TIPO_PERCEPCION (ID_TIPO_PRECEPCION,DESCRIPCION,CLAVE) VALUES (19,'Horas extra','019');
INSERT INTO NOMINA_TIPO_PERCEPCION (ID_TIPO_PRECEPCION,DESCRIPCION,CLAVE) VALUES (20,'Prima dominical','020');
INSERT INTO NOMINA_TIPO_PERCEPCION (ID_TIPO_PRECEPCION,DESCRIPCION,CLAVE) VALUES (21,'Prima vacacional','021');
INSERT INTO NOMINA_TIPO_PERCEPCION (ID_TIPO_PRECEPCION,DESCRIPCION,CLAVE) VALUES (22,'Prima por antigüedad','022');
INSERT INTO NOMINA_TIPO_PERCEPCION (ID_TIPO_PRECEPCION,DESCRIPCION,CLAVE) VALUES (23,'Pagos por separación','023');
INSERT INTO NOMINA_TIPO_PERCEPCION (ID_TIPO_PRECEPCION,DESCRIPCION,CLAVE) VALUES (24,'Seguro de retiro','024');
INSERT INTO NOMINA_TIPO_PERCEPCION (ID_TIPO_PRECEPCION,DESCRIPCION,CLAVE) VALUES (25,'Indeminizaciones','025');
INSERT INTO NOMINA_TIPO_PERCEPCION (ID_TIPO_PRECEPCION,DESCRIPCION,CLAVE) VALUES (26,'Reembolso por funeral','026');
INSERT INTO NOMINA_TIPO_PERCEPCION (ID_TIPO_PRECEPCION,DESCRIPCION,CLAVE) VALUES (27,'Cuotas de seguridad social pagadas por el patrón','027');
INSERT INTO NOMINA_TIPO_PERCEPCION (ID_TIPO_PRECEPCION,DESCRIPCION,CLAVE) VALUES (28,'Comisiones','028');

--MODULO DE EMPLEADO
CREATE TABLE NOMINA_EMPLEADO
(
   ID_EMPLEADO INT(10) NOT NULL AUTO_INCREMENT,
   ID_EMPRESA INT(10) NOT NULL,
   ID_ESTATUS INT(2),
   RFC VARCHAR(13),
   NOMBRE VARCHAR(40),
   APELLIDO_PATERNO VARCHAR(40),
   APELLIDO_MATERNO VARCHAR(40),
   NUM_EMPLEADO VARCHAR(15),
   CURP VARCHAR(35),
   ID_NOMINA_REGIMEN_FISCAL INT(3) COMMENT 'ID EXPRESION DE LA CLAVE DEL REGIMEN POR EL CUAL SE TIENE CONTRATADO AL TRABAJADOR',
   NUM_SEGURO_SOCIAL VARCHAR(20),
   ID_PUESTO INT(10),
   ID_DEPARTAMENTO INT(10),
   CLABE VARCHAR(30) COMMENT 'PARA EXPRESAR LA CLABE BANCARIA EN LA CUAL SE DEPOSITA LA NOMINA',
   ID_NOMINA_BANCO INT(4) COMMENT 'ID EXPRESION DEL BANCO CONFORME AL CATALOGO DONDE SE DEPOSITA LA NOMINA',
   FECHA_INICIO_RELACION_LABORAL DATE,
   FECHA_ALTA DATE,
   TIPO_CONTRATO VARCHAR(40) COMMENT 'TIPO DE CONTRATO QUE TIENE EL TRABAJADOR: BASE, EVENTUAL, CONFIANZA, SINDICALIZADO, A PRUEBA, ETC.',
   TIPO_JORNADA VARCHAR(40) COMMENT 'TIPO DE JORNADA QUE CUBRE EL TRABAJADOR: DIURNA, NOCTURNA, MIXTA, POR HORA, REDUCIDA, CONTINUADA, PARTIDA, POR TURNOS, ETC.',
   PERIODICIDAD_PAGO VARCHAR(40) COMMENT 'FORMA EN QUE SE ESTRABLECE EL PAGO DEL SALARIO: DIARIO, SEMANAL, QUINCENAL, CATORCENAL, MENSUAL, BIMESTRAL, UNIDA DE OBRA, COMISION, PRECIO ALZADO, ETC.',
   SALARIO_BASE_COT_APOR DOUBLE COMMENT 'RETRIBUCION OTORGADA AL TRABAJADOR, X CUOTA DIARIA, GRATIFICACIONES, PERCEPCIONES, ALIMENTACION, HABITACION, PRIMAS, COMISIONES, PRESTACIONES N ESPECIE Y CUALQUIERA OTRA CANTIDAD O PRESTACION Q S ENTREGUE AL TRABAJADOR POR SU TRABAJO',
   ID_RIESGO_PUESTO INT NOT NULL COMMENT 'EN BASE AL CATALOGO DE LA TABLA NOMINA_RIESGO_PUESTO',
   SALARIO_DIARIO_INTEGRADO DOUBLE COMMENT 'SALARIO DIARIO INTEGRADO',
   FECHA_BAJA DATE,
   CORREO VARCHAR(100),
   TELEFONO VARCHAR(30),
   PRIMARY KEY (ID_EMPLEADO)
);

---------
--TABLA DE PERCEPCIONES:
CREATE TABLE NOMINA_PERCEPCION(
    ID_NOMINA_PERCEPCION INT(10) NOT NULL AUTO_INCREMENT,
    ID_EMPRESA INT(10) NOT NULL,
    ID_ESTATUS INT(2),
    ID_NOMINA_TIPO_PERCEPCION INT(3) COMMENT 'CLAVE AGRUPADORA, CLASIFICA LA DEDUCCION CONFORME AL CATALOGO DEL SAT',
    CLAVE VARCHAR(15) COMMENT 'REPRESENTA LA CLAVE DE PERCEPCION DE NOMINA PROPIA DE LA CONTABILIDAD DE CADA PATRON',
    CONCEPTO VARCHAR(300) COMMENT 'DESCRIPCION DEL CONCEPTO',
    IMPORTE_GRAVADO DOUBLE COMMENT 'REPRESENTA EL IMPORTE GRAVADO DE UN CONCEPTO',
    IMPORTE_EXCEPTO DOUBLE COMMENT 'REPRESENTA EL IMPORTE EXENTO DE UN CONCEPTO',
    PRIMARY KEY(ID_NOMINA_PERCEPCION)
);

--TABLA DE DEDUCCIONES:
CREATE TABLE NOMINA_DEDUCCION(
    ID_NOMINA_DEDUCCION INT(10) NOT NULL AUTO_INCREMENT,
    ID_EMPRESA INT(10) NOT NULL,
    ID_ESTATUS INT(2),
    ID_NOMINA_TIPO_DEDUCCION INT(3) COMMENT 'CLAVE AGRUPADORA, CLASIFICA LA DEDUCCION CONFORME AL CATALOGO DEL SAT',
    CLAVE VARCHAR(15) COMMENT 'REPRESENTA LA CLAVE DE PERCEPCION DE NOMINA PROPIA DE LA CONTABILIDAD DE CADA PATRON',
    CONCEPTO VARCHAR(300) COMMENT 'DESCRIPCION DEL CONCEPTO',
    IMPORTE_GRAVADO DOUBLE COMMENT 'REPRESENTA EL IMPORTE GRAVADO DE UN CONCEPTO',
    IMPORTE_EXCEPTO DOUBLE COMMENT 'REPRESENTA EL IMPORTE EXENTO DE UN CONCEPTO',
    PRIMARY KEY(ID_NOMINA_DEDUCCION)
);

--TABLA 1 DE CONTENIDO DE COMPROBANTE NOMINA 
CREATE TABLE NOMINA_COMPROBANTE_DESCRIPCION(
    ID_NOMINA_COMPROBANTE_DESCRIPCION INT(10) NOT NULL AUTO_INCREMENT,
    ID_CROMPROBANTE_FISCAL INT(10) COMMENT 'ID DEL COMPROBANTE, EN LA TABLA COMPROBANTE_FISCAL',
    FECHA_PAGO DATE,
    FECHA_INICIAL_PAGO DATE,
    FECHA_FIN_PAGO DATE,
    NUM_DIAS_PAGADOS DOUBLE,
    ISR_IMPUESTO_PORCENTAJE DOUBLE DEFAULT 0 COMMENT 'PORCENTAJE DE IMPUESTO DE ISR',
    ISR_MONTO_IMPUESTO DOUBLE DEFAULT 0 COMMENT 'MONTO DE LA CANTIDAD DEL IMPUESTO',
    PRIMARY KEY (ID_NOMINA_COMPROBANTE_DESCRIPCION)
);

--TABLA 2 CONTENIDO DE COMPROBANTE NOMINA
CREATE TABLE NOMINA_COMPROBANTE_DESCRIPCION_PERCEPCION_DEDUCCION(
    ID_NOMINA_COMPROBANTE_DESCRIPCION INT(10) NOT NULL AUTO_INCREMENT,
    ID_CROMPROBANTE_FISCAL INT(10) COMMENT 'ID DEL COMPROBANTE, EN LA TABLA COMPROBANTE_FISCAL',
    ID_PERCEPCION_DEDUCCION INT(1) COMMENT '1 SI ES PERCEPCION, 2 SI ES DEDUCCION',
    TIPO_CLAVE VARCHAR(3) COMMENT 'CLAVE AGRUPADORA, CLASIFICA LA DEDUCCION CONFORME AL CATALOGO DEL SAT',
    CLAVE_PATRON VARCHAR(15) COMMENT 'REPRESENTA LA CLAVE DE PERCEPCION DE NOMINA PROPIA DE LA CONTABILIDAD DE CADA PATRON',
    CONCEPTO_DESCRIPCION VARCHAR(300) COMMENT 'DESCRIPCION DEL CONCEPTO',
    IMPORTE_GRAVADO DOUBLE COMMENT 'REPRESENTA EL IMPORTE GRAVADO DE UN CONCEPTO',
    IMPORTE_EXCEPTO DOUBLE COMMENT 'REPRESENTA EL IMPORTE EXENTO DE UN CONCEPTO',
    ID_DE_LA_PERCEPCION_DEDUCCION INT (10) DEFAULT 0,
    PRIMARY KEY (ID_NOMINA_COMPROBANTE_DESCRIPCION)
);

--TABLA 3 CONTENIDO DE COMPROBANTE_NOMINA
CREATE TABLE NOMINA_COMPROBANTE_DESCRIPCION_INCAPACIDAD(
    ID_NOMINA_COMPROBANTE_DESCRIPCION INT(10) NOT NULL AUTO_INCREMENT,
    ID_CROMPROBANTE_FISCAL INT(10) COMMENT 'ID DEL COMPROBANTE, EN LA TABLA COMPROBANTE_FISCAL',
    DIAS_INCAPACIDAD DOUBLE,
    CLAVE_TIPO_INCAPACIDAD INT(2) COMMENT 'CLAVE DEL TIPO DE INCAPACIDAD, CATALOGO DEL SAT',
    DESCUENTO DOUBLE,
    PRIMARY KEY (ID_NOMINA_COMPROBANTE_DESCRIPCION)
);

--TABLA 4 CONTENIDO DE COMPROBANTE_NOMINA
CREATE TABLE NOMINA_COMPROBANTE_DESCRIPCION_HORAS_EXTRA(
    ID_NOMINA_COMPROBANTE_DESCRIPCION INT(10) NOT NULL AUTO_INCREMENT,
    ID_CROMPROBANTE_FISCAL INT(10) COMMENT 'ID DEL COMPROBANTE, EN LA TABLA COMPROBANTE_FISCAL',
    DIAS INT(4) COMMENT 'NUM DE DIAS EN QUE EL TRABAJADOR REALIZO HORAS EXTRA EN EL PERIODO',
    TIPO_HORAS VARCHAR(15) COMMENT 'TIPO DE PAGO DE LAS HORAS EXTRA: DOBLES, TRIPLES',
    IMPORTE_PAGADO DOUBLE,
    PRIMARY KEY (ID_NOMINA_COMPROBANTE_DESCRIPCION)
);

INSERT INTO TIPO_COMPROBANTE (ID_TIPO_COMPROBANTE, NOMBRE, DESCRIPCION) VALUES (40, 'FACTURA NOMINA', 'Documento de Facturacion Nómina');
ALTER TABLE COMPROBANTE_FISCAL ADD NO_CERTIFICADO_SAT VARCHAR(40) DEFAULT '';
ALTER TABLE COMPROBANTE_FISCAL ADD FECHA_TIMBRADO DATETIME DEFAULT NULL;

SELECT ID_COMPROBANTE_FISCAL, ID_TIPO_COMPROBANTE, ID_EMPRESA, ID_CLIENTE, ID_ESTATUS, ID_FOLIO, ID_FORMA_PAGO, ID_TIPO_PAGO, FOLIO_GENERADO, FECHA_IMPRESION, FECHA_CAPTURA, FECHA_PAGO, IMPORTE_SUBTOTAL, IMPUESTOS, IMPORTE_NETO, PARCIALIDAD, CONCEPTO, ARCHIVO_CFD, CADENA_ORIGINAL, SELLO_DIGITAL, COMENTARIOS, ID_DIVISAS, ID_TIPO_MONEDA, TIPO_DE_CAMBIO, UUID, SELLO_SAT, ACUSE_CANCELACION, DESCUENTO, MOTIVO_DESCUENTO, FECHA_VIGENCIA, SECOFI, NUMERO_FACTURA FROM comprobante_fiscal ORDER BY ID_COMPROBANTE_FISCAL DESC LIMIT 1 

ALTER TABLE EMPRESA_PERMISO_APLICACION ADD ACCESO_SGFENS_NOMINA INT(1) DEFAULT 0 COMMENT '0 NO PUEDE ACCEDER A MODULO DE NOMINA, 1 PERMISO DE ACCESO';

