/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.tsp.sct.dao.jdbc;

import com.tsp.sct.dao.dao.*;
import com.tsp.sct.dao.factory.*;
import com.tsp.sct.dao.dto.*;
import com.tsp.sct.dao.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class ClienteCampoAdicionalDaoImpl extends AbstractDAO implements ClienteCampoAdicionalDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT ID_CLIENTE_CAMPO, ID_EMPRESA, ID_ESTATUS, LABEL_NOMBRE, TIPO_LABEL FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( ID_CLIENTE_CAMPO, ID_EMPRESA, ID_ESTATUS, LABEL_NOMBRE, TIPO_LABEL ) VALUES ( ?, ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET ID_CLIENTE_CAMPO = ?, ID_EMPRESA = ?, ID_ESTATUS = ?, LABEL_NOMBRE = ?, TIPO_LABEL = ? WHERE ID_CLIENTE_CAMPO = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE ID_CLIENTE_CAMPO = ?";

	/** 
	 * Index of column ID_CLIENTE_CAMPO
	 */
	protected static final int COLUMN_ID_CLIENTE_CAMPO = 1;

	/** 
	 * Index of column ID_EMPRESA
	 */
	protected static final int COLUMN_ID_EMPRESA = 2;

	/** 
	 * Index of column ID_ESTATUS
	 */
	protected static final int COLUMN_ID_ESTATUS = 3;

	/** 
	 * Index of column LABEL_NOMBRE
	 */
	protected static final int COLUMN_LABEL_NOMBRE = 4;

	/** 
	 * Index of column TIPO_LABEL
	 */
	protected static final int COLUMN_TIPO_LABEL = 5;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 5;

	/** 
	 * Index of primary-key column ID_CLIENTE_CAMPO
	 */
	protected static final int PK_COLUMN_ID_CLIENTE_CAMPO = 1;

	/** 
	 * Inserts a new row in the cliente_campo_adicional table.
	 */
	public ClienteCampoAdicionalPk insert(ClienteCampoAdicional dto) throws ClienteCampoAdicionalDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			StringBuffer sql = new StringBuffer();
			StringBuffer values = new StringBuffer();
			sql.append( "INSERT INTO " + getTableName() + " (" );
			int modifiedCount = 0;
			if (dto.isIdClienteCampoModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "ID_CLIENTE_CAMPO" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isIdEmpresaModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "ID_EMPRESA" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isIdEstatusModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "ID_ESTATUS" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isLabelNombreModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "LABEL_NOMBRE" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isTipoLabelModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "TIPO_LABEL" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (modifiedCount==0) {
				// nothing to insert
				throw new IllegalStateException( "Nothing to insert" );
			}
		
			sql.append( ") VALUES (" );
			sql.append( values );
			sql.append( ")" );
			stmt = conn.prepareStatement( sql.toString(), Statement.RETURN_GENERATED_KEYS );
			int index = 1;
			if (dto.isIdClienteCampoModified()) {
				stmt.setInt( index++, dto.getIdClienteCampo() );
			}
		
			if (dto.isIdEmpresaModified()) {
				stmt.setInt( index++, dto.getIdEmpresa() );
			}
		
			if (dto.isIdEstatusModified()) {
				if (dto.isIdEstatusNull()) {
					stmt.setNull( index++, java.sql.Types.INTEGER );
				} else {
					stmt.setInt( index++, dto.getIdEstatus() );
				}
		
			}
		
			if (dto.isLabelNombreModified()) {
				stmt.setString( index++, dto.getLabelNombre() );
			}
		
			if (dto.isTipoLabelModified()) {
				if (dto.isTipoLabelNull()) {
					stmt.setNull( index++, java.sql.Types.INTEGER );
				} else {
					stmt.setInt( index++, dto.getTipoLabel() );
				}
		
			}
		
			System.out.println( "Executing " + sql.toString() + " with values: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		
			// retrieve values from auto-increment columns
			rs = stmt.getGeneratedKeys();
			if (rs != null && rs.next()) {
				dto.setIdClienteCampo( rs.getInt( 1 ) );
			}
		
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ClienteCampoAdicionalDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the cliente_campo_adicional table.
	 */
	public void update(ClienteCampoAdicionalPk pk, ClienteCampoAdicional dto) throws ClienteCampoAdicionalDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			StringBuffer sql = new StringBuffer();
			sql.append( "UPDATE " + getTableName() + " SET " );
			boolean modified = false;
			if (dto.isIdClienteCampoModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "ID_CLIENTE_CAMPO=?" );
				modified=true;
			}
		
			if (dto.isIdEmpresaModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "ID_EMPRESA=?" );
				modified=true;
			}
		
			if (dto.isIdEstatusModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "ID_ESTATUS=?" );
				modified=true;
			}
		
			if (dto.isLabelNombreModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "LABEL_NOMBRE=?" );
				modified=true;
			}
		
			if (dto.isTipoLabelModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "TIPO_LABEL=?" );
				modified=true;
			}
		
			if (!modified) {
				// nothing to update
				return;
			}
		
			sql.append( " WHERE ID_CLIENTE_CAMPO=?" );
			System.out.println( "Executing " + sql.toString() + " with values: " + dto );
			stmt = conn.prepareStatement( sql.toString() );
			int index = 1;
			if (dto.isIdClienteCampoModified()) {
				stmt.setInt( index++, dto.getIdClienteCampo() );
			}
		
			if (dto.isIdEmpresaModified()) {
				stmt.setInt( index++, dto.getIdEmpresa() );
			}
		
			if (dto.isIdEstatusModified()) {
				if (dto.isIdEstatusNull()) {
					stmt.setNull( index++, java.sql.Types.INTEGER );
				} else {
					stmt.setInt( index++, dto.getIdEstatus() );
				}
		
			}
		
			if (dto.isLabelNombreModified()) {
				stmt.setString( index++, dto.getLabelNombre() );
			}
		
			if (dto.isTipoLabelModified()) {
				if (dto.isTipoLabelNull()) {
					stmt.setNull( index++, java.sql.Types.INTEGER );
				} else {
					stmt.setInt( index++, dto.getTipoLabel() );
				}
		
			}
		
			stmt.setInt( index++, pk.getIdClienteCampo() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ClienteCampoAdicionalDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the cliente_campo_adicional table.
	 */
	public void delete(ClienteCampoAdicionalPk pk) throws ClienteCampoAdicionalDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setInt( 1, pk.getIdClienteCampo() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ClienteCampoAdicionalDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the cliente_campo_adicional table that matches the specified primary-key value.
	 */
	public ClienteCampoAdicional findByPrimaryKey(ClienteCampoAdicionalPk pk) throws ClienteCampoAdicionalDaoException
	{
		return findByPrimaryKey( pk.getIdClienteCampo() );
	}

	/** 
	 * Returns all rows from the cliente_campo_adicional table that match the criteria 'ID_CLIENTE_CAMPO = :idClienteCampo'.
	 */
	public ClienteCampoAdicional findByPrimaryKey(int idClienteCampo) throws ClienteCampoAdicionalDaoException
	{
		ClienteCampoAdicional ret[] = findByDynamicSelect( SQL_SELECT + " WHERE ID_CLIENTE_CAMPO = ?", new Object[] {  new Integer(idClienteCampo) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the cliente_campo_adicional table that match the criteria ''.
	 */
	public ClienteCampoAdicional[] findAll() throws ClienteCampoAdicionalDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY ID_CLIENTE_CAMPO", null );
	}

	/** 
	 * Returns all rows from the cliente_campo_adicional table that match the criteria 'ID_CLIENTE_CAMPO = :idClienteCampo'.
	 */
	public ClienteCampoAdicional[] findWhereIdClienteCampoEquals(int idClienteCampo) throws ClienteCampoAdicionalDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ID_CLIENTE_CAMPO = ? ORDER BY ID_CLIENTE_CAMPO", new Object[] {  new Integer(idClienteCampo) } );
	}

	/** 
	 * Returns all rows from the cliente_campo_adicional table that match the criteria 'ID_EMPRESA = :idEmpresa'.
	 */
	public ClienteCampoAdicional[] findWhereIdEmpresaEquals(int idEmpresa) throws ClienteCampoAdicionalDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ID_EMPRESA = ? ORDER BY ID_EMPRESA", new Object[] {  new Integer(idEmpresa) } );
	}

	/** 
	 * Returns all rows from the cliente_campo_adicional table that match the criteria 'ID_ESTATUS = :idEstatus'.
	 */
	public ClienteCampoAdicional[] findWhereIdEstatusEquals(int idEstatus) throws ClienteCampoAdicionalDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ID_ESTATUS = ? ORDER BY ID_ESTATUS", new Object[] {  new Integer(idEstatus) } );
	}

	/** 
	 * Returns all rows from the cliente_campo_adicional table that match the criteria 'LABEL_NOMBRE = :labelNombre'.
	 */
	public ClienteCampoAdicional[] findWhereLabelNombreEquals(String labelNombre) throws ClienteCampoAdicionalDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE LABEL_NOMBRE = ? ORDER BY LABEL_NOMBRE", new Object[] { labelNombre } );
	}

	/** 
	 * Returns all rows from the cliente_campo_adicional table that match the criteria 'TIPO_LABEL = :tipoLabel'.
	 */
	public ClienteCampoAdicional[] findWhereTipoLabelEquals(int tipoLabel) throws ClienteCampoAdicionalDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE TIPO_LABEL = ? ORDER BY TIPO_LABEL", new Object[] {  new Integer(tipoLabel) } );
	}

	/**
	 * Method 'ClienteCampoAdicionalDaoImpl'
	 * 
	 */
	public ClienteCampoAdicionalDaoImpl()
	{
	}

	/**
	 * Method 'ClienteCampoAdicionalDaoImpl'
	 * 
	 * @param userConn
	 */
	public ClienteCampoAdicionalDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "cliente_campo_adicional";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected ClienteCampoAdicional fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			ClienteCampoAdicional dto = new ClienteCampoAdicional();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected ClienteCampoAdicional[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			ClienteCampoAdicional dto = new ClienteCampoAdicional();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		ClienteCampoAdicional ret[] = new ClienteCampoAdicional[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(ClienteCampoAdicional dto, ResultSet rs) throws SQLException
	{
		dto.setIdClienteCampo( rs.getInt( COLUMN_ID_CLIENTE_CAMPO ) );
		dto.setIdEmpresa( rs.getInt( COLUMN_ID_EMPRESA ) );
		dto.setIdEstatus( rs.getInt( COLUMN_ID_ESTATUS ) );
		if (rs.wasNull()) {
			dto.setIdEstatusNull( true );
		}
		
		dto.setLabelNombre( rs.getString( COLUMN_LABEL_NOMBRE ) );
		dto.setTipoLabel( rs.getInt( COLUMN_TIPO_LABEL ) );
		if (rs.wasNull()) {
			dto.setTipoLabelNull( true );
		}
		
		reset(dto);
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(ClienteCampoAdicional dto)
	{
		dto.setIdClienteCampoModified( false );
		dto.setIdEmpresaModified( false );
		dto.setIdEstatusModified( false );
		dto.setLabelNombreModified( false );
		dto.setTipoLabelModified( false );
	}

	/** 
	 * Returns all rows from the cliente_campo_adicional table that match the specified arbitrary SQL statement
	 */
	public ClienteCampoAdicional[] findByDynamicSelect(String sql, Object[] sqlParams) throws ClienteCampoAdicionalDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ClienteCampoAdicionalDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the cliente_campo_adicional table that match the specified arbitrary SQL statement
	 */
	public ClienteCampoAdicional[] findByDynamicWhere(String sql, Object[] sqlParams) throws ClienteCampoAdicionalDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ClienteCampoAdicionalDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
