/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.tsp.sct.dao.jdbc;

import com.tsp.sct.dao.dao.*;
import com.tsp.sct.dao.factory.*;
import com.tsp.sct.dao.dto.*;
import com.tsp.sct.dao.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class ComprobanteDescripcionPersonalizadaDaoImpl extends AbstractDAO implements ComprobanteDescripcionPersonalizadaDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT ID_COMPROBANTE_DESCRIPCION_PERSONALIZADA, ID_COMPROBANTE_FISCAL, DATOS_DE_PERSONALIZACION FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( ID_COMPROBANTE_DESCRIPCION_PERSONALIZADA, ID_COMPROBANTE_FISCAL, DATOS_DE_PERSONALIZACION ) VALUES ( ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET ID_COMPROBANTE_DESCRIPCION_PERSONALIZADA = ?, ID_COMPROBANTE_FISCAL = ?, DATOS_DE_PERSONALIZACION = ? WHERE ID_COMPROBANTE_DESCRIPCION_PERSONALIZADA = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE ID_COMPROBANTE_DESCRIPCION_PERSONALIZADA = ?";

	/** 
	 * Index of column ID_COMPROBANTE_DESCRIPCION_PERSONALIZADA
	 */
	protected static final int COLUMN_ID_COMPROBANTE_DESCRIPCION_PERSONALIZADA = 1;

	/** 
	 * Index of column ID_COMPROBANTE_FISCAL
	 */
	protected static final int COLUMN_ID_COMPROBANTE_FISCAL = 2;

	/** 
	 * Index of column DATOS_DE_PERSONALIZACION
	 */
	protected static final int COLUMN_DATOS_DE_PERSONALIZACION = 3;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 3;

	/** 
	 * Index of primary-key column ID_COMPROBANTE_DESCRIPCION_PERSONALIZADA
	 */
	protected static final int PK_COLUMN_ID_COMPROBANTE_DESCRIPCION_PERSONALIZADA = 1;

	/** 
	 * Inserts a new row in the comprobante_descripcion_personalizada table.
	 */
	public ComprobanteDescripcionPersonalizadaPk insert(ComprobanteDescripcionPersonalizada dto) throws ComprobanteDescripcionPersonalizadaDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			StringBuffer sql = new StringBuffer();
			StringBuffer values = new StringBuffer();
			sql.append( "INSERT INTO " + getTableName() + " (" );
			int modifiedCount = 0;
			if (dto.isIdComprobanteDescripcionPersonalizadaModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "ID_COMPROBANTE_DESCRIPCION_PERSONALIZADA" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isIdComprobanteFiscalModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "ID_COMPROBANTE_FISCAL" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isDatosDePersonalizacionModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "DATOS_DE_PERSONALIZACION" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (modifiedCount==0) {
				// nothing to insert
				throw new IllegalStateException( "Nothing to insert" );
			}
		
			sql.append( ") VALUES (" );
			sql.append( values );
			sql.append( ")" );
			stmt = conn.prepareStatement( sql.toString() );
			int index = 1;
			if (dto.isIdComprobanteDescripcionPersonalizadaModified()) {
				stmt.setInt( index++, dto.getIdComprobanteDescripcionPersonalizada() );
			}
		
			if (dto.isIdComprobanteFiscalModified()) {
				stmt.setInt( index++, dto.getIdComprobanteFiscal() );
			}
		
			if (dto.isDatosDePersonalizacionModified()) {
				stmt.setString( index++, dto.getDatosDePersonalizacion() );
			}
		
			System.out.println( "Executing " + sql.toString() + " with values: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ComprobanteDescripcionPersonalizadaDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the comprobante_descripcion_personalizada table.
	 */
	public void update(ComprobanteDescripcionPersonalizadaPk pk, ComprobanteDescripcionPersonalizada dto) throws ComprobanteDescripcionPersonalizadaDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			StringBuffer sql = new StringBuffer();
			sql.append( "UPDATE " + getTableName() + " SET " );
			boolean modified = false;
			if (dto.isIdComprobanteDescripcionPersonalizadaModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "ID_COMPROBANTE_DESCRIPCION_PERSONALIZADA=?" );
				modified=true;
			}
		
			if (dto.isIdComprobanteFiscalModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "ID_COMPROBANTE_FISCAL=?" );
				modified=true;
			}
		
			if (dto.isDatosDePersonalizacionModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "DATOS_DE_PERSONALIZACION=?" );
				modified=true;
			}
		
			if (!modified) {
				// nothing to update
				return;
			}
		
			sql.append( " WHERE ID_COMPROBANTE_DESCRIPCION_PERSONALIZADA=?" );
			System.out.println( "Executing " + sql.toString() + " with values: " + dto );
			stmt = conn.prepareStatement( sql.toString() );
			int index = 1;
			if (dto.isIdComprobanteDescripcionPersonalizadaModified()) {
				stmt.setInt( index++, dto.getIdComprobanteDescripcionPersonalizada() );
			}
		
			if (dto.isIdComprobanteFiscalModified()) {
				stmt.setInt( index++, dto.getIdComprobanteFiscal() );
			}
		
			if (dto.isDatosDePersonalizacionModified()) {
				stmt.setString( index++, dto.getDatosDePersonalizacion() );
			}
		
			stmt.setInt( index++, pk.getIdComprobanteDescripcionPersonalizada() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ComprobanteDescripcionPersonalizadaDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the comprobante_descripcion_personalizada table.
	 */
	public void delete(ComprobanteDescripcionPersonalizadaPk pk) throws ComprobanteDescripcionPersonalizadaDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setInt( 1, pk.getIdComprobanteDescripcionPersonalizada() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ComprobanteDescripcionPersonalizadaDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the comprobante_descripcion_personalizada table that matches the specified primary-key value.
	 */
	public ComprobanteDescripcionPersonalizada findByPrimaryKey(ComprobanteDescripcionPersonalizadaPk pk) throws ComprobanteDescripcionPersonalizadaDaoException
	{
		return findByPrimaryKey( pk.getIdComprobanteDescripcionPersonalizada() );
	}

	/** 
	 * Returns all rows from the comprobante_descripcion_personalizada table that match the criteria 'ID_COMPROBANTE_DESCRIPCION_PERSONALIZADA = :idComprobanteDescripcionPersonalizada'.
	 */
	public ComprobanteDescripcionPersonalizada findByPrimaryKey(int idComprobanteDescripcionPersonalizada) throws ComprobanteDescripcionPersonalizadaDaoException
	{
		ComprobanteDescripcionPersonalizada ret[] = findByDynamicSelect( SQL_SELECT + " WHERE ID_COMPROBANTE_DESCRIPCION_PERSONALIZADA = ?", new Object[] {  new Integer(idComprobanteDescripcionPersonalizada) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the comprobante_descripcion_personalizada table that match the criteria ''.
	 */
	public ComprobanteDescripcionPersonalizada[] findAll() throws ComprobanteDescripcionPersonalizadaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY ID_COMPROBANTE_DESCRIPCION_PERSONALIZADA", null );
	}

	/** 
	 * Returns all rows from the comprobante_descripcion_personalizada table that match the criteria 'ID_COMPROBANTE_DESCRIPCION_PERSONALIZADA = :idComprobanteDescripcionPersonalizada'.
	 */
	public ComprobanteDescripcionPersonalizada[] findWhereIdComprobanteDescripcionPersonalizadaEquals(int idComprobanteDescripcionPersonalizada) throws ComprobanteDescripcionPersonalizadaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ID_COMPROBANTE_DESCRIPCION_PERSONALIZADA = ? ORDER BY ID_COMPROBANTE_DESCRIPCION_PERSONALIZADA", new Object[] {  new Integer(idComprobanteDescripcionPersonalizada) } );
	}

	/** 
	 * Returns all rows from the comprobante_descripcion_personalizada table that match the criteria 'ID_COMPROBANTE_FISCAL = :idComprobanteFiscal'.
	 */
	public ComprobanteDescripcionPersonalizada[] findWhereIdComprobanteFiscalEquals(int idComprobanteFiscal) throws ComprobanteDescripcionPersonalizadaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ID_COMPROBANTE_FISCAL = ? ORDER BY ID_COMPROBANTE_FISCAL", new Object[] {  new Integer(idComprobanteFiscal) } );
	}

	/** 
	 * Returns all rows from the comprobante_descripcion_personalizada table that match the criteria 'DATOS_DE_PERSONALIZACION = :datosDePersonalizacion'.
	 */
	public ComprobanteDescripcionPersonalizada[] findWhereDatosDePersonalizacionEquals(String datosDePersonalizacion) throws ComprobanteDescripcionPersonalizadaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE DATOS_DE_PERSONALIZACION = ? ORDER BY DATOS_DE_PERSONALIZACION", new Object[] { datosDePersonalizacion } );
	}

	/**
	 * Method 'ComprobanteDescripcionPersonalizadaDaoImpl'
	 * 
	 */
	public ComprobanteDescripcionPersonalizadaDaoImpl()
	{
	}

	/**
	 * Method 'ComprobanteDescripcionPersonalizadaDaoImpl'
	 * 
	 * @param userConn
	 */
	public ComprobanteDescripcionPersonalizadaDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "comprobante_descripcion_personalizada";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected ComprobanteDescripcionPersonalizada fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			ComprobanteDescripcionPersonalizada dto = new ComprobanteDescripcionPersonalizada();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected ComprobanteDescripcionPersonalizada[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			ComprobanteDescripcionPersonalizada dto = new ComprobanteDescripcionPersonalizada();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		ComprobanteDescripcionPersonalizada ret[] = new ComprobanteDescripcionPersonalizada[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(ComprobanteDescripcionPersonalizada dto, ResultSet rs) throws SQLException
	{
		dto.setIdComprobanteDescripcionPersonalizada( rs.getInt( COLUMN_ID_COMPROBANTE_DESCRIPCION_PERSONALIZADA ) );
		dto.setIdComprobanteFiscal( rs.getInt( COLUMN_ID_COMPROBANTE_FISCAL ) );
		dto.setDatosDePersonalizacion( rs.getString( COLUMN_DATOS_DE_PERSONALIZACION ) );
		reset(dto);
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(ComprobanteDescripcionPersonalizada dto)
	{
		dto.setIdComprobanteDescripcionPersonalizadaModified( false );
		dto.setIdComprobanteFiscalModified( false );
		dto.setDatosDePersonalizacionModified( false );
	}

	/** 
	 * Returns all rows from the comprobante_descripcion_personalizada table that match the specified arbitrary SQL statement
	 */
	public ComprobanteDescripcionPersonalizada[] findByDynamicSelect(String sql, Object[] sqlParams) throws ComprobanteDescripcionPersonalizadaDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ComprobanteDescripcionPersonalizadaDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the comprobante_descripcion_personalizada table that match the specified arbitrary SQL statement
	 */
	public ComprobanteDescripcionPersonalizada[] findByDynamicWhere(String sql, Object[] sqlParams) throws ComprobanteDescripcionPersonalizadaDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ComprobanteDescripcionPersonalizadaDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}
        
        protected final String SQL_SELECT_MAX = "SELECT ID_COMPROBANTE_DESCRIPCION_PERSONALIZADA, ID_COMPROBANTE_FISCAL, DATOS_DE_PERSONALIZACION FROM " + getTableName() + " ORDER BY ID_COMPROBANTE_DESCRIPCION_PERSONALIZADA DESC LIMIT 1 ";
        
        public ComprobanteDescripcionPersonalizada findLast() throws ComprobanteDescripcionPersonalizadaDaoException
        {
          ComprobanteDescripcionPersonalizada ret[] = findByDynamicSelect( SQL_SELECT_MAX , new Object[0] );
          return ret.length==0 ? null : ret[0];
        }

}
