/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.tsp.sct.dao.jdbc;

import com.tsp.sct.dao.dao.*;
import com.tsp.sct.dao.factory.*;
import com.tsp.sct.dao.dto.*;
import com.tsp.sct.dao.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class NominaTipoDeduccionDaoImpl extends AbstractDAO implements NominaTipoDeduccionDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT ID_TIPO_DEDUCCION, DESCRIPCION, CLAVE, COMENTARIO FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( ID_TIPO_DEDUCCION, DESCRIPCION, CLAVE, COMENTARIO ) VALUES ( ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET ID_TIPO_DEDUCCION = ?, DESCRIPCION = ?, CLAVE = ?, COMENTARIO = ? WHERE ID_TIPO_DEDUCCION = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE ID_TIPO_DEDUCCION = ?";

	/** 
	 * Index of column ID_TIPO_DEDUCCION
	 */
	protected static final int COLUMN_ID_TIPO_DEDUCCION = 1;

	/** 
	 * Index of column DESCRIPCION
	 */
	protected static final int COLUMN_DESCRIPCION = 2;

	/** 
	 * Index of column CLAVE
	 */
	protected static final int COLUMN_CLAVE = 3;

	/** 
	 * Index of column COMENTARIO
	 */
	protected static final int COLUMN_COMENTARIO = 4;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 4;

	/** 
	 * Index of primary-key column ID_TIPO_DEDUCCION
	 */
	protected static final int PK_COLUMN_ID_TIPO_DEDUCCION = 1;

	/** 
	 * Inserts a new row in the nomina_tipo_deduccion table.
	 */
	public NominaTipoDeduccionPk insert(NominaTipoDeduccion dto) throws NominaTipoDeduccionDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			StringBuffer sql = new StringBuffer();
			StringBuffer values = new StringBuffer();
			sql.append( "INSERT INTO " + getTableName() + " (" );
			int modifiedCount = 0;
			if (dto.isIdTipoDeduccionModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "ID_TIPO_DEDUCCION" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isDescripcionModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "DESCRIPCION" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isClaveModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "CLAVE" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isComentarioModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "COMENTARIO" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (modifiedCount==0) {
				// nothing to insert
				throw new IllegalStateException( "Nothing to insert" );
			}
		
			sql.append( ") VALUES (" );
			sql.append( values );
			sql.append( ")" );
			stmt = conn.prepareStatement( sql.toString(), Statement.RETURN_GENERATED_KEYS );
			int index = 1;
			if (dto.isIdTipoDeduccionModified()) {
				stmt.setInt( index++, dto.getIdTipoDeduccion() );
			}
		
			if (dto.isDescripcionModified()) {
				stmt.setString( index++, dto.getDescripcion() );
			}
		
			if (dto.isClaveModified()) {
				stmt.setString( index++, dto.getClave() );
			}
		
			if (dto.isComentarioModified()) {
				stmt.setString( index++, dto.getComentario() );
			}
		
			System.out.println( "Executing " + sql.toString() + " with values: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		
			// retrieve values from auto-increment columns
			rs = stmt.getGeneratedKeys();
			if (rs != null && rs.next()) {
				dto.setIdTipoDeduccion( rs.getInt( 1 ) );
			}
		
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new NominaTipoDeduccionDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the nomina_tipo_deduccion table.
	 */
	public void update(NominaTipoDeduccionPk pk, NominaTipoDeduccion dto) throws NominaTipoDeduccionDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			StringBuffer sql = new StringBuffer();
			sql.append( "UPDATE " + getTableName() + " SET " );
			boolean modified = false;
			if (dto.isIdTipoDeduccionModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "ID_TIPO_DEDUCCION=?" );
				modified=true;
			}
		
			if (dto.isDescripcionModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "DESCRIPCION=?" );
				modified=true;
			}
		
			if (dto.isClaveModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "CLAVE=?" );
				modified=true;
			}
		
			if (dto.isComentarioModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "COMENTARIO=?" );
				modified=true;
			}
		
			if (!modified) {
				// nothing to update
				return;
			}
		
			sql.append( " WHERE ID_TIPO_DEDUCCION=?" );
			System.out.println( "Executing " + sql.toString() + " with values: " + dto );
			stmt = conn.prepareStatement( sql.toString() );
			int index = 1;
			if (dto.isIdTipoDeduccionModified()) {
				stmt.setInt( index++, dto.getIdTipoDeduccion() );
			}
		
			if (dto.isDescripcionModified()) {
				stmt.setString( index++, dto.getDescripcion() );
			}
		
			if (dto.isClaveModified()) {
				stmt.setString( index++, dto.getClave() );
			}
		
			if (dto.isComentarioModified()) {
				stmt.setString( index++, dto.getComentario() );
			}
		
			stmt.setInt( index++, pk.getIdTipoDeduccion() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new NominaTipoDeduccionDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the nomina_tipo_deduccion table.
	 */
	public void delete(NominaTipoDeduccionPk pk) throws NominaTipoDeduccionDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setInt( 1, pk.getIdTipoDeduccion() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new NominaTipoDeduccionDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the nomina_tipo_deduccion table that matches the specified primary-key value.
	 */
	public NominaTipoDeduccion findByPrimaryKey(NominaTipoDeduccionPk pk) throws NominaTipoDeduccionDaoException
	{
		return findByPrimaryKey( pk.getIdTipoDeduccion() );
	}

	/** 
	 * Returns all rows from the nomina_tipo_deduccion table that match the criteria 'ID_TIPO_DEDUCCION = :idTipoDeduccion'.
	 */
	public NominaTipoDeduccion findByPrimaryKey(int idTipoDeduccion) throws NominaTipoDeduccionDaoException
	{
		NominaTipoDeduccion ret[] = findByDynamicSelect( SQL_SELECT + " WHERE ID_TIPO_DEDUCCION = ?", new Object[] {  new Integer(idTipoDeduccion) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the nomina_tipo_deduccion table that match the criteria ''.
	 */
	public NominaTipoDeduccion[] findAll() throws NominaTipoDeduccionDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY ID_TIPO_DEDUCCION", null );
	}

	/** 
	 * Returns all rows from the nomina_tipo_deduccion table that match the criteria 'ID_TIPO_DEDUCCION = :idTipoDeduccion'.
	 */
	public NominaTipoDeduccion[] findWhereIdTipoDeduccionEquals(int idTipoDeduccion) throws NominaTipoDeduccionDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ID_TIPO_DEDUCCION = ? ORDER BY ID_TIPO_DEDUCCION", new Object[] {  new Integer(idTipoDeduccion) } );
	}

	/** 
	 * Returns all rows from the nomina_tipo_deduccion table that match the criteria 'DESCRIPCION = :descripcion'.
	 */
	public NominaTipoDeduccion[] findWhereDescripcionEquals(String descripcion) throws NominaTipoDeduccionDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE DESCRIPCION = ? ORDER BY DESCRIPCION", new Object[] { descripcion } );
	}

	/** 
	 * Returns all rows from the nomina_tipo_deduccion table that match the criteria 'CLAVE = :clave'.
	 */
	public NominaTipoDeduccion[] findWhereClaveEquals(String clave) throws NominaTipoDeduccionDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE CLAVE = ? ORDER BY CLAVE", new Object[] { clave } );
	}

	/** 
	 * Returns all rows from the nomina_tipo_deduccion table that match the criteria 'COMENTARIO = :comentario'.
	 */
	public NominaTipoDeduccion[] findWhereComentarioEquals(String comentario) throws NominaTipoDeduccionDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE COMENTARIO = ? ORDER BY COMENTARIO", new Object[] { comentario } );
	}

	/**
	 * Method 'NominaTipoDeduccionDaoImpl'
	 * 
	 */
	public NominaTipoDeduccionDaoImpl()
	{
	}

	/**
	 * Method 'NominaTipoDeduccionDaoImpl'
	 * 
	 * @param userConn
	 */
	public NominaTipoDeduccionDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "nomina_tipo_deduccion";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected NominaTipoDeduccion fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			NominaTipoDeduccion dto = new NominaTipoDeduccion();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected NominaTipoDeduccion[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			NominaTipoDeduccion dto = new NominaTipoDeduccion();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		NominaTipoDeduccion ret[] = new NominaTipoDeduccion[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(NominaTipoDeduccion dto, ResultSet rs) throws SQLException
	{
		dto.setIdTipoDeduccion( rs.getInt( COLUMN_ID_TIPO_DEDUCCION ) );
		dto.setDescripcion( rs.getString( COLUMN_DESCRIPCION ) );
		dto.setClave( rs.getString( COLUMN_CLAVE ) );
		dto.setComentario( rs.getString( COLUMN_COMENTARIO ) );
		reset(dto);
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(NominaTipoDeduccion dto)
	{
		dto.setIdTipoDeduccionModified( false );
		dto.setDescripcionModified( false );
		dto.setClaveModified( false );
		dto.setComentarioModified( false );
	}

	/** 
	 * Returns all rows from the nomina_tipo_deduccion table that match the specified arbitrary SQL statement
	 */
	public NominaTipoDeduccion[] findByDynamicSelect(String sql, Object[] sqlParams) throws NominaTipoDeduccionDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new NominaTipoDeduccionDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the nomina_tipo_deduccion table that match the specified arbitrary SQL statement
	 */
	public NominaTipoDeduccion[] findByDynamicWhere(String sql, Object[] sqlParams) throws NominaTipoDeduccionDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new NominaTipoDeduccionDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
