/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.tsp.sct.dao.jdbc;

import com.tsp.sct.dao.dao.*;
import com.tsp.sct.dao.factory.*;
import java.util.Date;
import com.tsp.sct.dao.dto.*;
import com.tsp.sct.dao.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class PosEstacionDaoImpl extends AbstractDAO implements PosEstacionDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT id_pos_estacion, id_empresa, identificacion, nombre, id_estatus, fecha_hr_ultima_conexion, folio_movil FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( id_pos_estacion, id_empresa, identificacion, nombre, id_estatus, fecha_hr_ultima_conexion, folio_movil ) VALUES ( ?, ?, ?, ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET id_pos_estacion = ?, id_empresa = ?, identificacion = ?, nombre = ?, id_estatus = ?, fecha_hr_ultima_conexion = ?, folio_movil = ? WHERE id_pos_estacion = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE id_pos_estacion = ?";

	/** 
	 * Index of column id_pos_estacion
	 */
	protected static final int COLUMN_ID_POS_ESTACION = 1;

	/** 
	 * Index of column id_empresa
	 */
	protected static final int COLUMN_ID_EMPRESA = 2;

	/** 
	 * Index of column identificacion
	 */
	protected static final int COLUMN_IDENTIFICACION = 3;

	/** 
	 * Index of column nombre
	 */
	protected static final int COLUMN_NOMBRE = 4;

	/** 
	 * Index of column id_estatus
	 */
	protected static final int COLUMN_ID_ESTATUS = 5;

	/** 
	 * Index of column fecha_hr_ultima_conexion
	 */
	protected static final int COLUMN_FECHA_HR_ULTIMA_CONEXION = 6;

	/** 
	 * Index of column folio_movil
	 */
	protected static final int COLUMN_FOLIO_MOVIL = 7;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 7;

	/** 
	 * Index of primary-key column id_pos_estacion
	 */
	protected static final int PK_COLUMN_ID_POS_ESTACION = 1;

	/** 
	 * Inserts a new row in the pos_estacion table.
	 */
	public PosEstacionPk insert(PosEstacion dto) throws PosEstacionDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			StringBuffer sql = new StringBuffer();
			StringBuffer values = new StringBuffer();
			sql.append( "INSERT INTO " + getTableName() + " (" );
			int modifiedCount = 0;
			if (dto.isIdPosEstacionModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "id_pos_estacion" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isIdEmpresaModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "id_empresa" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isIdentificacionModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "identificacion" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isNombreModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "nombre" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isIdEstatusModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "id_estatus" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isFechaHrUltimaConexionModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "fecha_hr_ultima_conexion" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isFolioMovilModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "folio_movil" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (modifiedCount==0) {
				// nothing to insert
				throw new IllegalStateException( "Nothing to insert" );
			}
		
			sql.append( ") VALUES (" );
			sql.append( values );
			sql.append( ")" );
			stmt = conn.prepareStatement( sql.toString(), Statement.RETURN_GENERATED_KEYS );
			int index = 1;
			if (dto.isIdPosEstacionModified()) {
				stmt.setInt( index++, dto.getIdPosEstacion() );
			}
		
			if (dto.isIdEmpresaModified()) {
				stmt.setInt( index++, dto.getIdEmpresa() );
			}
		
			if (dto.isIdentificacionModified()) {
				stmt.setString( index++, dto.getIdentificacion() );
			}
		
			if (dto.isNombreModified()) {
				stmt.setString( index++, dto.getNombre() );
			}
		
			if (dto.isIdEstatusModified()) {
				stmt.setInt( index++, dto.getIdEstatus() );
			}
		
			if (dto.isFechaHrUltimaConexionModified()) {
				stmt.setTimestamp(index++, dto.getFechaHrUltimaConexion()==null ? null : new java.sql.Timestamp( dto.getFechaHrUltimaConexion().getTime() ) );
			}
		
			if (dto.isFolioMovilModified()) {
				stmt.setString( index++, dto.getFolioMovil() );
			}
		
			System.out.println( "Executing " + sql.toString() + " with values: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		
			// retrieve values from auto-increment columns
			rs = stmt.getGeneratedKeys();
			if (rs != null && rs.next()) {
				dto.setIdPosEstacion( rs.getInt( 1 ) );
			}
		
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new PosEstacionDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the pos_estacion table.
	 */
	public void update(PosEstacionPk pk, PosEstacion dto) throws PosEstacionDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			StringBuffer sql = new StringBuffer();
			sql.append( "UPDATE " + getTableName() + " SET " );
			boolean modified = false;
			if (dto.isIdPosEstacionModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "id_pos_estacion=?" );
				modified=true;
			}
		
			if (dto.isIdEmpresaModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "id_empresa=?" );
				modified=true;
			}
		
			if (dto.isIdentificacionModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "identificacion=?" );
				modified=true;
			}
		
			if (dto.isNombreModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "nombre=?" );
				modified=true;
			}
		
			if (dto.isIdEstatusModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "id_estatus=?" );
				modified=true;
			}
		
			if (dto.isFechaHrUltimaConexionModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "fecha_hr_ultima_conexion=?" );
				modified=true;
			}
		
			if (dto.isFolioMovilModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "folio_movil=?" );
				modified=true;
			}
		
			if (!modified) {
				// nothing to update
				return;
			}
		
			sql.append( " WHERE id_pos_estacion=?" );
			System.out.println( "Executing " + sql.toString() + " with values: " + dto );
			stmt = conn.prepareStatement( sql.toString() );
			int index = 1;
			if (dto.isIdPosEstacionModified()) {
				stmt.setInt( index++, dto.getIdPosEstacion() );
			}
		
			if (dto.isIdEmpresaModified()) {
				stmt.setInt( index++, dto.getIdEmpresa() );
			}
		
			if (dto.isIdentificacionModified()) {
				stmt.setString( index++, dto.getIdentificacion() );
			}
		
			if (dto.isNombreModified()) {
				stmt.setString( index++, dto.getNombre() );
			}
		
			if (dto.isIdEstatusModified()) {
				stmt.setInt( index++, dto.getIdEstatus() );
			}
		
			if (dto.isFechaHrUltimaConexionModified()) {
				stmt.setTimestamp(index++, dto.getFechaHrUltimaConexion()==null ? null : new java.sql.Timestamp( dto.getFechaHrUltimaConexion().getTime() ) );
			}
		
			if (dto.isFolioMovilModified()) {
				stmt.setString( index++, dto.getFolioMovil() );
			}
		
			stmt.setInt( index++, pk.getIdPosEstacion() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new PosEstacionDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the pos_estacion table.
	 */
	public void delete(PosEstacionPk pk) throws PosEstacionDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setInt( 1, pk.getIdPosEstacion() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new PosEstacionDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the pos_estacion table that matches the specified primary-key value.
	 */
	public PosEstacion findByPrimaryKey(PosEstacionPk pk) throws PosEstacionDaoException
	{
		return findByPrimaryKey( pk.getIdPosEstacion() );
	}

	/** 
	 * Returns all rows from the pos_estacion table that match the criteria 'id_pos_estacion = :idPosEstacion'.
	 */
	public PosEstacion findByPrimaryKey(int idPosEstacion) throws PosEstacionDaoException
	{
		PosEstacion ret[] = findByDynamicSelect( SQL_SELECT + " WHERE id_pos_estacion = ?", new Object[] {  new Integer(idPosEstacion) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the pos_estacion table that match the criteria ''.
	 */
	public PosEstacion[] findAll() throws PosEstacionDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY id_pos_estacion", null );
	}

	/** 
	 * Returns all rows from the pos_estacion table that match the criteria 'id_pos_estacion = :idPosEstacion'.
	 */
	public PosEstacion[] findWhereIdPosEstacionEquals(int idPosEstacion) throws PosEstacionDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE id_pos_estacion = ? ORDER BY id_pos_estacion", new Object[] {  new Integer(idPosEstacion) } );
	}

	/** 
	 * Returns all rows from the pos_estacion table that match the criteria 'id_empresa = :idEmpresa'.
	 */
	public PosEstacion[] findWhereIdEmpresaEquals(int idEmpresa) throws PosEstacionDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE id_empresa = ? ORDER BY id_empresa", new Object[] {  new Integer(idEmpresa) } );
	}

	/** 
	 * Returns all rows from the pos_estacion table that match the criteria 'identificacion = :identificacion'.
	 */
	public PosEstacion[] findWhereIdentificacionEquals(String identificacion) throws PosEstacionDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE identificacion = ? ORDER BY identificacion", new Object[] { identificacion } );
	}

	/** 
	 * Returns all rows from the pos_estacion table that match the criteria 'nombre = :nombre'.
	 */
	public PosEstacion[] findWhereNombreEquals(String nombre) throws PosEstacionDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE nombre = ? ORDER BY nombre", new Object[] { nombre } );
	}

	/** 
	 * Returns all rows from the pos_estacion table that match the criteria 'id_estatus = :idEstatus'.
	 */
	public PosEstacion[] findWhereIdEstatusEquals(int idEstatus) throws PosEstacionDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE id_estatus = ? ORDER BY id_estatus", new Object[] {  new Integer(idEstatus) } );
	}

	/** 
	 * Returns all rows from the pos_estacion table that match the criteria 'fecha_hr_ultima_conexion = :fechaHrUltimaConexion'.
	 */
	public PosEstacion[] findWhereFechaHrUltimaConexionEquals(Date fechaHrUltimaConexion) throws PosEstacionDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE fecha_hr_ultima_conexion = ? ORDER BY fecha_hr_ultima_conexion", new Object[] { fechaHrUltimaConexion==null ? null : new java.sql.Timestamp( fechaHrUltimaConexion.getTime() ) } );
	}

	/** 
	 * Returns all rows from the pos_estacion table that match the criteria 'folio_movil = :folioMovil'.
	 */
	public PosEstacion[] findWhereFolioMovilEquals(String folioMovil) throws PosEstacionDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE folio_movil = ? ORDER BY folio_movil", new Object[] { folioMovil } );
	}

	/**
	 * Method 'PosEstacionDaoImpl'
	 * 
	 */
	public PosEstacionDaoImpl()
	{
	}

	/**
	 * Method 'PosEstacionDaoImpl'
	 * 
	 * @param userConn
	 */
	public PosEstacionDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "pos_estacion";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected PosEstacion fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			PosEstacion dto = new PosEstacion();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected PosEstacion[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			PosEstacion dto = new PosEstacion();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		PosEstacion ret[] = new PosEstacion[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(PosEstacion dto, ResultSet rs) throws SQLException
	{
		dto.setIdPosEstacion( rs.getInt( COLUMN_ID_POS_ESTACION ) );
		dto.setIdEmpresa( rs.getInt( COLUMN_ID_EMPRESA ) );
		dto.setIdentificacion( rs.getString( COLUMN_IDENTIFICACION ) );
		dto.setNombre( rs.getString( COLUMN_NOMBRE ) );
		dto.setIdEstatus( rs.getInt( COLUMN_ID_ESTATUS ) );
		dto.setFechaHrUltimaConexion( rs.getTimestamp(COLUMN_FECHA_HR_ULTIMA_CONEXION ) );
		dto.setFolioMovil( rs.getString( COLUMN_FOLIO_MOVIL ) );
		reset(dto);
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(PosEstacion dto)
	{
		dto.setIdPosEstacionModified( false );
		dto.setIdEmpresaModified( false );
		dto.setIdentificacionModified( false );
		dto.setNombreModified( false );
		dto.setIdEstatusModified( false );
		dto.setFechaHrUltimaConexionModified( false );
		dto.setFolioMovilModified( false );
	}

	/** 
	 * Returns all rows from the pos_estacion table that match the specified arbitrary SQL statement
	 */
	public PosEstacion[] findByDynamicSelect(String sql, Object[] sqlParams) throws PosEstacionDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new PosEstacionDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the pos_estacion table that match the specified arbitrary SQL statement
	 */
	public PosEstacion[] findByDynamicWhere(String sql, Object[] sqlParams) throws PosEstacionDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new PosEstacionDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
