/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.tsp.sct.dao.dao;

import java.util.Date;
import com.tsp.sct.dao.dto.*;
import com.tsp.sct.dao.exceptions.*;

public interface EmergenciaCreditoFacturaRealizadaDao
{
	/** 
	 * Inserts a new row in the emergencia_credito_factura_realizada table.
	 */
	public EmergenciaCreditoFacturaRealizadaPk insert(EmergenciaCreditoFacturaRealizada dto) throws EmergenciaCreditoFacturaRealizadaDaoException;

	/** 
	 * Updates a single row in the emergencia_credito_factura_realizada table.
	 */
	public void update(EmergenciaCreditoFacturaRealizadaPk pk, EmergenciaCreditoFacturaRealizada dto) throws EmergenciaCreditoFacturaRealizadaDaoException;

	/** 
	 * Deletes a single row in the emergencia_credito_factura_realizada table.
	 */
	public void delete(EmergenciaCreditoFacturaRealizadaPk pk) throws EmergenciaCreditoFacturaRealizadaDaoException;

	/** 
	 * Returns the rows from the emergencia_credito_factura_realizada table that matches the specified primary-key value.
	 */
	public EmergenciaCreditoFacturaRealizada findByPrimaryKey(EmergenciaCreditoFacturaRealizadaPk pk) throws EmergenciaCreditoFacturaRealizadaDaoException;

	/** 
	 * Returns all rows from the emergencia_credito_factura_realizada table that match the criteria 'ID_EMERGENCIA_CREDITO = :idEmergenciaCredito'.
	 */
	public EmergenciaCreditoFacturaRealizada findByPrimaryKey(int idEmergenciaCredito) throws EmergenciaCreditoFacturaRealizadaDaoException;

	/** 
	 * Returns all rows from the emergencia_credito_factura_realizada table that match the criteria ''.
	 */
	public EmergenciaCreditoFacturaRealizada[] findAll() throws EmergenciaCreditoFacturaRealizadaDaoException;

	/** 
	 * Returns all rows from the emergencia_credito_factura_realizada table that match the criteria 'ID_EMERGENCIA_CREDITO = :idEmergenciaCredito'.
	 */
	public EmergenciaCreditoFacturaRealizada[] findWhereIdEmergenciaCreditoEquals(int idEmergenciaCredito) throws EmergenciaCreditoFacturaRealizadaDaoException;

	/** 
	 * Returns all rows from the emergencia_credito_factura_realizada table that match the criteria 'ID_EMERGENCIA = :idEmergencia'.
	 */
	public EmergenciaCreditoFacturaRealizada[] findWhereIdEmergenciaEquals(int idEmergencia) throws EmergenciaCreditoFacturaRealizadaDaoException;

	/** 
	 * Returns all rows from the emergencia_credito_factura_realizada table that match the criteria 'FECHA = :fecha'.
	 */
	public EmergenciaCreditoFacturaRealizada[] findWhereFechaEquals(Date fecha) throws EmergenciaCreditoFacturaRealizadaDaoException;

	/** 
	 * Returns all rows from the emergencia_credito_factura_realizada table that match the criteria 'ID_EMPRESA = :idEmpresa'.
	 */
	public EmergenciaCreditoFacturaRealizada[] findWhereIdEmpresaEquals(int idEmpresa) throws EmergenciaCreditoFacturaRealizadaDaoException;

	/** 
	 * Returns all rows from the emergencia_credito_factura_realizada table that match the criteria 'RFC_EMISOR = :rfcEmisor'.
	 */
	public EmergenciaCreditoFacturaRealizada[] findWhereRfcEmisorEquals(String rfcEmisor) throws EmergenciaCreditoFacturaRealizadaDaoException;

	/** 
	 * Returns all rows from the emergencia_credito_factura_realizada table that match the criteria 'ID_CLIENTE_RECEPTOR = :idClienteReceptor'.
	 */
	public EmergenciaCreditoFacturaRealizada[] findWhereIdClienteReceptorEquals(int idClienteReceptor) throws EmergenciaCreditoFacturaRealizadaDaoException;

	/** 
	 * Returns all rows from the emergencia_credito_factura_realizada table that match the criteria 'RFC_RECEPTOR = :rfcReceptor'.
	 */
	public EmergenciaCreditoFacturaRealizada[] findWhereRfcReceptorEquals(String rfcReceptor) throws EmergenciaCreditoFacturaRealizadaDaoException;

	/** 
	 * Returns all rows from the emergencia_credito_factura_realizada table that match the criteria 'MONTO_FACTURA = :montoFactura'.
	 */
	public EmergenciaCreditoFacturaRealizada[] findWhereMontoFacturaEquals(double montoFactura) throws EmergenciaCreditoFacturaRealizadaDaoException;

	/** 
	 * Returns all rows from the emergencia_credito_factura_realizada table that match the criteria 'UUID = :uuid'.
	 */
	public EmergenciaCreditoFacturaRealizada[] findWhereUuidEquals(String uuid) throws EmergenciaCreditoFacturaRealizadaDaoException;

	/** 
	 * Returns all rows from the emergencia_credito_factura_realizada table that match the criteria 'ID_ESTATUS = :idEstatus'.
	 */
	public EmergenciaCreditoFacturaRealizada[] findWhereIdEstatusEquals(int idEstatus) throws EmergenciaCreditoFacturaRealizadaDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the emergencia_credito_factura_realizada table that match the specified arbitrary SQL statement
	 */
	public EmergenciaCreditoFacturaRealizada[] findByDynamicSelect(String sql, Object[] sqlParams) throws EmergenciaCreditoFacturaRealizadaDaoException;

	/** 
	 * Returns all rows from the emergencia_credito_factura_realizada table that match the specified arbitrary SQL statement
	 */
	public EmergenciaCreditoFacturaRealizada[] findByDynamicWhere(String sql, Object[] sqlParams) throws EmergenciaCreditoFacturaRealizadaDaoException;

}
