/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.tsp.sct.dao.dao;

import com.tsp.sct.dao.dto.*;
import com.tsp.sct.dao.exceptions.*;

public interface NominaTipoDeduccionDao
{
	/** 
	 * Inserts a new row in the nomina_tipo_deduccion table.
	 */
	public NominaTipoDeduccionPk insert(NominaTipoDeduccion dto) throws NominaTipoDeduccionDaoException;

	/** 
	 * Updates a single row in the nomina_tipo_deduccion table.
	 */
	public void update(NominaTipoDeduccionPk pk, NominaTipoDeduccion dto) throws NominaTipoDeduccionDaoException;

	/** 
	 * Deletes a single row in the nomina_tipo_deduccion table.
	 */
	public void delete(NominaTipoDeduccionPk pk) throws NominaTipoDeduccionDaoException;

	/** 
	 * Returns the rows from the nomina_tipo_deduccion table that matches the specified primary-key value.
	 */
	public NominaTipoDeduccion findByPrimaryKey(NominaTipoDeduccionPk pk) throws NominaTipoDeduccionDaoException;

	/** 
	 * Returns all rows from the nomina_tipo_deduccion table that match the criteria 'ID_TIPO_DEDUCCION = :idTipoDeduccion'.
	 */
	public NominaTipoDeduccion findByPrimaryKey(int idTipoDeduccion) throws NominaTipoDeduccionDaoException;

	/** 
	 * Returns all rows from the nomina_tipo_deduccion table that match the criteria ''.
	 */
	public NominaTipoDeduccion[] findAll() throws NominaTipoDeduccionDaoException;

	/** 
	 * Returns all rows from the nomina_tipo_deduccion table that match the criteria 'ID_TIPO_DEDUCCION = :idTipoDeduccion'.
	 */
	public NominaTipoDeduccion[] findWhereIdTipoDeduccionEquals(int idTipoDeduccion) throws NominaTipoDeduccionDaoException;

	/** 
	 * Returns all rows from the nomina_tipo_deduccion table that match the criteria 'DESCRIPCION = :descripcion'.
	 */
	public NominaTipoDeduccion[] findWhereDescripcionEquals(String descripcion) throws NominaTipoDeduccionDaoException;

	/** 
	 * Returns all rows from the nomina_tipo_deduccion table that match the criteria 'CLAVE = :clave'.
	 */
	public NominaTipoDeduccion[] findWhereClaveEquals(String clave) throws NominaTipoDeduccionDaoException;

	/** 
	 * Returns all rows from the nomina_tipo_deduccion table that match the criteria 'COMENTARIO = :comentario'.
	 */
	public NominaTipoDeduccion[] findWhereComentarioEquals(String comentario) throws NominaTipoDeduccionDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the nomina_tipo_deduccion table that match the specified arbitrary SQL statement
	 */
	public NominaTipoDeduccion[] findByDynamicSelect(String sql, Object[] sqlParams) throws NominaTipoDeduccionDaoException;

	/** 
	 * Returns all rows from the nomina_tipo_deduccion table that match the specified arbitrary SQL statement
	 */
	public NominaTipoDeduccion[] findByDynamicWhere(String sql, Object[] sqlParams) throws NominaTipoDeduccionDaoException;

}
