/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.tsp.sct.dao.dao;

import java.util.Date;
import com.tsp.sct.dao.dto.*;
import com.tsp.sct.dao.exceptions.*;

public interface SgfensPedidoEntregaDao
{
	/** 
	 * Inserts a new row in the sgfens_pedido_entrega table.
	 */
	public SgfensPedidoEntregaPk insert(SgfensPedidoEntrega dto) throws SgfensPedidoEntregaDaoException;

	/** 
	 * Updates a single row in the sgfens_pedido_entrega table.
	 */
	public void update(SgfensPedidoEntregaPk pk, SgfensPedidoEntrega dto) throws SgfensPedidoEntregaDaoException;

	/** 
	 * Deletes a single row in the sgfens_pedido_entrega table.
	 */
	public void delete(SgfensPedidoEntregaPk pk) throws SgfensPedidoEntregaDaoException;

	/** 
	 * Returns the rows from the sgfens_pedido_entrega table that matches the specified primary-key value.
	 */
	public SgfensPedidoEntrega findByPrimaryKey(SgfensPedidoEntregaPk pk) throws SgfensPedidoEntregaDaoException;

	/** 
	 * Returns all rows from the sgfens_pedido_entrega table that match the criteria 'id_pedido_entrega = :idPedidoEntrega'.
	 */
	public SgfensPedidoEntrega findByPrimaryKey(int idPedidoEntrega) throws SgfensPedidoEntregaDaoException;

	/** 
	 * Returns all rows from the sgfens_pedido_entrega table that match the criteria ''.
	 */
	public SgfensPedidoEntrega[] findAll() throws SgfensPedidoEntregaDaoException;

	/** 
	 * Returns all rows from the sgfens_pedido_entrega table that match the criteria 'id_pedido_entrega = :idPedidoEntrega'.
	 */
	public SgfensPedidoEntrega[] findWhereIdPedidoEntregaEquals(int idPedidoEntrega) throws SgfensPedidoEntregaDaoException;

	/** 
	 * Returns all rows from the sgfens_pedido_entrega table that match the criteria 'id_empresa = :idEmpresa'.
	 */
	public SgfensPedidoEntrega[] findWhereIdEmpresaEquals(int idEmpresa) throws SgfensPedidoEntregaDaoException;

	/** 
	 * Returns all rows from the sgfens_pedido_entrega table that match the criteria 'id_estatus = :idEstatus'.
	 */
	public SgfensPedidoEntrega[] findWhereIdEstatusEquals(int idEstatus) throws SgfensPedidoEntregaDaoException;

	/** 
	 * Returns all rows from the sgfens_pedido_entrega table that match the criteria 'fecha_hora = :fechaHora'.
	 */
	public SgfensPedidoEntrega[] findWhereFechaHoraEquals(Date fechaHora) throws SgfensPedidoEntregaDaoException;

	/** 
	 * Returns all rows from the sgfens_pedido_entrega table that match the criteria 'id_pedido = :idPedido'.
	 */
	public SgfensPedidoEntrega[] findWhereIdPedidoEquals(int idPedido) throws SgfensPedidoEntregaDaoException;

	/** 
	 * Returns all rows from the sgfens_pedido_entrega table that match the criteria 'id_usuario_vendedor = :idUsuarioVendedor'.
	 */
	public SgfensPedidoEntrega[] findWhereIdUsuarioVendedorEquals(int idUsuarioVendedor) throws SgfensPedidoEntregaDaoException;

	/** 
	 * Returns all rows from the sgfens_pedido_entrega table that match the criteria 'total_cant_entregada = :totalCantEntregada'.
	 */
	public SgfensPedidoEntrega[] findWhereTotalCantEntregadaEquals(double totalCantEntregada) throws SgfensPedidoEntregaDaoException;

	/** 
	 * Returns all rows from the sgfens_pedido_entrega table that match the criteria 'total_cant_entregada_peso = :totalCantEntregadaPeso'.
	 */
	public SgfensPedidoEntrega[] findWhereTotalCantEntregadaPesoEquals(double totalCantEntregadaPeso) throws SgfensPedidoEntregaDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the sgfens_pedido_entrega table that match the specified arbitrary SQL statement
	 */
	public SgfensPedidoEntrega[] findByDynamicSelect(String sql, Object[] sqlParams) throws SgfensPedidoEntregaDaoException;

	/** 
	 * Returns all rows from the sgfens_pedido_entrega table that match the specified arbitrary SQL statement
	 */
	public SgfensPedidoEntrega[] findByDynamicWhere(String sql, Object[] sqlParams) throws SgfensPedidoEntregaDaoException;

}
